### ISSUE TITLE
Does not discover any NUnit test in my .NET core project

### ISSUE THREAD

**Issue by dmitrynovik** [nunit/nunit3-vs-adapter#345] opened 2017-06-21 23:31 UTC
as above

**Comment by jnm2** [comment] 2017-06-22 14:31
I'm thinking this is a dupe of https://github.com/nunit/nunit3-vs-adapter/issues/296

**Comment by jnm2** [comment] 2017-06-22 14:31
Wait never mind, I'll let the .NET Core-knowledgable people handle this.

**Comment by rprouse** [comment] 2017-06-22 20:59
Things to check,

- Read http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/
- Does your test project target .NET Core?
- Are you using the 3.8 alpha 1 adapter?
- Are you referencing `Microsoft.NET.Test.Sdk`?

Beyond that, we need more info to help you. This is working for many people assuming it is setup correctly. Unfortunately the setup isn't as simple as it was for straight .NET Framework tests, but that is the way it works for .NET Core for all test frameworks.

**Closed** 2017-06-25 14:31 UTC
