### ISSUE TITLE
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object, with VS2015

### ISSUE THREAD

**Issue by saiparth** [nunit/nunit3-vs-adapter#781] opened 2020-09-04 13:02 UTC
* NUnit =3.12 and NUnit3TestAdapter =3.17
* Visual Studio preofessional version 15.3.3
* .net version 4.6.1
*  not installed vsix

**Steps to Repro**
1. Create a unit test project
2. Remove mstest in nuget and install nunit and nunittestadapter latest version
3. Create a test with OneTimeSetUp attribute
```
using NUnit.Framework;
using System;

namespace nUnittest
{
    [TestFixture]
    public class UnitTest1
    {
       [OneTimeSetUp]
        public static void OneTimeSetUp()
        {
            Console.WriteLine("OneTimeSetUp");
        }
        [SetUp]
        public void SetUp()
        {
            Console.WriteLine("SetUp");
        }
        [TearDown]
        public void TearDown()
        {
            Console.WriteLine("TearDown");
        }
        [Test]
        public void Test()
        {
            Console.WriteLine("Test");
        }

        [OneTimeTearDown]
        public static void OneTimeTearDown()
        {
            Console.WriteLine("OneTimeTearDown");
        }
    }
}
```
Firs time passes,rebuild the solution>>Observe console >>error will display as mentioned in title ,test will pass,[OneTimeSetUp] / [SetUp] will not be executed
packages.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NUnit" version="3.12.0" targetFramework="net461" />
  <package id="NUnit3TestAdapter" version="3.17.0" targetFramework="net461" />
</packages>
```
Close VS>>Run IFix vstestcache -f >>Rebuild>> works,first time,Test runs, later exception is thrown,One time setup not runs. 
`An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object`

I tried all the workaround mentioned in https://github.com/nunit/nunit3-vs-adapter/issues/261
I tried removing the cache,works for first time,later again the same problem,cant restart everytime
I changed test process acritecture to 64 still same

**Note**
On running through nunit3-console all methods works
```
>nunit3-console D:\automationRepo\nUnitTest\nUnittest\bin\Debug\nUnittest.dll
NUnit Console Runner 3.11.1 (.NET 2.0)
Copyright (c) 2020 Charlie Poole, Rob Prouse
04 September 2020 18:28:56

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    D:\automationRepo\nUnitTest\nUnittest\bin\Debug\nUnittest.dll

SetUp
Test
TearDown
OneTimeSetUp
OneTimeTearDown

Run Settings
    DisposeRunners: True
    WorkDirectory: D:\automationRepo\nUnitTest\nUnittest\bin\Debug
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    RuntimeFramework: net-4.0
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-09-04 12:58:56Z
    End time: 2020-09-04 12:58:57Z
    Duration: 0.909 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by saiparth** [comment] 2020-09-05 05:59
Added sample project.
[nUnitTest.zip](https://github.com/nunit/nunit3-vs-adapter/files/5177586/nUnitTest.zip)

**Comment by OsirisTerje** [comment] 2020-09-05 20:16
@saiparth   Have you checked if this works with earlier versions of the adapter?

**Comment by saiparth** [comment] 2020-09-06 05:56
Checked with 3.12.0 of nunit and 3.11.0 nUnit3TestAdapter after clearing temp files,
Exception was not thrown,But it dint print ontTimeSetup.OneTimeTearDown to console

**Comment by OsirisTerje** [comment] 2020-09-06 11:01
@saiparth Thanks!   That makes sense.   

Now, and this is might be a bit weird:  Can you comment out the OneTimeSetUp and the OneTimeTearDown, and run the tests ?  It should now run green.
Then, uncomment the two methods and run again - what happens now ?

Also, can you copy the Output/Test window messages when it fails ?

**Comment by saiparth** [comment] 2020-09-06 14:25
@OsirisTerje 
3.17 Exception will be thrown in console(It will not become red..like log it will be on console in test output window). Test will not be discovered after this
If not reproduces, The you close VS,clear temp files and open VS>>Rebuild
Below are the logs
```
[06-09-2020 19:38:48 Informational] ------ Load Playlist started ------
[06-09-2020 19:38:48 Informational] ========== Load Playlist finished (0:00:00.0160836) ==========
[06-09-2020 19:38:48 Informational] ------ Discover test started ------
[06-09-2020 19:38:50 Informational] NUnit Adapter 3.17.0.0: Test discovery starting
[06-09-2020 19:38:51 Informational] NUnit Adapter 3.17.0.0: Test discovery complete
[06-09-2020 19:38:52 Informational] ========== Discover test finished: 1 found (0:00:03.1219924) ==========
[06-09-2020 19:38:57 Informational] ------ Discover test started ------
[06-09-2020 19:38:57 Error] An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
[06-09-2020 19:38:57 Informational] ========== Discover test finished: 0 found (0:00:00.2031281) ==========

Commented oneTimeSetUp,OneTimetearDown
[06-09-2020 19:39:53 Error] An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
[06-09-2020 19:39:53 Informational] ========== Discover test finished: 0 found (0:00:00.0700293) ==========

Commented other retained onlt test method
[06-09-2020 19:40:56 Informational] ------ Discover test started ------
[06-09-2020 19:40:56 Error] An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
[06-09-2020 19:40:56 Informational] ========== Discover test finished: 0 found (0:00:00.0852885) ==========
```.

Downgraded adapter to 3.11.0
No exception was logged in test output window, But it dint print the console write line which was inside oneTimeSetup.
Please try to reproduce after clearing temp files

**Comment by Aaron-Corp00** [comment] 2020-09-28 21:12
I encountered a similar problem today (same exception message in the logs)  where my tests would appear on the first build, but after running once the tests and rebuilding the tests would disappear. I cleared my temp files, but the problem persisted. Installing 16.1, manually as an VS extension, in VS2015 seems to have resolved the issue.

**Comment by OsirisTerje** [comment] 2020-09-29 08:39
This issue seems bound to VS2015, not happening with VS2019.

**Comment by saiparth** [comment] 2020-09-29 08:46
I am using Microsoft Visual Studio Professional 2017 Version 15.3.3

**Comment by OsirisTerje** [comment] 2020-09-29 09:13
Can you drop a screenshot of your Test/General settings ?

**Comment by saiparth** [comment] 2020-09-29 09:25
![image](https://user-images.githubusercontent.com/19487229/94540016-992fda00-0263-11eb-9246-2538e9b4c351.png)
I have not selected any, Can you please let me know how to validate if its already selected?

**Comment by OsirisTerje** [comment] 2020-09-29 09:25
@saiparth Not able to repro with 2017,  15.9.25.   Can you upgrade to that version and recheck ?

**Comment by saiparth** [comment] 2020-09-29 09:30
![image](https://user-images.githubusercontent.com/19487229/94540806-85d13e80-0264-11eb-9fe7-7f298f4e3cf9.png)
Ok, Let me try updating

**Comment by saiparth** [comment] 2020-09-29 12:01
Issue was not reproducible with Microsoft Visual Studio Professional 2017 Version 15.9.27. However it dint print the OneTimeSetUp/OneTimeTearDown

**Comment by OsirisTerje** [comment] 2020-09-29 20:04
So, this is an issue with VS 2015 and VS 2017 up to at least 15.3.3, but fixed in at least 15.9.27 and VS 2019.  

The workaround for those on lower versions here is then  to not upgrade to 3.17.  

It is something with VS going on here, and I can't see that we can do anything more about this.  

Thanks for your reports, @saiparth !

**Comment by felipepessoto** [comment] 2020-09-29 20:07
It means NUnit 3.17+ doesn't support VS2015 anymore?

**Comment by OsirisTerje** [comment] 2020-09-29 20:12
@felipepessoto  Yes it does, but this particular bug doesn't seem like something we can fix.  It is triggered by the case shown,  but otherwise you would be fine.  

You can however build your own debug version of the adapter, and then enable debugging to see if you can pinpoint something we can change in the adapter.  You can also raise an issue at Developer Community and ask for what change they did between 2017 15.3 and and 15.9 - that might give a clue too.  

Is there a particular reason why you can't upgrade from VS 2015 ?

**Comment by OsirisTerje** [comment] 2020-09-29 20:33
@felipepessoto Notice you are a MSFT.  You could then ask internally what changed between those two versions.  That would be very helpful.

**Comment by Aaron-Corp00** [comment] 2020-09-29 20:40
"Is there a particular reason why you can't upgrade from VS 2015 ?"

As for myself, I work in a regulated industry. My team needs to support the team's product with VS 2015 for at least the next 2 years. We are only just beginning to talk about updating our core product to 2017 next year. Essentially we don't update until Microsoft stops adding features to a version of Visual Studio and then only when we have a major release where we would run our full suite of Verification tests.

My team doesn't strictly need to update as long as there is a version of the extension for VS 2015 that is stable.

**Comment by OsirisTerje** [comment] 2020-09-30 07:35
@Aaron-Corp00 Which version of the adapter are you currently using (that works)  ?

**Comment by schlati** [comment] 2020-10-02 09:46
I can confirm this issue. I am on VS2015 too and experience the same behaviour (i.e. tests are only discovered only once after startup of the VS, after any further build the discovered tests are gone with the exception of the NUnit3TestDiscoverer).

I could solve this issue by removing the 'Nunit 3 Test Adapter' from Tools > Extensions and Updates, restarting VS and downgrading the NuGet package 'NUnit3TestAdapter' from v3.17.0 to v3.16.1. Hope that helps!

**Comment by Aaron-Corp00** [comment] 2020-10-02 15:11
@OsirisTerje I'm currently running 13.6.0, which is odd because I thought I installed 13.6.1, but its working at the moment so I'll probably leave this as is.

**Comment by OsirisTerje** [comment] 2020-10-04 20:33
With VS2015, the TestAdapter's base class should initialize the internal engine adapter, but for some reason it is found to be null. This does not happen on later VS2017 and VS2019. It seems that the adapter is being kept alive, and then the engine adapter is null'ed during end of first test. This fix ensure the internal engine adapter is recreated if it is null when accessed.

**Comment by OsirisTerje** [comment] 2020-10-04 20:59
@felipepessoto @schlati @saiparth @Aaron-Corp00  I believe the error is found.  I would really appreciate if you can test the package at https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter (NUnit3TestAdapter 4.0.0-dev-01507), and verify if it work for you in your setup.  Please ensure that you have no VSIX installed.  On my repro I can no longer repro the case, but it is a weird case, so I would really need your input here.

**Closed** 2020-10-06 15:02 UTC
Labels: External, VS Issue, closed:done

**Comment by felipepessoto** [comment] 2020-10-06 22:07
Sorry @OsirisTerje I'm really focused in a complex work and can't test it now, since I only have my working machine to test it.

**Comment by saiparth** [comment] 2020-10-07 12:29
@OsirisTerje 
Sorry for delay. Cleared temp files, created new project with 
```
nunit 3.12 
NUnit3TestAdapter 4.0.0-dev-01507
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
```
For above mentioned test, No exception was seen
```
[10/7/2020 5:57:03 PM Informational] ------ Discover test started ------
[10/7/2020 5:57:03 PM Informational] NUnit Adapter 4.0.0.0: Test discovery starting
[10/7/2020 5:57:03 PM Informational] NUnit Adapter 4.0.0.0: Test discovery complete
[10/7/2020 5:57:03 PM Informational] ========== Discover test finished: 1 found (0:00:00.3408487) ==========
[10/7/2020 5:57:13 PM Informational] ------ Run test started ------
[10/7/2020 5:57:16 PM Informational] NUnit Adapter 4.0.0.0: Test execution started
[10/7/2020 5:57:16 PM Informational] Running selected tests in C:\Users\admin\source\repos\UnitTestProject3\UnitTestProject3\bin\Debug\UnitTestProject3.dll
[10/7/2020 5:57:16 PM Informational]    NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run
[10/7/2020 5:57:17 PM Informational] SetUp
Test
TearDown

[10/7/2020 5:57:17 PM Informational] NUnit Adapter 4.0.0.0: Test execution complete
[10/7/2020 5:57:17 PM Informational] ========== Run test finished: 1 run (0:00:04.0671967) ==========
```
However it dint print the OneTimeSetUp/OneTimeTearDown

**Comment by schlati** [comment] 2020-10-07 14:52
@OsirisTerje 


> Sorry @OsirisTerje I'm really focused in a complex work and can't test it now, since I only have my working machine to test it.

Thank you! That fixes the problem for me! (I use VS 2015 Version 14.025431.01 Update 3)

**Comment by shahnawazm786** [comment] 2020-11-26 15:14
Hello all
I am getting error in visual studio 2013
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests.
please help me out 
Thanks

**Comment by OsirisTerje** [comment] 2020-11-26 19:24
@shahnawazm786 A little bit more details would be helpful.

**Comment by pwachira** [comment] 2020-12-23 23:14
Using Vs2015 ;In Nuget,  I uninstalled the latest Nunit , Installed version 3.9.0 to resolve the issue
