### ISSUE TITLE
VSTest.Console.exe with /EnableCodeCoverage does not produce .trx files

### ISSUE THREAD

**Issue by mikanyg** [nunit/nunit3-vs-adapter#100] opened 2015-12-15 11:31 UTC
When using VSO Build vNext on an on-premise build agent, which executes NUnit test using the VSTest build task (https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/VsTest/README.md), then I cannot get code coverage to work.

I have enabled Code Coverage in the build task, which appends /EnableCodeCoverage to the VSTest.Console.exe command. When running my Nunit test either from VSO or from commandline, no .trx file is being generated, when the /EnableCodeCoverage is used.
So the VSO build tasks reports back that no tests are available, but looking in the TestResults folder, I can see the .coverage file, that contains information about the test run as well as proper code coverage information (all timestamps are correct).

When removing code coverage everything works as expected and VSO publishes a proper test result.

I suspect the issue is in the NUnit3TestAdapter, since MSTest works fine with and without Code Coverage enabled.

**Comment by CharliePoole** [comment] 2015-12-16 15:13
@OsirisTerje This one involves software I don't have access to. Can you review?

**Comment by OsirisTerje** [comment] 2015-12-16 19:48
I'll create a repro.

**Comment by mikanyg** [comment] 2016-02-01 11:17
I have had a look at the issue again, and it seems to be related to the Nunit3 test adapter .vsix extension. When the extension is installed and a project references the nunit3testadapter nuget package, then no tests are found. Uninstalling the .vsix seems to fix the issue. Removed it from my custom build agent and enabled code coverage, and now everything works as expected.

**Comment by CharliePoole** [comment] 2016-07-03 07:53
Closing this as not a bug (of ours).

**Closed by CharliePoole** 2016-07-03 07:53 UTC
