### ISSUE TITLE
.NET core support Linux

### ISSUE THREAD

**Issue by robvanpamel** [nunit/nunit3-vs-adapter#311] opened 2017-03-30 11:24 UTC
Hi, 

Nunit was working fine when making use of the project.json file format. However if we want to switch over to the new csproj file format i can't find out how to use this. 
Or is it possible to use NUnit.Console for this? However I assume that the NetCoreApp framework is not supported.

Is there anybody how could guide me on this ? I already installed the adapter using nuget, but when i run it I get the exception as described below:
 
    dotnet test -a ~/.nuget/packages/nunit3testadapter/3.6.0/tools/

    Starting test execution, please wait...
    An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load file or assembly 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyT
    oken=b77a5c561934e089'. The system cannot find the file specified.

Kind regards
  Rob

**Comment by OsirisTerje** [comment] 2017-03-30 17:55
See discussion at https://github.com/nunit/nunit3-vs-adapter/issues/297  .  The adapter doesn't support .net core projects, and it first requires support for .net core in NUnit itself, work which is in progress.   Copied from @rprouse in #297 "he NUnit Engine does not currently support .NET Core projects and the dotnet-test-nunit adapter doesn't work with the new .NET Core CSPROJ format. Microsoft decided to drop support for the various dotnet-test-* style adapters in favor of the old style visual studio adapters and we are still playing catchup."

**Comment by rprouse** [comment] 2017-03-30 17:57
I am going to close this as a duplicate of #297. Please track it there.

**Closed by rprouse** 2017-03-30 17:57 UTC
