### ISSUE TITLE
Duplicating Tag's in Test Explorer when using Nunit3TestAdapter 3.11.0

### ISSUE THREAD

**Issue by garry-edmonds** [nunit/nunit3-vs-adapter#559] opened 2018-10-31 10:38 UTC
Code version's in use:
- Visual Studio 2015 Enterprise, Version 14.0.25431.01 Update 3
- Nunit - Ver 3.0+
- Nunit3TestAdapter - Ver 3.11.0
- Specflow - Ver 2.2.1
- .Net Framework - Ver 4.5.2

Using Nunit3TestAdapter as an installed extension on Visual Studio 2015.
Create a new Class Project and install Specflow and nunit 3.11 nuget packages.
Create a feature file with the default steps.
Build the solution.

Note the Tag @mytag is shown in the Test Explorer twice.

If you downgrade the Nunit3TestAdapter to version 3.10, then the tags are only shown once in the Test Explorer window,

See screenshot
![nunit311testadapterissue](https://user-images.githubusercontent.com/7498060/47782612-85d30780-dcf8-11e8-832a-e1774dd65fbe.JPG)

**Comment by OsirisTerje** [comment] 2018-10-31 12:37
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".

**Comment by OsirisTerje** [comment] 2018-11-02 22:09
This works in VS 2017
![image](https://user-images.githubusercontent.com/203432/47942866-dcf0fc00-def3-11e8-9baf-cca324db9235.png)

 Frankly I am not sure why you see this in 3.11 with VS2015 and not in 3.10.   There should be no difference there really.  
I'll check this on another machine with VS2015 installed.

**Comment by garry-edmonds** [comment] 2018-11-05 10:00
Hi, I have found that the issue is also in VS2017 but you have to be using the NUnit3TestAdapter as an Extension only.  But I don't have the issue if using the nuget package.  This issue seems to be related to the Extension only and not the nuget package.

Work around is to only use the nuget package in the solution and remove the extension from visual studio completely.

![extensionscreen](https://user-images.githubusercontent.com/7498060/47991252-8a753280-e0e1-11e8-9e14-adeedf88ff7f.jpg)

**Comment by garry-edmonds** [comment] 2018-11-06 15:01
VS2015 also has the issue with the duplicate tag's when just using the nuget package for the test adapter, I've uninstalled the extensions completely from VS2015 now.  

I can confirm that is works perfectly correct in VS2017 though both from the extension and the nuget package.  So this is just a VS2015 issue.

**Comment by OsirisTerje** [comment] 2018-11-06 19:55
I have found a similar issue, duplicate traits, in VS 2017 too, so there is definitively something weird going one.  I have raised the issue with MS too, to get some help looking into where the issue really is.  Do you see this with any test project in VS 2015 ?

**Comment by garry-edmonds** [comment] 2018-11-06 21:05
Yes we have a few Vs2105 projects that the machine of the users had the extension with auto update set to on and when the 3.11.0 extension became available it was noticed have tried a few solutions and all had the same issue so we downgraded the extension back to 3.10 and turned off auto update.   
I am now getting the guys to upgrade to Vs2017 and not using the extension just the nuget package which seems to be working correctly.

**Comment by OsirisTerje** [comment] 2018-11-06 21:09
Thanks for this information!  It's really helpful.  We'll continue trying to track down what is going on here.

**Comment by MattKeenum** [comment] 2018-11-08 17:01
I am having the same issue. Using Professional VS2017 Version 15.8.6, I upgraded to NUnit3TestAdapter v3.11.0 and I had duplicate tests show up in the test explorer. Without changing anything other than downgrading to v3.10.0, I do not have any test duplication.

I do not have any NUnit Extensions installed. I have tried turning off source based discovery to no avail. 
Anything else I can try? For the time being I will stay on v3.10.0

**Comment by OsirisTerje** [comment] 2018-11-08 20:03
@MattKeenum  Do you mean you have both the Extension (vsix) and the nuget adapter installed?   Then the vsix should take preference regardless of version (if that hasnt changed in latest VS).  In the output/test window - do you see the adapter version there?  And does it correspond?

(It's obviously now we have a bug here, so I'll mark it confirmed.)

**Comment by garry-edmonds** [comment] 2018-11-08 20:12
I’ve been trying some stuff on vs2017. Found that specflow seems to add all the traits to the test explorer that is needed. Nunittestadapter 3.11. Ver then adds the tagged traits to the test explorer. But ver 3.10 did not add the tagged traits.  

So seems to also be an issue on vs2017 I don’t know why 3.11 and adding in the traits again for traits already added by specflow. 

There seems to be no options in visual studio to stop specflow adding the traits to the test explorer.

**Comment by MattKeenum** [comment] 2018-11-08 21:58
@OsirisTerje You are correct. When I checked the output/test window, it showed NUnit Test Adapter 3.11.0.0. This did duplicate the tests in the test explorer. They are all the same test; if I highlight one, the duplicated test highlights as well. 

If I disable the extension, the output/test window shows NUnit Adapter 3.10.0.21 and the tests are not duplicated.

**Comment by OsirisTerje** [comment] 2018-11-11 17:56
@MattKeenum  Thanks a lot! This starts to close in.   If you remove the nuget adapter from the solution, and *just* use the extension, do you then see duplicates ?
(Frankly I don't understand why having both in should give duplicates, not why one should be different from the other - since they're the same code, but I have MS in the loop here, it might be something with the way the extension adapter and nuget adapter interact.)

**Comment by MattKeenum** [comment] 2018-11-13 19:52
@OsirisTerje I can confirm that just having the extension installed and removing the nuget adapter from the solution still produces the duplicate tests.

**Comment by OsirisTerje** [comment] 2018-11-18 20:32
I think I have found the reason for this now.  It is PR #507 (for issue #506).  The categories are added twice, once with NUnit category type and once with MSTest category type, and the Test Explorer can't make sense of this.   @rprouse  indicated in his comments he expected this to happen when MS fixed the trx issue,  they have not yet, but we now see this in Test Explorer instead.  So, I cannot see any other way around this than to revert the #507, and raise the issue with MS, or add a PR ourselves to the trx logger.

**Comment by garry-edmonds** [comment] 2018-11-18 21:04
Thanks for the update.

**Comment by OsirisTerje** [comment] 2018-11-19 21:37
I have a fix here , PR #564 .   It fails tests on appveyor build, but not locally.  I'll wait until tomorrow, and then I'll merge.  @garry-edmonds , @MattKeenum You can then test this from the dev feed.

**Comment by OsirisTerje** [comment] 2018-11-20 21:02
@garry-edmonds @MattKeenum  I have merged the PR, so there is new pre-release version in the Myget feed.  Can you verify it works for you both?  If it does, I can release this within a day or two. 

Feed link to package:  https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.11.1-dev-00958

**Closed** 2018-11-20 21:02 UTC
Labels: Investigate, is:bug, pri:critical, pri:high

**Comment by garry-edmonds** [comment] 2018-11-20 21:29
@OsirisTerje - Can confirm is working as expected in VS2015 and VS2017 now, with numerous feature files and tags.  All the traits in test explorer are now unique with the correct test count against each one.  So I'm happy with the fix.  Garry.

**Comment by OsirisTerje** [comment] 2018-11-21 05:09
@garry-edmonds Thanks!  Will release asap

**Comment by OsirisTerje** [comment] 2018-11-21 21:54
@garry-edmonds , @MattKeenum   3.11.1 is released

**Comment by MattKeenum** [comment] 2018-11-27 13:07
Using 3.11.2, everything is working as expected. Thanks. If I notice anything else, I'll be sure to let you know.
