### ISSUE TITLE
Multiple category support missing in VS 2015 Update 2

### ISSUE THREAD

**Issue by scara** [nunit/nunit3-vs-adapter#184] opened 2016-06-06 14:52 UTC
Look at `MockTest2()` or `MockTest3()` or try adding multiple categories e.g.:
```
diff --git a/src/mock-assembly/MockAssembly.cs b/src/mock-assembly/MockAssembly.cs
index 08ecf26..2158245 100644
--- a/src/mock-assembly/MockAssembly.cs
+++ b/src/mock-assembly/MockAssembly.cs
@@ -132,6 +132,8 @@ namespace NUnit.Tests
             }

             [Test, Property("TargetMethod", "SomeClassName"), Property("Size", 5), /*Property("TargetType", typeof( System.Threading.Thread ))*/]
+            [Category("YetAnotherCat")]
+            [Property("YetAnotherProp", 0)]
             public void TestWithManyProperties()
             {}
```
Multiple properties appear as expected in the _Test Explorer_ window while not the multiple categories: only the first category will appear grouping by _Traits_.
The same applies to the NUnit Test Adapter: could it be an issue with the [Update 2](https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx) rather than with the adapter code (not found any mention of it in the net)?

**Comment by rprouse** [comment] 2016-06-06 15:05
It is indeed been confirmed as a bug in VS 2015 update 2, and will be fixed in VS 2015 Update 3.

Closing this as a duplicate of nunit/nunit-vs-adapter#108

**Closed by rprouse** 2016-06-06 15:05 UTC

**Comment by scara** [comment] 2016-06-06 15:29
TNX for the prompt reply, appreciated :thumbsup:.
Apologies for not having found the original issue here :blush:.
