### ISSUE TITLE
Latest TestAdapter locking dll's

### ISSUE THREAD

**Issue by tbertenshaw** [nunit/nunit3-vs-adapter#29] opened 2015-05-18 14:42 UTC
After updating two of my VS2013 environments to use the latest test adapter I get errors when trying to build my solution.  Where MyDLL.dll is the asp.net MVC binary which is referenced by the the test project.

`Error	46	Unable to copy file "obj\Debug\MyDLL.dll" to "bin\MyDLL.dll". The process cannot access the file 'bin\MyDLL.dll' because it is being used by another process.	`

A 3rd environment which i havent updated to the latest V3Testadapter will clean and build successfully. 

All 3 environments have the test explorer window open and docked.

**Comment by OsirisTerje** [comment] 2015-05-18 15:00
We've seen this issue coming and going.  Somehow the vstest.executionengine holds on to the adapter/framework or it doesn't release itself properly.  As a workaround add a desktop shortcut to the command :  TASKKILL /F /FI "IMAGENAME eq vstest.*"   
Using this you kill off the vstest processes, and you can build again.

**Comment by CharliePoole** [comment] 2015-05-18 17:31
@OsirisTerje status:confirm means it needs to be confirmed - i.e. is not confirmed. From your comment, I'm guessing that's not what you mean. :-)

I marked it critical and assigned it to the next milestone.

**Comment by OsirisTerje** [comment] 2015-05-18 17:33
Correct, I meant it  confirmed, since I had the same, and the issue confirmed it.


/Terje

**Comment by BgRva** [comment] 2015-05-19 11:25
Terje, thank you for the shortcut.  The image name of the process locking the dlls on my system was "TE.ProcessHost.Managed.exe", ( the Test Authoring and Execution Framework ), and once I updated he shortcut it worked fine.

**Comment by tbertenshaw** [comment] 2015-05-20 14:17
FYI I've reverted to CTP1 and after numerous builds on 3 different vs2013 environments I've not experienced this locking issue. So from my perspective it's looking like something specifically in CTP2?

**Comment by rprouse** [comment] 2015-05-20 14:23
Thanks, it is specific to CTP2. We are trying to get a fix out as soon as possible. Sorry for the delay.

**Closed** 2015-05-21 21:22 UTC
Labels: is:bug, pri:critical

**Comment by bhupeshdahal** [comment] 2016-03-30 19:05
Hello I upgraded my test suites to nnunit 3.2.0. when i run test using nunit3 console and generate xml in nunit2 format, i am seeing above  mentioned error.   If i try to build as tests are running i get error unable to copy dll. Is this fix in 3.2.0 version ?

**Comment by CharliePoole** [comment] 2016-03-30 19:11
If you are looking at this online on GitHub, look to the right. You'll see that this was included in the NUnit the CTP-3 release of the adapter, some time back.

However, I see you are writing about a problem using the NUnit 3.2 console runner, not the test adapter, so you can't really be seeing "this" error. :-)

Take a look through actual issues on the nunit project at https://github.com/nunit/nunit and see if there are any that match what you are observing. If not, please create one.

**Comment by exhau** [comment] 2016-07-27 19:26
I am using nunit3.4 and vs-adapter3.4 on VS2015. The same problem is still there.
DLLs are either locked by vstest.executionengine or vstest.discoverengine.
