### ISSUE TITLE
"Source: no source available" for tests in abstract base class

### ISSUE THREAD

**Issue by drmannion** [nunit/nunit3-vs-adapter#133] opened 2016-03-16 21:02 UTC
Test methods defined on an abstract base class are properly included under the derived class in Test Explorer and run as expected. However, you can not open the test method source code for the base class methods from Test Explorer by double clicking or by pressing F12. Test Explorer shows the following message: "Source: no source 
![untitled picture](https://cloud.githubusercontent.com/assets/12001392/13828622/b30872de-eb7f-11e5-9caa-619d1fc663ab.png)
available"

**Comment by Green-Bug** [comment] 2016-03-17 08:56
I was about to file this same issue and I already have a fix for it. It requires a change in the engine as well.

I'm now working on adding tests for the change, I expect to have them in the next few days.

**Comment by CharliePoole** [comment] 2016-03-20 19:17
Appears to require an NUnit bug fix. Once we get the fix this just needs to be verified and closed.

**Comment by CharliePoole** [comment] 2016-05-31 20:21
Closing this as a duplicate of #163. Normally, we would close the later one and keep this open but there is already a PR refering to #163. Thanks goes to the originators of both issues.

**Closed** 2016-06-01 03:27 UTC
Labels: closed:duplicate, is:bug, pri:high
