### ISSUE TITLE
[VSTest Runner] TrxLogger report shows wrong "Started on" value for the TestRun if first test is skipped

### ISSUE THREAD

**Issue by harshjain2** [nunit/nunit3-vs-adapter#275] opened 2016-11-28 10:42 UTC
While executing NUnit test cases through vstest.console.exe, the .trx file generated shows wrong "Started on" value if first test is skipped. 

## Repro Steps 
1. Create a Test Project in Visual Studio and add NUnit and NUnit3TestAdapter nuget packages.
2. Remove MSTest Adapter reference and delete UnitTest1.cs
3. Add two NUnit tests. Add [Ignore] tag on first test.
4. Execute the tests using vstest.console.exe and specify /logger:trx switch. 
5. Open the .trx file generated in Visual Studio. 
6. Observe the "Started On" value.
## Expected Behaviour
Trx file should show correct "Started on" value.

## Actual Behaviour
Trx file is showing Started On date as 1/1/0001 5:30 AM.
![image](https://cloud.githubusercontent.com/assets/13763032/20665071/19d0ca60-b584-11e6-8c51-081a29544fb3.png)

This behaviour is observed only in case of NUnit, MSTest and XUnit tests behave as expected for this scenario.

## Environment Info
1. NUnit : 3.5.0
2. NUnit3TestAdapter : 3.6.0

**Comment by rprouse** [comment] 2016-11-28 23:53
What version of Visual Studio are you using? I am using VS 2015 update 3 and see very different UI when I follow your repro steps. 

In the NUnit Test results file produced by NUnit itself, the start date for ignored tests is included correctly.

```xml
          <test-case id="0-1001" name="ShouldCatchAsyncExceptions" fullname="nunit.v3.AsyncTests.ShouldCatchAsyncExceptions" methodname="ShouldCatchAsyncExceptions" classname="nunit.v3.AsyncTests" runstate="Ignored" seed="918658402" result="Skipped" label="Ignored" start-time="2016-11-28 23:38:56Z" end-time="2016-11-28 23:38:56Z" duration="0.001844" asserts="0">
            <properties>
              <property name="_SKIPREASON" value="Issue #1190" />
            </properties>
            <reason>
              <message><![CDATA[Issue #1190]]></message>
            </reason>
          </test-case>
```

Running that same test suite, the TRX file also has the correct data,

```xml
    <UnitTestResult executionId="8a3673df-d2e0-4973-8454-86a92f2a5253" testId="27b1a1b7-0162-491c-b633-544e3f0c10f9" testName="ShouldCatchAsyncExceptions" computerName="XPS-15" duration="00:00:00.0010000" startTime="2016-11-28T18:42:18.0000000-05:00" endTime="2016-11-28T18:42:18.0000000-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="NotExecuted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="8a3673df-d2e0-4973-8454-86a92f2a5253">
      <Output>
        <ErrorInfo>
          <Message>Issue #1190</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
```

And the start/end times are correct in the Visual Studio UI

![image](https://cloud.githubusercontent.com/assets/493828/20690941/999d78c6-b59b-11e6-92c6-b8e809d27546.png)

I would also add that as far as I know, we are not responsible for translating the NUnit test results to the Visual Studio format, that is handled by VSTest. 

I am going to close this as no-repro, but will reopen if you can help us determine it is an NUnit bug and not a VSTest bug.

**Comment by harshjain2** [comment] 2016-11-29 05:44
@rprouse I used Visual Studio 2015 Update 3 as well. I am getting the same behaviour.

![image](https://cloud.githubusercontent.com/assets/13763032/20697861/b4c07126-b622-11e6-9a54-1d1f948c5b89.png)

I've uploaded a repro project [here](https://github.com/harshjain2/samples/tree/master/NUnitBugRepro/UnitTestProject31) and trx [here](https://github.com/harshjain2/samples/blob/master/NUnitBugRepro/UnitTestProject31/ReproBug.trx)

**Comment by rprouse** [comment] 2016-11-29 14:42
I have reopened with a confirm label. The difference looks to be related to the OneTimeSetup. I put confirm on this to determine if it is an NUnit bug or a VSTest bug.

**Comment by harshjain2** [comment] 2016-12-01 06:09
@rprouse Are you able to repro the issue using the solution I shared? 
Any thoughts on the steps to determine if it is an NUnit but or VSTest bug?

**Comment by iamthegD** [comment] 2017-06-29 15:11
Hi,

this is breaking all our nunit tests publish in prod (june 2017). 

Any update on this ? Should I look in VsTest for fix ?

Thanks

**Comment by OsirisTerje** [comment] 2017-06-30 00:24
This looks to me to be a nunit bug.  I singlestepped through the eventhandler , and for the first ignored test I got these results:
![image](https://user-images.githubusercontent.com/203432/27715845-5b63ec1a-5d3a-11e7-8ce3-fd6f3aefc0b8.png)
The test converter in the adapter looks for the attributes start-time and end-time, and I assume it doesn't find any. 
Further, I dont understand why it comes out with OneTimeSetup. There is also only start-suite events (multiple), and then comes a test-case event (test finished).  The non-ignored test also has a start-test.  This makes sense from nunit since the test is not executing, but VS then gets a  RecordEnd message before any RecordStart events.   I am not really sure what VS expects in these cases. We need to look up that too, but anyway, the test-case data is wrong wrt to the time in the first testfinished case.

**Comment by CharliePoole** [comment] 2017-06-30 03:30
This is the sequence we have been using for ignored tests for a long time: RecordEnd followed by RecordResult. It was arrived at empirically back when we had no info about what VS expected. I tried a result without an end and that was not working.

Since NUnit never runs the test, there is no start or end time to provide and the duration is zero, which VS has always interpreted as Not Run.

**Comment by OsirisTerje** [comment] 2017-06-30 08:47
I had a look in the MSTest adapter source.  It seems they are setting the times to DateTimeOffset.Now  .  We could do the same when we don't have any time information  from nunit. It would still keep the duration at zero, so shouldn't change anything else.

**Comment by OsirisTerje** [comment] 2017-06-30 16:45
@harshjain2 @iamthegD @  See enclosed trx file, I assume this is the way it should be.  Will push up a PR for this now. 
[Terje_TERJE2014 2017-06-30 18_37_25.txt](https://github.com/nunit/nunit3-vs-adapter/files/1115927/Terje_TERJE2014.2017-06-30.18_37_25.txt)

(just rename extension to trx)

**Comment by OsirisTerje** [comment] 2017-07-01 00:28
Right now I am not able to repro this any longer.  I am saying any longer, because I am pretty sure I had a repro earlier today.  I have now gone back to the original repro, and I get correct trx values.  I have also tried different nunit/adapter combinations, and all seems to work as they should.    Based on this, I'll readd the confirm label.  Can you provide another repro @iamthegD which show this, or check the above repro from @harshjain2 on your system?

**Comment by OsirisTerje** [comment] 2017-07-01 09:06
Doesnt repro, so closing until someone can come up with a repro that show this is still an issue

**Closed** 2017-07-01 09:06 UTC
Labels: closed:norepro, confirm, is:bug

**Comment by IrmantasVaracinskas** [comment] 2018-08-03 08:12
Had similar issue. For some reason what worked was to change machine's Time zone to UTC or UTC + anything.
In short this problem is only reproduced for me when Time zone is UTC -

If my explanation is not clear enough please let me know.
