### ISSUE TITLE
Nunit test runner picking up ignored tests (ish) in tfs

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#241] opened 2016-10-19 17:11 UTC
@dgee2 commented on [Wed Oct 19 2016](https://github.com/nunit/nunit/issues/1853)

Hi,

I'm running tests in TFS using the NUnit3TestAdapter nuget package. We have a test fixture that is completely ignored at the class level. We are getting error messages in the output saying: `The specified test case was not found in the current result context (mapping test id to test node).` I can't find any information in the documentation to say that this is not supported and it indeed has been in previous versions of NUnit but I can't explain why this error would happen after the upgrade to the new runner.

It should be noted that I don't see this error when running the tests within either Visual Studio, NCrunch or Resharper.

This seems to be similar but different to the following issue: #427

If anyone can shed any light on this, I would greatly appreciate it.

---

@CharliePoole commented on [Wed Oct 19 2016](https://github.com/nunit/nunit/issues/1853#issuecomment-254878401)

Please try to select the right project when reporting errors. That way the right people are looking at it. Since you identified this as an adapter issue, I'm moving it there.

**Comment by dgee2** [comment] 2016-10-20 00:40
Thanks, wasn't sure whether to consider this as nunit core because of it being related to the Ignore attribute or something for this repository.

In case someone else finds this, the current workaround that we're using is to ignore each test individually. Regardless of there being a relatively simple workaround, this feels like it is a bug.

Thanks

**Comment by pablonautic** [comment] 2017-07-19 14:48
I can confirm we have the same problem here - TFS VS Test Runner + NUnit adapter runs all tests, including [Ignore]d and [Explicit].

**Comment by jnm2** [comment] 2017-07-19 16:54
Duplicate of https://github.com/nunit/nunit3-vs-adapter/issues/47?

**Comment by CharliePoole** [comment] 2017-07-19 18:15
@pablonautic Are you confirming this as applied to test __classes__ marked with `IgnoreAttribute` or `ExplicitAttribute`

@jnm2 Issue #47 refers to use of TFS test filters, which are not mentioned here. Also, the problem in #47 is very well understood and documented while this one is not.

**Comment by jnm2** [comment] 2017-07-19 18:44
Okay. Looks like I'll have to be more careful saying the keyword "duplicate". https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates

**Comment by CharliePoole** [comment] 2017-07-19 18:48
Ah a feature you are using without necessarily deciding to use it!

**Comment by jnm2** [comment] 2017-07-19 18:51
Yep, and there's no undo. 😒

**Comment by jnm2** [comment] 2017-07-19 18:52
Almost always the appropriate thing is to proceed without asking but provide robust undo.

**Comment by CharliePoole** [comment] 2017-07-19 18:57
What if you edit or remove the comment?

At Microsoft, we used to worry about discoverability of features. GitHub has solved that one!

**Comment by jnm2** [comment] 2017-07-19 19:16
Already tried edit, just deleted. No effect.
Haha!

**Comment by pablonautic** [comment] 2017-07-20 07:55
@CharliePoole 
That's exactly what happens, so we are using test categories together with a custom filter to disable the required tests. The case is true for classes and (I think) for single methods as well.

**Comment by CharliePoole** [comment] 2017-07-20 08:11
@pablonautic We have several issues with similar symptoms but probably diverse causes. This one, related to the attribute being on the class, is entirely new so I'm digging into it as part of triage in order to get it ready to be worked on.

**Comment by CharliePoole** [comment] 2017-07-20 08:44
@dgee2 You didn't indicate if a filter was in use, which is what #47 is about. However, since you only see the problem when the attribute is on the class, I am thinking it's a new issue. I'd still like somebody to confirm it, however.

**Comment by OsirisTerje** [comment] 2017-07-20 19:42
I've set up a test to check this, and can't confirm.   I have a class with the ignore attribute, and VSTS build def for it, and it the tests in that class are ignored. 

I do however,  see output messages as Error messages in the log, corresponding with the same for cmd line vstest run. 

`Skipped  ClassWhichIsIgnored_Test1
2017-07-20T19:22:50.7757161Z Error Message:
2017-07-20T19:22:50.7757161Z    OneTimeSetUp: the whole class
2017-07-20T19:22:50.7757161Z 
2017-07-20T19:22:50.7757161Z Skipped  ClassWhichIsIgnored_Test2
2017-07-20T19:22:50.7757161Z 
2017-07-20T19:22:50.7757161Z Error Message:
2017-07-20T19:22:50.7757161Z    OneTimeSetUp: the whole class`

The test class looks like:

`[Ignore("the whole class")]
    [TestFixture]
    public class ClassWhichIsIgnored
    {
        [Test]
        public void ClassWhichIsIgnored_Test1()
        {
            Assert.Pass();
        }

        [Test]
        public void ClassWhichIsIgnored_Test2()
        {
            Assert.Pass();
        }
    `}``


@pablonautic Can you give some more information, or preferably a repro - it should be the same result with vstest.console as with TFS/VSTS, so also copy the cmd line parameters you're using.

**Comment by dgee2** [comment] 2017-07-24 16:44
@CharliePoole I don't remember needing to use filters. I think my expectation was that I could put an ignore attribute on a whole class and that they would be ignored. If I'm honest though, until 5 days ago I'd forgotten about this issue. I think we just accepted the workaround that was found and moved on.

**Comment by CharliePoole** [comment] 2017-07-24 17:07
@dgee2 That expectation is correct. We know that NUnit normally does that and are assuming that the problem arises in the adapter due to some mistake in the adaptation itself. Still looking for somebody to confirm this. @nunit/core-team ?

**Comment by jnm2** [comment] 2017-07-24 17:14
@OsirisTerje tried what was described and couldn't confirm and asked for a repro.

**Comment by mikkelbu** [comment] 2019-07-18 20:47
@jnm2 https://github.com/nunit/nunit3-vs-adapter/issues/241#issuecomment-316482026 Now there is an undo button :)

**Comment by jnm2** [comment] 2019-07-19 03:25
Sweet, thanks for pointing it out! Found it!

https://help.github.com/en/articles/about-duplicate-issues-and-pull-requests#unmarking-duplicates

**Closed** 2019-08-20 12:58 UTC
Labels: closed:norepro, confirm

**Comment by slombardo** [comment] 2022-06-29 18:28
I can definitely confirm that this is still happening with `nunit3-console`

**Comment by CharliePoole** [comment] 2022-06-29 18:46
@slombardo This is of course the NUnit3 adapter project and the issue is against the adapter.If that was not a typo and there is an actual issue i missed in the console runner, kindly point it out or file a new issue there. :-)
