### ISSUE TITLE
NUnit3Adapter support for .NET core

### ISSUE THREAD

**Issue by sbaid** [nunit/nunit3-vs-adapter#242] opened 2016-10-20 03:25 UTC
.NET core tooling is moving to common .csproj based projects. That includes IDE support and dotnet/cli support. As part of that change - test tooling is enabling support .NET core unit testing by moving Test Platform (vstest runner & engine) to .NET core and powering dotnet test CLI.

To enable support for NUnit3 - It will be excellent to have .NET core support in the Nunit3 VS adapter.

**Comment by rprouse** [comment] 2016-10-20 20:18
Does this mean that once projects are migrated from `xproj` to `csproj`, then the various `dotnet test` adapters will stop working in Visual Studio?

**Comment by sbaid** [comment] 2016-10-21 14:20
They continue to work on dev14 with dotnet tools preview2 release. In dev15 preview/RC releases - they will not work.

**Comment by rprouse** [comment] 2016-10-21 17:08
@sbaid, @CharliePoole brings up a good point. Will our `dotnet-test-nunit` adapter still be needed or work on the command line once you migrate to the `csproj` format, or is the `dotnet test` command also being dropped from the CLI tooling? I would like to know now so that we can stop work on it if it isn't going to be needed.

**Comment by sbaid** [comment] 2016-10-24 13:16
dotnet test3 is being build side by side and that will be renamed eventually - to replace dotnet test when the migration to csproj is complete. dotnet test3 CLI flow is using the visual studio adapter. This way dotnet CLI & IDE both will use the same adapter.

**Comment by rprouse** [comment] 2016-10-24 18:45
@sbaid thanks, that is good to know if not a bit annoying considering the pressure to create the `dotnet test` version (from Microsoft) and the amount of work that went into it only to be dropped less than a year later.

**Comment by rprouse** [comment] 2017-02-02 11:38
I am closing this as a duplicate of #297

**Closed by rprouse** 2017-02-02 11:38 UTC
