### ISSUE TITLE
Moving on

### ISSUE THREAD

**Issue by leaderanalytics** [nunit/nunit3-vs-adapter#308] opened 2017-03-10 14:50 UTC
Rather than write another "why are my tests not being found" post I just decided to move to xunit.  I was up and running in five mins.  I hope you guys get the issues worked out because I like NUnit so much more.

**Comment by rprouse** [comment] 2017-03-10 15:32
Thanks for letting us know. Are you targeting .NET Core?

**Comment by leaderanalytics** [comment] 2017-03-10 19:30
Yes

Sent from my Windows Phone
________________________________

**Comment by daniel-meismer-zocdoc** [comment] 2017-03-13 19:47
@rprouse is there anything we (the community) can do to help get the issues worked out?

**Comment by daniel-meismer-zocdoc** [comment] 2017-03-13 19:47
FWIW, my team is staying on NUnit on dotnet core/ubuntu, though in the meantime that means we have to use vs2015 & an old sdk version (`1.0.0-preview2-1-003177`). It's not too big of a dealbreaker.

**Comment by rprouse** [comment] 2017-03-14 00:27
@daniel-meismer-zocdoc getting .NET Core working is my main focus now, so the biggest help would be to help triage issues and help users here on GitHub to give the team more time to work on code 😉

**Comment by rprouse** [comment] 2017-03-26 12:44
Closing this as a duplicate of #297. I am tracking the work in that issue.

**Closed by rprouse** 2017-03-26 12:44 UTC
