### ISSUE TITLE
Fatal error debugging tests via Test-Explorer

### ISSUE THREAD

**Issue by bunnu** [nunit/nunit3-vs-adapter#320] opened 2017-05-04 08:50 UTC
Thanks for your work getting nunit3-vs-adapter running with .net core. Running tests via dotnet test or Test-Explorer in VS seems to work fine.

When i try to debug a test via Test-Explorer a Message-Box with following Message appears:

> A fatal error has occurred and debugging needs to be terminated.  For more details, please see the Microsoft Help and Support web site. HRESULT=0x8000ffff. ErrorCode=0x0

![debug_error](https://cloud.githubusercontent.com/assets/5147219/25696006/be6839d0-30b5-11e7-958e-f5aa0661b279.png)

I'm using VS 2017 V15.1 (26403.79) and referencing following packages:

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="Moq" Version="4.7.9" />
<PackageReference Include="NUnit" Version="3.6.1" />
<PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
```

**Comment by MikeBeaton** [comment] 2017-05-05 11:10
(FWIW I can debug individual tests with 3.8-alpha in my setup, so this problem is not universal. I don't know if it is relevant, but I am not using Moq, and I have VS Professional 2017 15.0.0+26228.9.)

**Comment by rprouse** [comment] 2017-05-05 12:26
Debugging is one of the main tests before releasing, so it is definately not universal. 

- Can you post your entire CSPROJ file here to see? 
- Do you have a minimum reproducible example that I can debug?
- Does debug all work? 
- Can you try downloading https://github.com/rprouse/NUnitPlatformTests and see debugging in that solution works?

We need to identify what is different about your project or setup so that we can fix this 👍

**Comment by bunnu** [comment] 2017-05-05 13:00
Hi Rob,

I'm little bit confused: The solution, which was generating the mentioned fatal error yesterday, is working today. I'm quite sure I didn't change anything (code, extensions, packages, etc.). My co-worker had the same issue yesterday. Today it is working too?!  I'm also able to debug all your tests in the NUnitPlatformTests-Solution.

Currently I'm not able to repruduce the error.

**Comment by rprouse** [comment] 2017-05-05 13:19
@bunnu don't you love working with .NET Core? Thanks for letting me know. I am going to keep this issue open for a bit so others can confirm if it is an issue or not. Maybe it just required a restart of Visual Studio? I do 

@Gerfaut can you let us know if it is working for you yet? If not, can you answer any of my questions that I posted above?

**Comment by bunnu** [comment] 2017-05-05 13:30
My first try yesterday was restarting Visual Studio, but it didn't solved the problem.  Maybe the antivirus caused the issue? I'm using Kaspersky Endpoint Security 10. @Gerfaut which AV are you using?

**Comment by Gerfaut** [comment] 2017-05-05 15:32
Hi @rprouse, 

I have the exact same behavior than @bunnu, my previous try is now working... but I succeed to recreate the problem. 
Here are the step to do it: 
- Inside a folder, `dotnet new sln`
- Open the sln with Visual Studio 2017
- From Visual Studio, create a new Class Lib project. 
- Edit the .csproj to add the dependencies (so I am not using Nuget). The csproj is then the following:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
  </ItemGroup>

</Project>
```

- When I build the solution, those lines are added in the csproj:
```
<ItemGroup> 
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" /> 
  </ItemGroup> 
```
- I try to launch one dummy test and it crashes with the error above. 
- When I close and relaunch Visual Studio, I can debug the test without error. The only file that changed is the Test.NETCoreNunit\ClassLibrary1\bin\Debug\netcoreapp1.1\nunit_random_seed.tmp which was "1972429476" and now contains "971211234" (tracked with GIT). 

My AV is BitDefender Endpoint Security Tools but I don't think there is a issue with this :) 

Does it help a bit ? 
Do you need the full project (which should work then) ? 

Thanks!

**Comment by rprouse** [comment] 2017-05-05 16:43
@Gerfaut thanks for the detailed report. My guess is that it is a Visual Studio or .NET Core tooling bug, but I am going to leave this open to confirm. Personally, Visual Studio 2017 is very buggy working with .NET Core. It often crashes or exhibits weird behaviour whenever I edit the CSPROJ files, so it could be related.

For your other comments, the **Service** tag is added to all test project by Visual Studio. It is intended to speed up test discovery. The **nunit_random_seed.tmp** file allows for repeatable test runs when using NUnit's random features. It can be ignored.

**Comment by Gerfaut** [comment] 2017-05-06 06:19
Hi @rprouse, 
Thanks for explanation! If I succeed to find more information, I'll complete it here. 
Anyway, you should be right about the VS2017 / .NET Core Tooling bug. 
Let's see! 

Thanks a lot!!

**Comment by NightOwl888** [comment] 2017-05-07 12:42
I had the same problem. Here is my project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestNUnit\TestNUnit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

It kept producing the same error message as above as many times as I ran it. Then I read some of the posts here that said "overnight it stopped happening". I decided to close Visual Studio 2017 and reopen it and then it started working. So, it looks like this probably isn't a problem with the test adapter, but a caching issue of some sort in Visual Studio.

**Comment by rprouse** [comment] 2017-05-07 19:16
@NightOwl888 thanks for the update. It is definately looking like a Visual Studio issue, but I am going to leave this issue open for a bit so others can find it easily.

**Comment by ircnelson** [comment] 2017-05-23 13:29
I have the same problem with xUnit and solved this problem changing project type from **Library** to **Console Application**:

```xml
<PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netcoreapp1.1|AnyCPU'">
  <OutputType>exe</OutputType>
</PropertyGroup>

<PropertyGroup>
  <TargetFrameworks>netcoreapp1.1;net461</TargetFrameworks>
  <AssemblyName>MyProject.UnitTests</AssemblyName>
  <ApplicationIcon />
  <OutputTypeEx>exe</OutputTypeEx>
  <StartupObject />
</PropertyGroup>
```

My final csproj: https://gist.github.com/ircnelson/9cbddb681d520d7f581dbfc99709a9e1

**Comment by giggio** [comment] 2017-06-06 22:04
I can confirm that changing from Library to Console App solves the problem.

**Comment by OsirisTerje** [comment] 2017-06-25 18:21
Following @Gerfaut 's recipe (Thanks, that was to the point!!!) , and updating to NUnit 3.7.1, and adapter 3.8.0-alpha1  I can confirm it still fails. 



![image](https://user-images.githubusercontent.com/203432/27518569-65ae8d24-59e3-11e7-95e8-71512332ea81.png)

I am pretty sure this is VS, so I'll contact them about it.  It might be related to the adapter, that we're not acting the way we should (but don't know yet - A little bit of Kafka here), so I'll keep it open.  

PS:
Thanks also to @giggio , @ircnelson , @MikeBeaton , @NightOwl888 and @bunnu for the feedback, it really helps when more can confirm and elaborate on the issues!

**Comment by grokky1** [comment] 2017-07-12 05:30
I have the same problem ("dotnet has stopped working") crash when running or debugging tests. I thought to try something else, which was to delete then restore the nuget package cache. Unfortunately, that didn't work.

**Comment by Delpak** [comment] 2017-10-25 19:25
I had exactly the same problem. But after lean and rebuild the solution, the problem was solved.

**Comment by zhenyu-siama** [comment] 2017-10-29 23:20
I had extactly the same issue. Not with NUnit, but XUnit.

It was all good last Friday (2017-10-27). This morning, it crashes whenever I start a debug from test explorer. I could not fix it by restarting Visual Studio or restarting windows.

I did the rebuild as suggested by Delpak, it worked. The error is gone. So try clean & rebuild. Good luck!

**Comment by OsirisTerje** [comment] 2017-10-30 08:28
@navin22 says this is probably related to https://github.com/Microsoft/vstest/issues/558

**Comment by joost-morsink** [comment] 2017-12-05 09:57
For me, removing the <ItemGroup><Service Include="{GUID}"... solved the problem, at least temporarily.

**Comment by k-s-s** [comment] 2018-03-09 19:35
Had this issue with latest VS 15.6.1
Solved with setting test projecct (Class Library) startup object to NUnit.Program, run a test (fails), then revert the setting back to Not Set

**Comment by jnm2** [comment] 2018-03-20 01:10
@k-s-s Is your issue the one [fixed in 15.6.3](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.6.3)?

https://developercommunity.visualstudio.com/content/problem/209020/last-update-studion-2017-cannot-run-nunit-tests.html

**Comment by TheCodechimp** [comment] 2018-04-12 20:15
I apologize if someone already mentioned this, but I encountered this error while trying to debug some Azure functions. You can run into this error if you specify a .NET framework version but have the function API specified to V2

**Comment by shargon** [comment] 2018-04-17 16:06
I have the same issue :(

**Comment by prudhviraj299** [comment] 2018-08-09 15:05
Cleaning Project resolved my issue. 
If this doesn't work restart VS and then clean project before debugging.

**Comment by OsirisTerje** [comment] 2018-08-09 16:36
Close this for now, as there is nothing we can do.  Feel free to add links to work-arounds.

**Closed by OsirisTerje** 2018-08-09 16:36 UTC
Labels: External, VS Issue, closed:SomebodyElsesProblem, is:bug

**Comment by aleha84** [comment] 2018-09-17 11:56
VS 2017 Pro. Version: 15.8.4 Still reproducing. Using NUnit 3.10.1. 
Used solution from [here](https://stackoverflow.com/a/42913421/1235390)

> In my case with Visual Studio 2017 release version the unit test project failed with this error because for some reason the unit test project had a launchsettings.json file under the project "properties" folder. Deleting it resolved the debugging issue.

**Comment by VictorioBerra** [comment] 2019-01-24 16:48
I am encountering this still.

![image](https://user-images.githubusercontent.com/2934507/51693838-4e0cf080-1fc5-11e9-8595-8eaa7d8bf1cd.png)

> A fatal error has occurred and debugging needs to be terminated. For more details, please see the Microsoft Help and Support web site. HRESULT=0x8000ffff. ErrorCode=0x0.

### `dotnet --info`

```
PS C:\Users\victorioberra> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### VisualStudio Info

(Enterprise 2017) 15.9.4

![image](https://user-images.githubusercontent.com/2934507/51693695-14d48080-1fc5-11e9-9874-4b6df8a0a24c.png)


## Project File Info

```csharp
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <!-- Optional performance setting - enables tiered JIT compilation-->
    <TieredCompilation>true</TieredCompilation>
    <IsPackable>false</IsPackable>
    <RootNamespace>My.API.IntegrationTests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.6.0" />
    <PackageReference Include="FluentAssertions" Version="5.5.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />    
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.2.0" />    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
    <PackageReference Include="RestEase" Version="1.4.7" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\My.API\My.API.csproj" />
  </ItemGroup>

</Project>

```

This issue has survived multiple system reboots, and bin/obj folder deletions. I am not sure how to solve this.

**Comment by VictorioBerra** [comment] 2019-01-24 16:50
@aleha84  Thank you!

My issues was my test projects had a launchsettings!

This is because before the fixes in 2.2 we were told for our tests, we need to target the `.Web` SDK. So as I converted everything over back to the normal SDK those files remained.

**Comment by freerider7777** [comment] 2019-02-21 15:51
I had this issue with VS 2017, Nunit3
My test project had in Build -> Platform target x64. I switched to Any CPU and everything is ok :)

**Comment by adamsproul** [comment] 2019-02-21 20:05
Removing the IIS Express profile from the launchsettings.json fixed this issue for me.

![image](https://user-images.githubusercontent.com/2125354/53198299-11471000-35ea-11e9-8e53-2c370863eda6.png)
