### ISSUE TITLE
Tests with TestCase attribute appear twice in test adapter.

### ISSUE THREAD

**Issue by AndreyNNN** [nunit/nunit3-vs-adapter#520] opened 2018-06-19 11:44 UTC
Tests with TestCase attribute appear twice in test adapter. Ones as "Not Run Tests" and then as "Passed Tests"

NUnit 3.8.1, NUnit3TestAdapter 3.10.0 
Visual Studio Community 2017 - 15.7.2
 What .net platform and version is being targeted = .Net 2.0

```
 [TestFixture]
    public class TestDefects
    {
        [Test]
        public void SimpleTest()
        {
            Console.WriteLine("SimpleTest");
        }

        [TestCase(1, 2, 3)]
        [TestCase(3, 2, 1)]
        [TestCase(2, 3, 1)]
        public void TestCaseTest(int a, int b, int c)
        {
            Console.WriteLine("TestCaseTest = " + a + b + c);
        }
}
```
![testcase](https://user-images.githubusercontent.com/34504942/41595379-3e85edbc-73cf-11e8-8a15-db67b484cf9d.png)

**Comment by OsirisTerje** [comment] 2018-06-19 20:22
I can't repro this, what I get is:
![image](https://user-images.githubusercontent.com/203432/41622104-de8c55be-740e-11e8-9b5c-0d16c1649c0f.png)

I have also tried different frameworks, beside .net 2 as you state, and same behavior.  
I am using the newest version of NUnit though, but I cant see why that should cause this.  You may check with the earlier version.
Otherwise, there is something else going on in your project, like a runsettings file with name overrides ?
Do you see this on other projects ?

**Comment by AndreyNNN** [comment] 2018-06-20 06:06
Thank you for your help. Please try to set the "Output Type" to "Class Library". And then rebuild app.
![classlib](https://user-images.githubusercontent.com/34504942/41640118-43bb2442-7469-11e8-9df6-d71871ba92d1.png)

**Comment by AndreyNNN** [comment] 2018-06-20 07:40
Thank you for your help.
Please try to set “Target Framework” 
[NetFrameworkConsoleApp.zip](https://github.com/nunit/nunit3-vs-adapter/files/2118315/NetFrameworkConsoleApp.zip)
to “.NET 3.5”
Then try to play with the "Output Type" – change to "Class Library" rebuild and Run all. And then change and rebuild app again.

I cannot find out the reason of this problem because it is randomly reproducible.
I do not use runsettings file. It is simple test app. Please see the attachment.

**Comment by OsirisTerje** [comment] 2018-06-24 18:37
With 15.7.4 and your solution I still can't see the error - but there is one thing, I had to add the NUnit3TestAdapter package to the solution.  Are you using the VSIX adapter version?

And yes, I tried to change output type back and forth too.  

![image](https://user-images.githubusercontent.com/203432/41822278-9eef4582-77ed-11e8-8ff3-f0dcefc593ae.png)

![image](https://user-images.githubusercontent.com/203432/41822283-a8eef51e-77ed-11e8-93e7-425fe1381a05.png)

You can also try to turn off source based discovery too, there might be something there.

![image](https://user-images.githubusercontent.com/203432/41822345-613c78d0-77ee-11e8-9526-2fc85027c43a.png)

**Comment by AndreyNNN** [comment] 2018-06-25 12:31
Thank you. The workaround with turning off "Discover tests in real time from source files" works!

Yes, I'm using VSIX adapter version, but the problem is reproducible with NUnit3TestAdapter package.

**Comment by OsirisTerje** [comment] 2018-06-25 16:08
Good to hear!

When you say it repro'd with the adapterpackage, did you uninstall the vsix when you tried the package?

Because if the vsix stays installed, it takes precedence over the nuget package.

**Comment by AndreyNNN** [comment] 2018-06-26 07:02
Yes, The VSIX version of adapter was uninstalled before test.

**Comment by OsirisTerje** [comment] 2018-10-30 00:34
I am not able to reproduce this.  Using VS 15.8 and latest NUnit and adapter, it works also with source based discovery enabled.  Closing this for now.

**Closed by OsirisTerje** 2018-10-30 00:34 UTC
Labels: confirm
