### ISSUE TITLE
Confusion with data driven tests in VS2015 test manager when using dynamic test data.

### ISSUE THREAD

**Issue by PiotrNestor** [nunit/nunit3-vs-adapter#255] opened 2016-11-01 15:31 UTC
VS2015 test manager cannot handle data driven tests with dynamic test data.
Consider the following example where the test data is in a file

```
using System;
using System.Collections;
using NUnit.Framework;
using FluentAssertions;
using System.IO;
using System.Reflection;

namespace FunctionTest
{
    [TestFixture]
    public class SimpleDD
    {
        [TestCaseSource(typeof(TestData))]
        public void DataDrivenTest2(int number, string name)
        {
            number.Should().BeGreaterThan(0);
            name.Should().NotBeEmpty();
        }
    }

    public class TestData : IEnumerable
    {
        public IEnumerator GetEnumerator()
        {
            var lines = File.ReadLines($@"{Path.Combine(AssemblyDir(), "data.txt")}");
            foreach (var line in lines)
            {
                var number = int.Parse(line.Substring(0, line.IndexOf(",")));
                var name = line.Substring(line.IndexOf(",") + 1);
                yield return new TestCaseData(number, name)
                    .SetName($"TS_{number}_{name}");
            }
        }

        private string AssemblyDir()
        {
            var assembly = Assembly.GetExecutingAssembly();
            var codebase = new Uri(assembly.CodeBase);
            var path = codebase.LocalPath;
            return Directory.GetParent(path).ToString();
        }
    }
}
```

Test data file 'data.txt' - place it in the bin/Debug, or where the test dll resides
```
1,abc_1
2,abc_2
3,abc_3
4,abc_4
```

Compile the example with the above test data. The VS test manager shows 4 tests at compile time.

Now change/update the test data and add some more test data
```
1,abc_1
2,abc_2
3,abc_3
4,abc_4
5,abc_5
6,abc_6
```

Run again (right-click in the test class and Run) and now the Nunit runner says that 6 tests are found but VS test manager still shows the 4 initial tests
```
------ Run test started ------
NUnit Adapter 3.4.1.0: Test execution started
Running selected tests in C:\Users\piones\work\Programs\SlidingDoor\FunctionTest\bin\Debug\FunctionTest.dll
NUnit3TestExecutor converted 6 of 6 NUnit test cases
NUnit Adapter 3.4.1.0: Test execution complete
========== Run test finished: 4 run (0:00:02,184) ==========
```

Note that the Resharper test manager handles this correctly.
Time to implement NUnit specific test manger for VS and forget the built-in one

**Comment by CharliePoole** [comment] 2016-11-01 16:32
The NUnit3TestExecutor ran six tests. Visual studio ignored two of them because they were not found in discovery. The problem is that you are only changing a data file and not the test code, therefore no new compile is triggered. If you make the data change and then force a rebuild, all six will be discovered.

I entirely agree that a custom VS extension for running NUnit tests would be a big gain because the architecture of the Test Explorer is based on assumptions about how test runners work that come pretty much entirely from the MsTest runner. However, this piece of software is merely an __adapter__ and it can't force the TestExplorer to work differently than it does.

I'm closing this as not a bug but please continue to comment if you have further comments or questions.

**Closed by CharliePoole** 2016-11-01 16:32 UTC

**Comment by CharliePoole** [comment] 2016-11-01 16:36
I just noticed a further point. The messages indicate that you __selected__ the tests to run. Since only the four tests are displayed, you can only have selected those four. If you used Run All, you would see an error message in the output window for the two extra tests.

I realize you may have selected the project or class containing the tests, but in the TestExplorer, that simply translates to selecting the test cases themselves. Only the names of the four tests are ever passed to the adapter.
