### ISSUE TITLE
Base class OneTimeTearDown and OneTimeSetup on VS2012

### ISSUE THREAD

**Issue by LateNate** [nunit/nunit3-vs-adapter#129] opened 2016-03-01 10:40 UTC
My solution doesn't work on VS2012 because the OneTimeSetUp/TearDown in derived classes is never called from the Base Class.

This functionality appears to work on VS2013 and later. 

    [TestFixture]
    public class _BaseTestClass
    {
        [OneTimeSetUp]
        public static void SetupBeforeAllTests()
        {
            ...
        }

        [OneTimeTearDown]
        public static void TearDownAfterAllTests()
        {
            ...
        }
    }

    public class test : _BaseTestClass
    {
        [Test]
        public void Test()
        {
            doStuff();
        }
    }

In the above code, when I run Test(), the OneTimeSetUp is never called.

**Comment by CharliePoole** [comment] 2016-03-01 16:29
I think this will be difficult for you to debug, because both Base class and test class are fixtures, one because it has the TestFixture attribute and one because it inherits the attribute. Clearly, you only intend to have one fixture, with baseclass providing part of the implementation of that fixture. To do this you must either put the TestFixture attribute on the derived class or change base class to be abstract.

To be clear, I don't think this has caused your problem but that it may have confused the issue of what is actually happening. Can you try moving the attribute and let us know what happens?

**Comment by CharliePoole** [comment] 2016-04-01 01:24
I'm closing this as non-reproducible and because you haven't added any more info over the past month. If something useful comes up, we can always reopen this.

**Closed** 2016-04-01 01:25 UTC
Labels: closed:norepro
