### ISSUE TITLE
Adapter discovers explicit TestCase without skip details

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit3-vs-adapter#530] opened 2018-07-16 02:08 UTC
Hi all,

I have a custom program that wraps the Visual Studio Test Platform using `IVsTestConsoleWrapper` as demonstrated in the [VSTest samples](https://github.com/Microsoft/vstest/tree/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest). This enables our in-house CI system to run unit tests for .NET Core with more advanced functionality than `dotnet` can provide.

We're using NUnit 3.10.1 and NUnit3TestAdapter 3.10.0.

Given the following three test cases:

```csharp
[Ignore("reasons")]
public void IgnoredTest() => Assert.Fail();

[Explicit("reasons")]
public void ExplicitTest() => Assert.Fail();

[TestCase(null, Explicit = true, Reason = "because")]
public void ExplicitTestCase(object ignored) => Assert.Fail("This test should not be run.");
```

VSTest test discovery does not return the first two tests. It does, however, return the third test, but there are no details provided to say "hey you shouldn't run this test".

![image](https://user-images.githubusercontent.com/426009/42740911-94abeac6-88f0-11e8-827a-d6cdc0b71d70.png)

This is inconsistent / un-actionable.

I can't discover the first two tests - which in my case is good, because I don't want to run them.

I do discover the third test, but that's bad, because I don't want to run it, and cannot distinguish it from any other tests that I do want to run.

Is there anything that NUnit can do here to clean this up, or is this an issue for VSTest?

**Comment by OsirisTerje** [comment] 2018-07-31 21:12
Can you enable the Dump files, see Tips&Tricks https://github.com/nunit/docs/wiki/Tips-And-Tricks  , using a runsettings file, and then upload the results.

**Comment by yaakov-h** [comment] 2018-08-01 01:06
That's a neat trick!

I've attached the source file and the dumped discovery XML.


[NetCoreNUnitTests_WithDiscoveryDump.zip](https://github.com/nunit/nunit3-vs-adapter/files/2247608/NetCoreNUnitTests_WithDiscoveryDump.zip)

**Comment by yaakov-h** [comment] 2018-08-01 07:00
> The discovery should always find them (otherwise you would not be able to run any explicit tests), but does the execution run them?

So I'm in a sticky situation here regarding explicit tests. I'm working on a distributed testing system, where we essentially:

1. Discover all tests
2. Analyze the tests and divide them into small groups
3. Get a bunch of machines to run each group of tests

Since the group of tests includes the explicit tests, the test runner will always execute it, since it was explicitly listed.

Therefore, I need a way to filter out ignored and explicit tests at step 2 of the above process, i.e. between discovery and execution.

When I use VSTest's discovery, I get no information about the Explicit attribute or any hints to it's exisence, no `__SKIPREASON`, etc. - see screenshot in OP.

**Comment by OsirisTerje** [comment] 2018-08-01 20:09
Using the latest adapter (3.10), the explicit tests should also have a category of Explicit.  I tested it again on some test code, and it works as it should.  
![image](https://user-images.githubusercontent.com/203432/43545854-4e9da774-95d7-11e8-867a-d6f230c82b53.png)

This does not work with source based discovery though, but since this is a CI run, you are not using that anyway, that means you're running the discovery phase of the adapter.  As I mentioned above, the adapter adds a category named "Explicit" to all Explicit tests, and you can therefore filter on this category to exclude those tests.

**Comment by yaakov-h** [comment] 2018-08-01 23:46
`[Explicit]` gets treated as explicit just fine, as shown in your screenshot, but `[TestCase(Explicit = true)]` does not.

I also just noticed - if you look at the NUnit discovery XML, these two tests do not appear to be discovered by NUnit (which would explain why VSTest does not return them).

```csharp
[Ignore("reasons")]
public void IgnoredTest() => Assert.Fail();

[Explicit("reasons")]
public void ExplicitTest() => Assert.Fail();
```

There's definitely an inconsistency between `[Explicit]`/`[Ignore]` and their equivalent `[TestCase]` properties.

**Comment by OsirisTerje** [comment] 2018-08-03 19:51
@jnm2 Can you take a look at this ?

**Comment by jnm2** [comment] 2018-08-06 21:31
Happy to!

@yaakov-h 

> I also just noticed - if you look at the NUnit discovery XML, these two tests do not appear to be discovered by NUnit (which would explain why VSTest does not return them).

I was unable to reproduce this with NUnit framework 3.10.1 and the adapter master branch. When framework 3.10.1 explores an assembly with this:

```cs
public class Foo
{
    [TestCase(null, Explicit = true, Reason = "reason")]
    public void Bar(string x) { }
}
```

I get the XML I would expect:

```xml
<test-suite type="TestFixture" id="x1000" name="Foo" fullname="NUnit.Tests.Foo" classname="NUnit.Tests.Foo" runstate="Runnable" testcasecount="1">
  <test-suite type="ParameterizedMethod" id="x1002" name="Bar" fullname="NUnit.Tests.Foo.Bar" classname="NUnit.Tests.Foo" runstate="Runnable" testcasecount="1">
    <test-case id="x1001" name="Bar(null)" fullname="NUnit.Tests.Foo.Bar(null)" methodname="Bar" classname="NUnit.Tests.Foo" runstate="Explicit" seed="553622473">
      <properties>
        <property name="_SKIPREASON" value="reason" />
      </properties>
    </test-case>
  </test-suite>
</test-suite>
```

And when I put that in a unit test just like this test, it passes:

https://github.com/nunit/nunit3-vs-adapter/blob/1af91628171a8792a19a78b7f8ce72cfeab24dd1/src/NUnitTestAdapterTests/TraitsTests.cs#L550-L558

@yaakov-h That's about all I can see. Can you boil down a repro project for us?

**Comment by yaakov-h** [comment] 2018-08-07 04:40
I'm putting together a full repro project, but in the process I reckon this screenshot should speak for itself...

![image](https://user-images.githubusercontent.com/426009/43754764-c2b71394-9a4f-11e8-94ee-f111f4a96a89.png)

**Comment by yaakov-h** [comment] 2018-08-07 05:08
Hmm, so it seems that the "Explicit" trait does show up with the latest framework and adapter, though there is no equivalent for "Ignored".

I've uploaded a repro to https://github.com/yaakov-h/NUnitAdapter530Repro.

The output I'm getting is:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        MISSING: Tests.Fixture.IgnoredTestCase
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        MISSING: Tests.Fixture.ExplicitTestCase
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        MISSING: Tests.Fixture.IgnoredTestCase
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        MISSING: Tests.Fixture.ExplicitTestCase
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

The output I would expect is either:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
```

Or:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTestCase
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTestCase
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

with some way to identify the tests that should be Ignored, too.

**Comment by yaakov-h** [comment] 2018-12-04 23:02
I assume nobody's had a chance to dig into the repro yet?

**Comment by OsirisTerje** [comment] 2019-01-30 16:12
@jnm2 Can you have a look again at this?

**Comment by jnm2** [comment] 2019-02-01 02:03
Thanks for the ping; I fell behind. Happy to!

**Comment by jnm2** [comment] 2019-02-01 02:05
This appears to be a framework bug. Both 3.10.1 and 3.11.0 give:

```xml
<test-suite type="Assembly" id="1008" name="NUnitXmlTest.dll" fullname="NUnitXmlTest.dll" runstate="Runnable" testcasecount="4">
  <properties>
    <property name="_PID" value="38052" />
    <property name="_APPDOMAIN" value="NUnitXmlTest" />
  </properties>
  <test-suite type="TestSuite" id="1009" name="NUnitXmlTest" fullname="NUnitXmlTest" runstate="Runnable" testcasecount="4">
    <test-suite type="TestFixture" id="1000" name="Fixture" fullname="NUnitXmlTest.Fixture" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="4">
      <test-suite type="ParameterizedMethod" id="1007" name="ExplicitTestCase" fullname="NUnitXmlTest.Fixture.ExplicitTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1006" name="ExplicitTestCase(null)" fullname="NUnitXmlTest.Fixture.ExplicitTestCase(null)" methodname="ExplicitTestCase" classname="NUnitXmlTest.Fixture" runstate="Explicit" seed="1262453225">
          <properties>
            <property name="_SKIPREASON" value="because" />
          </properties>
        </test-case>
      </test-suite>
      <test-suite type="ParameterizedMethod" id="1005" name="IgnoredTestCase" fullname="NUnitXmlTest.Fixture.IgnoredTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1004" name="IgnoredTestCase(null)" fullname="NUnitXmlTest.Fixture.IgnoredTestCase(null)" methodname="IgnoredTestCase" classname="NUnitXmlTest.Fixture" runstate="Ignored" seed="1726680985">
          <properties>
            <property name="_SKIPREASON" value="because" />
          </properties>
        </test-case>
      </test-suite>
      <test-case id="1001" name="PassingTest" fullname="NUnitXmlTest.Fixture.PassingTest" methodname="PassingTest" classname="NUnitXmlTest.Fixture" runstate="Runnable" seed="1029543833" />
      <test-suite type="ParameterizedMethod" id="1003" name="PassingTestCase" fullname="NUnitXmlTest.Fixture.PassingTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1002" name="PassingTestCase(null)" fullname="NUnitXmlTest.Fixture.PassingTestCase(null)" methodname="PassingTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" seed="1215827924" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-suite>
```

There's nothing the adapter can do if the framework decides it isn't going to output XML nodes for `IgnoredTest` and `ExplicitTest`!

**Comment by jnm2** [comment] 2019-02-01 02:08
I just spotted the problem. 😁

@yaakov-h You need to mark the methods as test methods:

```diff
+[Test, Ignore("reasons")]
-[Ignore("reasons")]
 public void IgnoredTest() => Assert.Fail();
 
+[Test, Explicit("reasons")]
-[Explicit("reasons")]
 public void ExplicitTest() => Assert.Fail();
```

Looks like everything is working as expected in 3.10.1 and 3.11.0!

**Comment by yaakov-h** [comment] 2019-02-01 02:35
Ughhhhhhhhh good catch.

Okay, so after fixing that (repro repo updated), updating NUnit, and getting back to the core issue, I get this output:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTest
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTest
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTest
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTest
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

I can filter for the trait `Explicit` with an empty value, but my concern has how flipped... there's no way to identify that the _Ignored_ tests should not be run.

**Comment by jnm2** [comment] 2019-02-13 12:30
Why do you need metadata telling you which ones are ignored? They aren't runnable. The engine just reports an ignored result if VSTest asks to execute them.

**Comment by yaakov-h** [comment] 2019-02-13 19:25
My company’s testing system is distributed.

I’d rather not discover a test, find a worker node, upload the binaries, run some initialisation and start executing only to then discover that the test should not have been run in the first place.

**Comment by jnm2** [comment] 2019-02-14 00:24
Very cool! Some points that come to mind:

- The VSTest adaptation is not as rich a representation as NUnit XML. I'll assume that the reason you're using VSTest XML instead of NUnit XML is that you have non-NUnit tests in the mix.

- `[Ignore]` was conceived as a way to indicate poor test health as a team TODO. If there are ever a significant number of ignored tests, that indicates a problem according to how I understand the original NUnit authors. Therefore, should you be trying to optimize your distributed system to work well with ignored tests? If you take the same philosophy, the pressure to eliminate ignored tests might be a benefit.

- Instead of reporting ignored tests, would there be a benefit to you if you could specify a VSTest filter such as `!Ignored` or `Ignored!=true` (if we can get that to work) or `Category!=Ignored`? Or would you still want to know that the ignored tests exist?

If none of those sound interesting, we can definitely surface a new VSTest property or trait. We do this on a case-by-case basis since it's extra work for us and because there's no 1:1 mapping from NUnit's test model to VSTest's, so we need a real-world use case like yours to drive the design.

**Comment by yaakov-h** [comment] 2019-02-14 04:12
> I'll assume that the reason you're using VSTest XML instead of NUnit XML is that you have non-NUnit tests in the mix.

That's been an unexpected side-benefit, but the real reason is that it's the only way I've found to run .NET Core tests outside of the IDE or `dotnet` toolchain, i.e. on precompiled binaries, without the source code.

> would there be a benefit to you if you could specify a VSTest filter

That could be useful. At the moment we ignore ignored and explicit tests outright, so being able to ask the VSTest engine for not-those would save me some extra code to filter them out.

**Comment by jnm2** [comment] 2019-02-20 01:00
@OsirisTerje I'm inclined to make filtering understand how to filter out ignored and explicit tests. What are your thoughts?

@yaakov-h Have you considered the second point, that effort could go to reducing the number of ignored tests rather than optimizing to make it easier to keep them around?

**Comment by yaakov-h** [comment] 2019-02-20 01:12
@jnm2 in a perfect world, sure. I’d have to check how many we have and why. I don’t think it’s many, but I’m concerned about flow-on effects into other parts of our testing system.

**Comment by OsirisTerje** [comment] 2020-07-02 21:06
In the upcoming version, Explicit tests will not be returned, by default.  Ignored tests will have an ignored/skipped result given.  @jnm2 Should we add a runsettings property to skip returning  anything on stuff that is not run at all ?

**Comment by jnm2** [comment] 2020-07-05 17:59
What would be the net difference that would make me as a user go looking for a setting?

**Comment by OsirisTerje** [comment] 2020-07-05 19:15
In the test explorer. the "not run at all" will show up as dimmed test cases.  The alternative would be that they would be marked as "Skipped" - with that slightly bluish color.  The Ignored will be that now, the explicit not.  So, just if anyone cares about that - I would not bother, they are both ignored, and if I want to run them, I can - by selecting them (the explicit ones that is).  So, no, I am not sure why anyone would like them to be treated equal.....

**Comment by OsirisTerje** [comment] 2021-05-03 07:35
Version 4.0.0-beta.2 doesn't run these tests.

**Closed by OsirisTerje** 2021-05-03 07:35 UTC
Labels: closed:fixedinnewversion
