### ISSUE TITLE
Test Explorer shows excess class name for tests with multiple TestCaseAttribute

### ISSUE THREAD

**Issue by Deni35** [nunit/nunit3-vs-adapter#644] opened 2019-08-07 11:59 UTC
Look at `UnitTests1.Test_3`. What is that class name for? Is it bug or feature?

![Test Explorer](https://user-images.githubusercontent.com/7755015/62620960-4d192c00-b923-11e9-82c2-87f52e10ed29.png)

```
public class UnitTests1 {

    [TestCase( 0 )]
    public void Test_1(int id) {
    }

    [Test]
    public void Test_2() {
    }

    [TestCase( 666 )]
    [TestCase( 777 )]
    public void Test_3(int id) {
    }
    //[TestCase( null )]
    //public void Test_3(string id) {
    //}

    [Test]
    public void Test_4() {
    }

    [Test]
    public void Test_5() {
    }

}
```

**Comment by johnmwright** [comment] 2019-10-28 20:42
I believe this issues is caused by the same underlying issues at #622 and is resolved by PR https://github.com/nunit/nunit3-vs-adapter/pull/668

**Comment by OsirisTerje** [comment] 2019-11-01 18:29
I checked this now with VS 16.3.4 and adapter 3.13, and it looks right.  
I also can't detect any change with updating to 3-16.0-dev

**Closed** 2019-11-01 18:31 UTC
Labels: VS Issue, is:bug
