### ISSUE TITLE
"System.FormatException: The UTC representation of the date falls outside the year range 1-9999" from skipped test in Eastern European time zone

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [nunit/nunit3-vs-adapter#811] opened 2021-01-11 16:58 UTC
I have a C# test project in which a test fixture class has NUnit.Framework.ExplicitAttribute. The project references NUnit3TestAdapter and NUnit from NuGet. I then run `vstest.console.exe "REDACTED.dll" /Parallel /Framework:".NETFramework,Version=4.5" /Platform:x64 /Logger:trx;LogFileName=".NETFramework,v4.5.trx" /ResultsDirectory:"Test\TestResults"` and get a FormatException for each test that was skipped because of the ExplicitAttribute:

```
Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.17.0.0: Test execution started
Running all tests in REDACTED.dll
   NUnit3TestExecutor discovered 13 of 13 NUnit test cases

Error processing REDACTED event for REDACTED
System.FormatException: The UTC representation of the date falls outside the year range 1-9999.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitTestEvent.StartTime() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitTestEvent.cs:line 135
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(INUnitTestEvent resultNode, IEnumerable`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 302
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVsTestResults(INUnitTestEventTestCase resultNode, ICollection`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 111
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 160
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 92
```

I tried to debug this. The string being converted seems to be "0001-01-01T00:00:00.0000000". The computer is in UTC+2 Eastern European time zone, so the corresponding UTC time is before year 1.

Versions:

* NUnit3TestAdapter 3.17.0; the problem also happens with 3.15.1.
* NUnit 3.13.0; the problem **does not happen** with 3.10.1.
* vstest.console.exe 15.9.1 from Visual Studio Professional 2017 version 15.9.30
* .NET Framework 4.8, but the test project targets .NET Framework 4.5

**Comment by OsirisTerje** [comment] 2021-01-11 19:31
The Explicit attribute is not supported for 3.17 (nor 3.15) (but works in 4.0-alpha and beta), but it should not give this format exception, so this is weird. 

Does this reproduce with just a simple bare test?

**Comment by mikkelbu** [comment] 2021-01-11 20:51
I think the reason for this error is nunit/nunit#3311. If I change the reading of the time to use `DateTime.Parse` as @jnm2 suggested, then it works on my machine.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-11 21:32
<https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html> says

> + **start-time** The UTC time that the test run started.

NUnitTestEvent.StartTime should not try to convert it from local time to UTC when it is already UTC.

<https://github.com/nunit/nunit3-vs-adapter/blob/600fd7ee7f8d4b2484e3d692959089cae0026b91/src/NUnitTestAdapter/NUnitEngine/NUnitTestEvent.cs#L132-L138>

How about adding [DateTimeStyles.AssumeUniversal](https://docs.microsoft.com/dotnet/api/system.globalization.datetimestyles?view=netstandard-1.3)? Maybe that would just move the problem to some other phase of test reporting.

> can you check if the problem was also in NUnit 3.12.0?

Tomorrow.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-11 22:01
> The Explicit attribute is not supported for 3.17

I should check whether IgnoreAttribute likewise causes a FormatException.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-11 22:40
> can you check if the problem was also in NUnit 3.12.0?

The exceptions occur with NUnit 3.13.0 but not with NUnit 3.12.0.

> Does this reproduce with just a simple bare test?

Yes, it does. Even IgnoreAttribute causes the same exception.

## NUnit3VSIssue811.csproj

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.5</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.2" />
  </ItemGroup>

</Project>
```

## Explicit.cs

```C#
using NUnit.Framework;

namespace NUnit3VSIssue811
{
    [TestFixture]
    [Explicit("https://github.com/nunit/nunit3-vs-adapter/issues/811")]
    public class Explicit
    {
        [Test]
        public void ExplicitTest()
        {
        }
    }
}
```

## Ignore.cs

```C#
using NUnit.Framework;

namespace NUnit3VSIssue811
{
    [TestFixture]
    [Ignore("https://github.com/nunit/nunit3-vs-adapter/issues/811")]
    public class Ignore
    {
        [Test]
        public void IgnoredTest()
        {
        }
    }
}
```

## Execution

In Visual Studio 2017 Developer Command Prompt:

```
c:\Projects\NUnit3VSIssue811>vstest.console.exe bin\Debug\net4.5\NUnit3VSIssue811.dll /Framework:".NETFramework,Version=v4.5" /Platform:x64
Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.17.0.0: Test execution started
Running all tests in c:\Projects\NUnit3VSIssue811\bin\Debug\net4.5\NUnit3VSIssue811.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases
Error processing ExplicitTest event for NUnit3VSIssue811.Explicit.ExplicitTest
System.FormatException: The UTC representation of the date falls outside the year range 1-9999.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitTestEvent.StartTime() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitTestEvent.cs:line 135
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(INUnitTestEvent resultNode, IEnumerable`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 302
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVsTestResults(INUnitTestEventTestCase resultNode, ICollection`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 111
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 160
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 92
Error processing IgnoredTest event for NUnit3VSIssue811.Ignore.IgnoredTest
System.FormatException: The UTC representation of the date falls outside the year range 1-9999.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitTestEvent.StartTime() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitTestEvent.cs:line 135
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(INUnitTestEvent resultNode, IEnumerable`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 302
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVsTestResults(INUnitTestEventTestCase resultNode, ICollection`1 outputNodes) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 111
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 160
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 92
NUnit Adapter 3.17.0.0: Test execution complete
No test is available in c:\Projects\NUnit3VSIssue811\bin\Debug\net4.5\NUnit3VSIssue811.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

## Workaround

Move the ExplicitAttribute and IgnoreAttribute from the text fixture classes to the test methods.  Then, there is no exception:

```
c:\Projects\NUnit3VSIssue811>vstest.console.exe bin\Debug\net4.5\NUnit3VSIssue811.dll /Framework:".NETFramework,Version=v4.5" /Platform:x64
Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.17.0.0: Test execution started
Running all tests in c:\Projects\NUnit3VSIssue811\bin\Debug\net4.5\NUnit3VSIssue811.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases
ExplicitTest: https://github.com/nunit/nunit3-vs-adapter/issues/811
IgnoredTest: https://github.com/nunit/nunit3-vs-adapter/issues/811
NUnit Adapter 3.17.0.0: Test execution complete
Not Run  ExplicitTest
Skipped  IgnoredTest

Total tests: 2. Passed: 0. Failed: 0. Skipped: 1.
Test Run Successful.
Test execution time: 1,4073 Seconds
```

**Comment by OsirisTerje** [comment] 2021-01-12 09:16
Thanks for the repro!  And yes, I can confirm this.  It fails using the vstest.console, but works in Visual Studio.   Adding a test for it in the adapter will fail though, so....

```
<NUnitTestEvent>
<test-case id='0-1001' name='ExplicitTest' fullname='NUnit3VSIssue811.Explicit.ExplicitTest' methodname='ExplicitTest' classname='NUnit3VSIssue811.Explicit' runstate='Runnable' seed='1980958818' result='Skipped' label='Explicit' site='Parent' start-time='0001-01-01T00:00:00.0000000' end-time='0001-01-01T00:00:00.0000000' duration='0.000000' asserts='0' parentId='0-1000'>
   <reason>
      <message><![CDATA[OneTimeSetUp: https://github.com/nunit/nunit3-vs-adapter/issues/811]]></message>
   </reason>
</test-case>
</NUnitTestEvent>
```
Your suggestion with adding DateTimeStyles.AssumeUniversal works though.  But the underlying cause is that the starttime comes out in the NUnit 3.13 as the equivalent of null.  @jnm2 @mikkelbu What was changed here ?

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-12 09:28
> Your suggestion with adding DateTimeStyles.AssumeUniversal works though.

I worry that it might cause an error if DateTimeStyles.AssumeUniversal makes DateTimeOffset.Parse treat 0001-01-01T00:00:00.0000000 as 0001-01-01T00:00:00.0000000Z and the adapter then tries to convert that to local time in an American time zone. I don't know whether the adapter ever tries to do so.

**Comment by OsirisTerje** [comment] 2021-01-12 11:59
I don't think it does, but dates and timezones are hard :-)  I would believe this fix hardens the adapter, but I don't understand why we should send this datetime from the framework.  The starttime should be the actual start of test as a default, then we would never get into these kinds of issues, but that is a fix in the framework.  @jnm2 @rprouse @mikkelbu - comments ?

**Comment by rprouse** [comment] 2021-01-12 12:55
I'll have to check what changed in NUnit, but I think the time should be coming across from the framework with the Z at the end to indicate UTC.

**Comment by OsirisTerje** [comment] 2021-01-12 15:14
@rprouse Looking at the dump, it comes back without any Z:
```
<test-case id='0-1001' name='ExplicitTest' fullname='NUnit3VSIssue811.Explicit.ExplicitTest' methodname='ExplicitTest' classname='NUnit3VSIssue811.Explicit' runstate='Runnable' seed='1980958818' result='Skipped' label='Explicit' site='Parent' start-time='0001-01-01T00:00:00.0000000' end-time='0001-01-01T00:00:00.0000000' duration='0.000000' asserts='0' parentId='0-1000'>
 ```

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-12 15:39
The format string in the DateTime.ToString call was changed from "u" to "o" in <https://github.com/nunit/nunit/pull/3335>, between v3.12 and v3.13. If the StartTime property is never set, then it is default(DateTime), i.e. 0001-01-01T00:00:00.0000000 with DateTimeKind.Unspecified. [The "u" format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-universal-sortable-u-format-specifier) ignored the DateTimeKind, assumed that the value was in UTC, and returned "0001-01-01 00:00:00Z". [The "o" format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier) instead notices DateTimeKind.Unspecified and returns "0001-01-01T00:00:00.0000000" without time zone information.

However, that does not yet explain why the FormatException is not thrown if the attribute is on the test method rather than on the test fixture class. It seems to me that NUnit should output the same XML in both cases.

**Comment by OsirisTerje** [comment] 2021-01-12 21:26
The issue indicates there might be an issue in the framework, but the adapter should handle the time XML information with the suggested change above - to make it more resilient.  

@KalleOlaviNiemitalo I suggest you raise this issue in the NUnit framework repo and link it to this issue, so that we can handle the changes there too.

**Comment by rprouse** [comment] 2021-01-13 18:59
I created nunit/nunit#3724 which is assigned to the 3.13.1 milestone which I hope to release by the end of the month.

**Closed** 2021-01-14 20:10 UTC
Labels: is:bug

**Comment by OsirisTerje** [comment] 2021-04-06 20:22
@KalleOlaviNiemitalo  Please check out:   The package NUnit3TestAdapter 4.0.0-beta.2 https://www.nuget.org/packages/NUnit3TestAdapter/4.0.0-beta.2  was recently published on NuGet Gallery. Release notes: https://docs.nunit.org/articles/vs-test-adapter/Adapter-Release-Notes.html
