### ISSUE TITLE
dotnet test with category filter is slow with a lot of tests

### ISSUE THREAD

**Issue by jskeet** [nunit/nunit3-vs-adapter#497] opened 2018-03-29 15:09 UTC
When there are thousands of tests, filtering by category takes a huge amount of time.

I noticed this with Noda Time when trying to migrate from NUnitLite to dotnet test, but I've now reproduced separately.

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.2" />
    <PackageReference Include="NUnit" Version="3.10.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
  </ItemGroup>
</Project>
```

I have 500 generated test classes, each of which has 40 tests in, like this:

```csharp
using NUnit.Framework;
public class GeneratedTest0
{
    [Test] public void Test1() { }
    [Test] public void Test2() { }
    [Test] public void Test3() { }
    [Test] public void Test4() { }
    ...
}
```

(I'm happy to provide the generator code if that would help.)

When running the tests without a filter, they're reasonably quick:

```text
dotnet test -c Release
...
Total tests: 20000. Passed: 20000. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 13.9321 Seconds
```

When a filter is specified, it slows down massively - from 14 seconds to over 110:

```text
dotnet test -c Release --filter=TestCategory!=Slow
...
Total tests: 20000. Passed: 20000. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.9212 Minutes
```

An equivalent test with xUnit didn't show the same issue, so I don't *think* it's a problem in `dotnet test` itself. (I'm working on running this through a profiler to see.)

Version information for dotnet:

```text
dotnet --info
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

I have VS15.6.4 installed, if that's relevant.

**Comment by jskeet** [comment] 2018-03-31 07:42
It looks like the problem isn't specific to category filtering - it's any *negative* filter. So `FullyQualifiedName!=Foo` exhibits the same slowness.

If I apply a *positive* filter, e.g. `TestCategory=Foo`, that's matched quickly. Are negative filters applied in a completely different way to negative ones? Positive regex matches (e.g. `TestCategory~Foo`) are quick too.

**Comment by rprouse** [comment] 2018-03-31 21:15
Thanks for the detailed report @jskeet. I'd like to determine if this issue is in the adapter, in the framework, or possibly in the engine. I suspect it is in the framework itself.

Could you share the code so that I can check, or could you target `net461` and run with the NUnit Console? You will likely need to add `<DebugType>Full</DebugType>` to the project file to get it to run.

I am putting the confirm label on the issue until we determine which project it belongs in.

**Comment by jskeet** [comment] 2018-04-01 07:09
Here are the tests:
[Filtering.zip](https://github.com/nunit/nunit3-vs-adapter/files/1866163/Filtering.zip)

The test generator if you want it:

```csharp
using System;
using System.IO;
using System.Linq;

namespace TestGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            int classes = int.Parse(args[0]);
            int tests = int.Parse(args[1]);
            for (int i = 0; i < classes; i++)
            {
                var lines = new[] { "using NUnit.Framework;", $"public class GeneratedTest{i}", "{" }
                    .Concat(Enumerable.Range(1, tests).Select(index => $"    [Test] public void Test{index}() {{ }}"))
                    .Concat(new[] { "}" });
                File.WriteAllLines($"GeneratedTest{i}.cs", lines);
            }
        }
    }
}
```

I ran that with arguments of 500 40 (to create 500 test files with 40 tests per file).

I don't have time to run the console runner right now (just dashing off) but will try to do so later today.

**Comment by jskeet** [comment] 2018-04-01 11:45
Running with net461 (release build) on nunit3-console.exe:

- No filter: 46 seconds (so still a lot slower than with `dotnet test`, interestingly)
- `--where=cat!=Slow`: 58 seconds (so faster than `dotnet test` with a negative category filter)

Let me know anything else you'd like me to try.

**Comment by rprouse** [comment] 2018-04-01 13:24
Here are the results from my initial tests,

Platform | Runner | Neg Filter | Seconds
-- | -- | -- | --
netcoreapp2.0 | dotnet test | no | 8.7
netcoreapp2.0 | dotnet test | yes | 73
net461 | dotnet test | no | 21.7
net461 | dotnet test | yes | 110
net461 | console | no | 26.4
net461 | console --inprocess | no | 18.2
net461 | console --inprocess | yes | 18.7

Initial conclusions,

- Running with and without negative filters against 4.6.1 in the console is not different, therefore the issue is not in the engine or the framework
- .NET Core seems to be significantly faster then .NET 4.6.1. Since the NUnit Framework code for .NET 4.5 and .NET Standard 2.0 is nearly identical, I am guessing it is down to .NET Core being more efficient?
- The slowdown running under the console is caused by running out of process and communicating over .NET Remoting. Running in-process is faster than `dotnet test`.

Based on this, I am going to look at the filters that are passed into the adapter by VSTest and the filter conversion in the adapter.

**Comment by jskeet** [comment] 2018-04-01 13:31
I'm glad you're at least able to reproduce it. Just to add that I did run both the filtered and non-filtered versions (with dotnet test) through a profiler, but that didn't reveal anything obvious I'm afraid... nor did casual examination of the filtering code.

Do you have any knowledge of how xUnit handles its communication? (I only ask as it doesn't seem to exhibit the same symptoms, so finding any significant differences in how it deals with filters could be useful.)

**Comment by rprouse** [comment] 2018-04-01 13:34
I was just about to test with xUnit to see if it is in VSTest itself. It sounds like you did already, so I will skip doing that. As for how it handles filters, I haven't looked at their adapter code.

**Comment by jskeet** [comment] 2018-04-01 13:49
Yes, it doesn't seem to make any significant difference in xUnit. Just to save you a bit of time if you want to run the same test yourself (e.g. in a profiler), here's the test generator for xUnit:

```csharp
using System;
using System.IO;
using System.Linq;

namespace TestGenerator2
{
    class Program
    {
        static void Main(string[] args)
        {
            int classes = int.Parse(args[0]);
            int tests = int.Parse(args[1]);
            for (int i = 0; i < classes; i++)
            {
                var lines = new[] { "using Xunit;", $"public class GeneratedTest{i}", "{" }
                    .Concat(Enumerable.Range(1, tests).Select(index => $"    [Fact] public void Test{index}() {{ }}"))
                    .Concat(new[] { "}" });
                File.WriteAllLines($"GeneratedTest{i}.cs", lines);
            }
        }
    }
}
```

Just to add yet more data, I tried (back with NUnit) using parameterized tests. That gave a significant slowdown, but not as much. Test code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace TestCaseFilter
{
    public class ParameterizedTest
    {
        private static IEnumerable<int> Counter => Enumerable.Range(1, 20000);
        
        [TestCaseSource(nameof(Counter))]
        public void CountTest(int count)
        {
        }
    }
}
```

Run times using netcoreapp2.0 in release mode:

- No filter: 10s
- Negative filter: ~66s
- Positive filter finding tests: ~66s (interesting...)
- Positive filter not finding tests: almost instantaneous

The last two are interesting I hadn't changed my generator before to make all the tests have a category; I was just going by the "positive tests quickly find that there's nothing to run" part. The discrepancy between a test case source and multiple actual tests is interesting though.

**Comment by rprouse** [comment] 2018-04-01 13:56
I think this code in `NUnitTestFilterBuilder` is the issue,

```C#
        public TestFilter ConvertTfsFilterToNUnitFilter(TfsTestFilter tfsFilter, List<TestCase> loadedTestCases)
        {
            var filteredTestCases = tfsFilter.CheckFilter(loadedTestCases);
            var testCases = filteredTestCases as TestCase[] ?? filteredTestCases.ToArray();
            //TestLog.Info(string.Format("TFS Filter detected: LoadedTestCases {0}, Filterered Test Cases {1}", loadedTestCases.Count, testCases.Count()));
            return MakeTestFilter(testCases);
        }

        public TestFilter MakeTestFilter(IEnumerable<TestCase> testCases)
        {
            if (testCases.Count() == 0)
                return NoTestsFound;

            ITestFilterBuilder filterBuilder = _filterService.GetTestFilterBuilder();

            foreach (TestCase testCase in testCases)
                filterBuilder.AddTest(testCase.FullyQualifiedName);

            return filterBuilder.GetFilter();
        }
```

Rather than converting the negative filter into the NUnit equivalent, this code is selecting all tests that match and then creates a filter that specifically includes those tests based on their FullyQualifiedName. The resulting filter will be huge in this case.

@jnm2 you were in this code recently, can you comment on why we do it this way? Probably because it is just the easiest way to do the conversion? @OsirisTerje any comments?

**Comment by jskeet** [comment] 2018-04-01 14:04
I've just changed the test generator to generate with a category of "Fast", and the results are:

- No filter: ~15s
- `TestCategory!=Slow`: 1.4 minutes
- `TestCategory!=Fast`: A few seconds
- `TestCategory=Fast`: 1.5 minutes
- `TestCategory=Slow`: A few seconds

So it's not positive/negative testing - it's "if there's a filter, and it matches some tests".

**Comment by OsirisTerje** [comment] 2018-04-01 18:52
@rprouse  This code is unchanged since inception, and it doesn't behave differently for positive or negative filters.  It  first asks the vstest to filter the list (we call back to vstest), it gets back a filtered list of test cases, and then it fills a NUnit name filter with the names that matches and returns that.  
I can't really see how this would be different for positive and negative tests.  The behaviour is the same.  (And it seems that is what @jskeet confirms now, right?)  

Also note that if the adapter is called without any filter and with the Run All, that is - not any kind of selection, the filtering code is not invoked at all.  

We have had discussions about how to handle the filtering several times during the last 2 years.  @CharliePoole's latest proposal was to create our own filter parser for the VSTest syntax.

**Comment by CharliePoole** [comment] 2018-04-01 20:04
@rprouse You've come across exactly the point I've made several times. We __use__ the filter without understanding it. The only way available to use the filter is to apply it and come up with a list of names. I"ve proposed instead reading the text of the filter, which is available to us, parsing it and converting it to an NUnit filter.

@OsirisTerje It works the same for positive and negative filters, but the impact would be significantly greater. If we have a thousand tests and include two of them, the filter contains two elements. But if we exclude two tests in the same in the same situation, the filter contains 998 elements. We could do some optimization but it would require a lot of processing, probably more than just doing the suggested translation.

I feel I must point out that you turned down the proposal you mentioned. 😕

**Comment by OsirisTerje** [comment] 2018-04-01 20:31
@CharliePoole I didn't turn it down.  I stored it :-)

**Comment by CharliePoole** [comment] 2018-04-02 15:02
@OsirisTerje Sorry. What I meant was "Are you saying that you expected me to implement the proposal?" It's always better to ask a question when you have a question.

**Comment by OsirisTerje** [comment] 2018-04-02 16:48
@CharliePoole Ahh, no - no such expectation intended !  
I just wanted to point out that your proposal earlier probably matches what we need to do here.  Given this issue, it might resolve it and bring the times down to match the times for the NUnit.console.

**Comment by rprouse** [comment] 2018-04-03 13:10
> I can't really see how this would be different for positive and negative tests. The behaviour is the same. (And it seems that is what @jskeet confirms now, right?)

@OsirisTerje I think that you understand the issue now based on previous comments, but just in case, @jskeet's last comment confirms that it is not the fact that the test cases are positive or negative, but the number of tests that are selected by the filter since each selected test is added to the filter collection individually and filters with that many entries are much slower to process and work with.

**Comment by OsirisTerje** [comment] 2018-04-03 18:28
@rprouse Absolutely.  
I have also done the following performance traces, using a test program with 6000 tests, half with a category set. 
1:  Run with category set, giving 3000 tests
![image](https://user-images.githubusercontent.com/203432/38267954-345677b4-377d-11e8-8f94-0ed3807cfa2c.png)

2: Run without any category set, giving 6000 tests
![image](https://user-images.githubusercontent.com/203432/38267971-3ee57c3e-377d-11e8-8403-cf5f473931e4.png)

3. Hardcoded with new filter set, matching what it would be if we did a parse of the filter and sent that down to the engine, giving 3000 tests
![image](https://user-images.githubusercontent.com/203432/38268016-5ccbb36c-377d-11e8-8c48-9f7039f37e53.png)

So it seems that converting to use a filter conversion to NUnit filter would do the trick.

**Comment by OsirisTerje** [comment] 2019-02-15 10:02
I checked up on this now, and can't see the same behavior anymore using @jskeet 's test code above. 
![image](https://user-images.githubusercontent.com/203432/52849282-f0297f80-3110-11e9-8d28-3ffb071ff9ac.png)
![image](https://user-images.githubusercontent.com/203432/52849291-f7508d80-3110-11e9-9a95-453f32873478.png)

The test runner is the VS 2019 preview test runner, but it should not matter.....
Using it with the new code doesnt change anything now.
@rprouse Can you check on your side again ?

**Comment by jskeet** [comment] 2019-02-15 10:10
I'm happy to give this a go with Noda Time as well.

**Comment by OsirisTerje** [comment] 2019-02-15 10:15
@jskeet 

And for comparison, here is the pre version of the adapter with the new filter, and a runsettings file that enables it.  
[NUnit3TestAdapter.3.13.0-e01.zip](https://github.com/nunit/nunit3-vs-adapter/files/2868796/NUnit3TestAdapter.3.13.0-e01.zip)

**Comment by jskeet** [comment] 2019-02-15 10:19
@OsirisTerje: Ah, I hadn't realized this wasn't with a released version. Will still give it a try, but it may end up being a bit too invasive to test easily.

**Comment by OsirisTerje** [comment] 2019-02-15 10:22
@jskeet The **thing** is that I can't repro anymore with the older version.  I know it worked 6 months ago, but now I just get the same results regardless of filtering.  Not sure if there is something I do wrong, so if you could just recheck on your side, it would be awesome.  

If that comes out positive on your side, you could just do the test with the enclosed one and then see if that fixes it.  If it does, then I'll add up the PR for it.

**Comment by jskeet** [comment] 2019-02-15 11:27
Okay, I can confirm that the pre version works with Noda Time:

With 3.12.0:

```text
$ dotnet test
...
Total tests: 17950. Passed: 17948. Failed: 0. Skipped: 0.
Test execution time: 1.4451 Minutes

$ dotnet test --filter=TestCategory!=Slow
...
Total tests: 17945. Passed: 17945. Failed: 0. Skipped: 0.
Test execution time: 1.8256 Minutes
```

With 3.13.0-e01:

```text
$ dotnet test --settings Simple.runsettings
...
Total tests: 17950. Passed: 17948. Failed: 0. Skipped: 0.
Test execution time: 1.3672 Minutes

$ dotnet test --filter=TestCategory!=Slow --settings Simple.runsettings
...
Total tests: 17947. Passed: 17945. Failed: 0. Skipped: 0.
Test execution time: 21.8506 Seconds
```

**Comment by OsirisTerje** [comment] 2019-02-15 13:37
@jskeet  21 seconds !    That is good, I suppose...  But... Don't understand why you get test times over 1  minute in the other cases ....  Anyway, I'll put the changes in the 13.0-e01 through the full check of tests, and get it up.    
Currently it is under a feature flag, with default off.  Wonder if it would be better to set it to default true......  Then if there are some issues people can opt out.

**Comment by jskeet** [comment] 2019-02-15 13:41
@OsirisTerje: To be clear, these are the real Noda Time tests. The "slow" tests are really slow. Those times are about what I'd expect normally for running all vs "just quick" tests. The outlier here is the "filtered but using 3.12.0" case, where the actual *tests* are only taking 21 seconds, but the filtering is adding a minute of overhead.

(Admittedly the fact that skipped-by-default tests aren't reported as skipped is odd, but that's a different matter.)

As for the feature flag - it would be useful to *me* for it to be the default, but I don't know enough about the context to comment in general.

**Comment by rprouse** [comment] 2019-02-15 14:23
@OsirisTerje it looks like you and @jskeet have worked this out and don't need my help anymore. I am getting on a plane today for a week-long ski trip, so I don't have too much time. I did notice that the same number of tests are run with and without the filters which seems odd.

**Comment by jskeet** [comment] 2019-02-15 14:26
Not quite the same in Noda Time: 17948 without filters, 17945 with filters.

It *is* the same in the generated test cases I started this issue with, because the filter actually matches all the tests. (There aren't any tests in a category of "slow".)

**Comment by jskeet** [comment] 2020-01-18 14:50
@OsirisTerje Any update on when this is likely to be fixed in a release? Every time there's a new release I check the release notes hoping to see something about this, but I haven't seen anything yet :(

**Comment by jskeet** [comment] 2020-01-18 14:54
Admittedly the alternative of "use a runsettings file with an NUnit test selector" works well - but it would be nice to be able to do this easily without the file :)

**Comment by OsirisTerje** [comment] 2020-01-18 16:12
@jskeet Yeah, understand you absolutely.  What scares me from doing it full on is the issues we've had when releasing both 3.15 and 3.16, both requiring hotfixes afterwards.  We have a "moving target" on the Visual Studio side - they are changing the inner workings, not the interfaces per se, but the way they use the interfaces,  and we've had long time issues related in particular to parametrized tests, which hit in the same place as this PR does.   And these issues escapes our testing, which really annoys me.  We've got an end-to-end test system up now, and I hope to get the latest issues in there.  We also need to be able to test against all the different variations of usage we have now.   The pre-release version does not attract any attention, so there is very few people testing those.   To make that easier I'm planning on having dev versions as now on myget, but releasing betas on nuget.    Have you seen any of the issues related to the latest we've had?    These are the [3.16 bugs fixed in 3.16.1](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and these are the [3.15 bugs fixed in 3.15.1](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+is%3Aclosed+milestone%3A3.15.1)

**Comment by jskeet** [comment] 2020-01-18 16:42
@OsirisTerje: Understood, and thanks for the swift response. I haven't seen any issues, but I've only just (as of this afternoon!) updated from 3.14 straight to 3.16.1. Using the runsettings to provide a filter massively reduced my CI time, so I'm very grateful for that :)

**Comment by OsirisTerje** [comment] 2020-07-11 23:20
@jskeet  Releasing an alpha version now of version 4.0.  The performance looks now like it is not dependent upon the filters.  

There will be a package soon at the myget feed.  I'll get an alpha version up on the nuget feed within a day or so.  
It needs more testing for edge cases, but all normal test goes as it should. 

![image](https://user-images.githubusercontent.com/203432/87235588-ca73d900-c3dd-11ea-89bd-51f0ee7265ae.png)

**Closed by OsirisTerje** 2020-07-11 23:20 UTC
Labels: closed:done, is:bug, pri:normal

**Comment by OsirisTerje** [comment] 2020-07-11 23:28
Resolved with https://github.com/nunit/nunit3-vs-adapter/pull/763

**Comment by jskeet** [comment] 2020-07-12 07:35
@OsirisTerje: Wonderful! Thanks, will give it a whirl :)

**Comment by OsirisTerje** [comment] 2020-07-12 16:33
@jskeet Alpha.1 released now:  https://www.nuget.org/packages/NUnit3TestAdapter/4.0.0-alpha.1

**Comment by mikkelbu** [comment] 2020-07-12 20:16
@OsirisTerje Just curious. Is there a reason for the difference in the number of total test in the image?

**Comment by OsirisTerje** [comment] 2020-07-12 20:36
@mikkelbu  Yes, it is the counting of the explicit test.  That is not included in the first, but in the second
