### ISSUE TITLE
OneTimeSetUp isn't executed in TFS

### ISSUE THREAD

**Issue by biiiipy** [nunit/nunit3-vs-adapter#98] opened 2015-12-09 10:50 UTC
In VS everything works fine, but in TFS build ```[OneTimeSetUp]``` isn't executed at all. Obsolete ```[TestFixtureSetUp]``` works fine though.
Using NUnit 3.0.1 and NUnit3TestAdapter 3.0.8-ctp-8

**Comment by rprouse** [comment] 2015-12-09 12:47
@biiiipy if the tests are running fine in VS and if `[TestFixtureSetup]` is running but `[OneTimeSetup]` is not under TFS, then TFS is not using the test adapter or the latest version of NUnit to run the tests. It is using either it's own test runner or a version of NUnit older than 2.6.4.

I would recommend running your tests in TFS by adding the `nunit.console` nuget package to the solution. This will cause `nunit3-console.exe` to be downloaded into the packages directory and you can then use it to run your tests on the command line.

I am closing this as not a bug for tracking purposes, but feel free to continue to comment on this issue and we will help you figure it out.

**Closed by rprouse** 2015-12-09 12:47 UTC
