### ISSUE TITLE
Can't install NUnit 3.8 Alpha 1 on VS2017: catalog missing 'Component'

### ISSUE THREAD

**Issue by jessejacob** [nunit/nunit3-vs-adapter#335] opened 2017-06-03 05:15 UTC
The install log contains:
```
6/3/2017 12:09:44 AM - 	Visual Studio Professional 2017
6/3/2017 12:09:44 AM - 
6/3/2017 12:09:45 AM - Beginning to install extension to Visual Studio Professional 2017...
6/3/2017 12:09:46 AM - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

And displays the message "The VSIX's catalog does not include a 'Component' which is required for install/uninstall." Installation works fine for 2012 and 2015 on the same machine, but 2017 fails. Any ideas?

**Comment by rprouse** [comment] 2017-06-06 00:22
I assume you downloaded from the GitHub release page since it is the only place we have released alpha 1? Can you tell me the exact version of Visual Studio 2017 you are running since there have been so many updates. 

I would also recommend using the NuGet package in 2017 since the VSIX does not (and can not) support .NET Core or .NET Standard.

**Comment by jessejacob** [comment] 2017-06-06 16:00
You assume correctly. My version is Visual Studio Pro 2017, 15.2 (26430.12) Release. We have a mix of core and non-core projects, and we're using the nugget package in 2017 for the core projects. I just thought the Visual Studio 2017 extension should be able to install and function for non-core projects. Thoughts?

**Comment by rprouse** [comment] 2017-06-06 16:40
It should install for non-core projects and I tested it with 15.0. Something may have changed since then. I will retest.

**Comment by OsirisTerje** [comment] 2017-07-14 19:43
No confirmation, so closing for now.  Will reopen if confirmed.

**Comment by OsirisTerje** [comment] 2017-07-15 20:16
I can confirm this one.  Got it now on testing the vsix for the 3.8.  That it also happens with 3.7 means this is probably caused by some changes in VS latest versions.   Checking with MS.

**Closed** 2017-07-19 20:10 UTC
Labels: closed:done, is:bug
