### ISSUE TITLE
VSIX no longer visible in Visual Studio 2012

### ISSUE THREAD

**Issue by ssrmm** [nunit/nunit3-vs-adapter#260] opened 2016-11-09 14:01 UTC
I'm unable to find the extension in the Visual Studio Gallery when using VS 2012. Searching for "nunit 3 test adapter" yields no results, while it does in VS 2015. Additionally VS never showed me an update for the installed version either.

As far as I can tell this is specific to version 3.5.1 (3.5.0 was installed through the gallery if I remember correctly).

Interestingly enough I could still install the extension by downloading the vsix manually.

**Comment by rprouse** [comment] 2016-11-12 21:33
We are currently testing an update, so will try to confirm this when we test in 2012.

**Comment by ssrmm** [comment] 2016-12-04 16:40
I finally remembered checking this on the machine where I have VS 2013 installed. Turns out VS 2013 Gallery doesn't find the VSIX either.

For reference, here are the exact Visual Studio Versions with which I encounter this:

```
Microsoft Visual Studio Ultimate 2013
Version 12.0.40629.00 Update 5

Microsoft Visual Studio Premium 2012
Version 11.0.61219.00 Update 5
```

**Comment by CharliePoole** [comment] 2016-12-04 17:36
Seems like we confirmed that this happens to some people, with some installations, and decided offline that we would specify each sku in the vsix as a possible solution. We can't confirm this will work for everyone unless we upload it first. Any reason not to do that?

@OsirisTerje Are you working on this? If not I'll upload something.

Based on my understanding, I'm relabeling this. If I'm wrong, let me know!

**Comment by OsirisTerje** [comment] 2016-12-04 20:54
@CharliePoole Can't see any reason not to, and no, not working on it.  It has to be done i VS 2017 RC though.

**Comment by CharliePoole** [comment] 2016-12-04 21:10
Ah! I forgot that. I'm still not set up on VS2017 - too many other things backlogged.

**Comment by CharliePoole** [comment] 2016-12-04 21:11
It does seem like a critical thing to me, if people can't install!

**Comment by OsirisTerje** [comment] 2016-12-04 21:45
I'll add it tomorrow.

**Comment by CharliePoole** [comment] 2016-12-06 03:00
I'm closing this since we released the vsix for 3.6.1. There doesn't seem to be a PR linked to it.

**Closed by CharliePoole** 2016-12-06 03:00 UTC
Labels: is:bug, pri:critical

**Comment by ssrmm** [comment] 2016-12-06 19:46
:+1: I can confirm that 3.6.1 shows up in both my 2012 and 2013 installation.

**Comment by CharliePoole** [comment] 2016-12-06 21:13
Thans @ssrmm we're a bit in the dark because none of us had ever seen the problem! I have a suspicion that it only shows up if you don't __also__ have VS2015 or VS2017 installed. Can you confirm that was your case? 

Anyway, it's good to know it's fixed. :smile:

**Comment by ssrmm** [comment] 2016-12-07 08:10
One machine has 2012 Premium and 2015 Enterprise installed, while the other has 2010 Ultimate alongside 2013 Ultimate. So it doesn't seem to be the reason, at least not exclusively. Eventually the SKUs must be the same as well...
