### ISSUE TITLE
No tests found to run when TestFixture contains ValueSource

### ISSUE THREAD

**Issue by jonnydatester** [nunit/nunit3-vs-adapter#277] opened 2016-12-05 20:25 UTC
I have several tests which use different types of value sources. For the most part the Test Adapter recognizes them. However, there are some cases like below which when I build the solution it does not recognize the test. Displays "No tests found" in the output and the tests do not display in the Test Explorer. Also, it won't load any tests in that test fixture where this is the case even if the other tests do not have the value source. 

It does recognize the tests from the command line and able to run there fine. Example below is where it does not work. Instead of using the GetNumberOfQueues method, if I just do something like "private static IEnumerable<string> queueNumbers = new string[] { "1", "2", "3" }" it works fine.

I am using the current version of Test Adapter (3.6). 

            [TestFixture]
            public class WindowsServicesTests
            {
                 private static IEnumerable<string> queueNumbers = GetNumberOfQueues();
        
                 [Test]
                 public void CheckQueuingServiceRunning([ValueSource("queueNumbers")] string queueNumber)
                 {
                      string queuingService = string.Format("AssureRx.{0}.Queuing.Service{1}", this.environment,       queueNumber);
                      Assert.True(WindowsServices.IsServiceRunning(this.machineName, queuingService), string.Format("{0} is not running on {1}", queuingService, this.machineName));
                 }

                 private static IEnumerable<string> GetNumberOfQueues()
                 {
                      using (var db = new Database(EnvironmentValues.GetValue("DatabaseConnectionString")))
                      {
                          int numberOfServices = Convert.ToInt32(db.RunQuery("SELECT TOP 1 ModuloDivisor FROM QueueService").Tables[0].Rows[0][0].ToString());
                          return Enumerable.Range(1, numberOfServices).Select(x => x.ToString());
                      }
                 }
            }

**Comment by CharliePoole** [comment] 2016-12-05 20:31
What version of the NUnit framework are you using?

**Comment by jonnydatester** [comment] 2016-12-05 20:32
I am using NUnit 3.5.

**Comment by CharliePoole** [comment] 2016-12-05 20:35
The problem is that queueNumbers is a static field that has no references to it. There is nothing to tell the compiler when it needs to be initialized or even that it needs to be initialized. The ValueSource, of  course, is not a reference since it merely uses the string representation of the name. If you change your ValueSource to use "GetNumberOfQueues" I believe that will fix it.

**Comment by jonnydatester** [comment] 2016-12-05 21:12
I tried that and it did not work. If I remove the using statement in the GetNumberOfQueues method and replace it with "return new string[] { "1", "2", "3" };" it pulls from the method just fine and displays the 3 tests in the Test Explorer. It seems to be something specific with the connecting to the database. 

Also have the same problem when trying to get the data from a spreadsheet: 
private static IEnumerable<string> datasheetClinics = new Datasheet("ExcelData/Order Forms.xlsx", "Clinics").Select(x => x["Clinic"]);

**Comment by OsirisTerje** [comment] 2016-12-07 00:01
This doesn't seem to point to any error in ValueSource.  As you @jonnydatester say it is probably more related to your database connection.   Suggest you add a simple test for the GetNumberOfQueues method to see that is actually returns anything.  
I'll close this.

**Closed by OsirisTerje** 2016-12-07 00:01 UTC

**Comment by jonnydatester** [comment] 2016-12-07 17:17
Using the 2.6.4 framework, I installed the Test Adapter 2.0 version and it works correctly as can be seen below. It is using the same code including the static variable. There must be something with the 3.6 version of the Test Adapter.

![image](https://cloud.githubusercontent.com/assets/13220666/20978474/05a35b30-bc77-11e6-81ec-6fead25e2a82.png)

**Comment by CharliePoole** [comment] 2016-12-07 17:35
@jonnydatester Have you tried to run this under the NUnit 3 console runner? If there is a problem, it seems unlikely for it to be in the VS adapter, since that's not the code that actually creates the test cases. In NUnit 3 that code lives in the framework.

**Comment by jonnydatester** [comment] 2016-12-09 20:53
After some digging, I figured out what the cause is. We have .xlsx and .xml files that are used for the ValueSource. These files live in the same directory as the Tests.dll lives. The TestAdapter isn't looking for those files. If I put a break point and get current directory when the test runs, it shows "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE". I tried to put the files there but still doesn't recognize. 

The same problem is happening when running the console runner. If I move the files where the exe is run (\packages\NUnit.ConsoleRunner.3.5.0\tools) it recognizes the tests fine. However, that is not a good way to handle that as we have a lot of different branches/builds and that can mess things up.

Unless you can think of something else, we will move away from non-cs files for the value source and put them in cs files.

**Comment by rprouse** [comment] 2016-12-09 21:59
@jonnydatester rather than refactor your tests too much, switch the opening of your files from a relative path to an absolute one. Something like the following,

```C#
var workingDirectory = Path.GetDirectoryName(Assembly.GetAssembly(typeof(MyTestClass))?.Location);
var xlsxFile = Path.Combine(workingDirectory, "MyData.xlsx");
```

**Comment by jonnydatester** [comment] 2016-12-12 17:37
@rprouse that worked for getting the tests to be recognized when using the command line for the console runner. However, it is not being recognized by the Test Adapter for some reason. Even if I hard code the path where the files exist the Test Adapter will not recognize the tests. For now, we will have to run those tests (only a handful) using the command line.

**Comment by CharliePoole** [comment] 2016-12-12 18:45
@jonnydatester It's a well-known change in NUNit 3 (documented on the Breaking Changes page of the docs) that NUnit no longer changes the current directory to match the location of your test assembly. That sort of thing can't work in an environment where you may be running multiple assemblies, from different directories, in parallel. As suggested on that page, you should use TestContext.TestDirectory to return the directory where your test assembly is located. Alternatively, you can figure out the location yourself using code like that suggested by @rprouse.

If you would like to have this issue re-opened and looked at again, please provide us with a simple repro case that doesn't require use of your database.

**Comment by jonnydatester** [comment] 2016-12-12 19:01
@rprouse After some more digging, it looks like the Test Adapter is running in 32-bit mode instead of 64-bit and that is why it is failing. If I try to run another test that loads spreadsheets get error: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine. We have had this problem in the past in TeamCity but it was because the runner was running in 32-bit. Is there an option in the Test Adapter to run in 64-bit mode?

**Comment by CharliePoole** [comment] 2016-12-12 19:36
@jonnydatester Visual Studio decides whether to launch a 64-bit or a 32-bit process for your tests. The nunit adapter simply runs the way that VS runs it. Usually, it will run in 64-bit mode if you have targeted 64-bit or Any CPU for your assembly. You can also force it to use 64-bit by using a `.runsettings` file with `<TargetPlatform>x64</TargetPlatform>` in it.

**Comment by jonnydatester** [comment] 2016-12-13 16:34
@CharliePoole  So I didn't realize that this can be set from the Test menu. I was able to go to Test-->Test Settings-->Default Processor Architecture-->x64. Now all tests are loading in the Test Adapter and I am good to go. Thanks for all your help!
