### ISSUE TITLE
NUnit 3 Test Adapter ignores first 100 tests

### ISSUE THREAD

**Issue by MuhKuh7** [nunit/nunit3-vs-adapter#91] opened 2015-12-01 16:06 UTC
The Test Adapter worked perfectly while I had < 100 tests in my projects. But the minute I added test 100 it failed to execute them. I added more tests and it seems to just execute randomly selected n-100 tests. (It selects always the same n-100, but the selection has no visible logic)

There is no error, it just does not execute them.

```
------ Discover test started ------
NUnit Adapter 3.0.7.0 discovering tests is started
NUnit Adapter 3.0.7.0 discovering test is finished
========== Discover test finished: 107 found (0:00:00.3330333) ==========
------ Run test started ------
NUnit Adapter 3.0.7.0 executing tests is started
Running all tests in D:\Development\MyApp\Data\bin\Debug\MyApp.Data.dll
Loading tests from D:\Development\MyApp\Data\bin\Debug\MyApp.Data.dll
NUnit Adapter 3.0.7.0 executing tests is finished
========== Run test finished: 7 run (0:00:04.1584158) ==========
```

The nunit3-console.exe however executes them all:
```
Test Run Summary
    Overall result: Passed
   Tests run: 107, Passed: 107, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-12-01 15:55:02Z
    End time: 2015-12-01 15:55:03Z
    Duration: 0.501 seconds
```

**Comment by CharliePoole** [comment] 2015-12-01 18:18
Two possibilities here:

* It's really skipping 100 tests. That would be really strange indeed, but possible. In fact, my own test demo that I use for checking out the adapter has less than 100 tests! It seems odd that nobody reported this before, however. Do you know if it worked before 3.0.7?

* One of your tests is causing the adapter to silently stop running tests. Of course, that would be a bug too, but a different kind of bug. You can check this easily enough. Comment out half your tests. Do the remaining tests run? Then uncomment those and comment out the other half. What happens?

I'll start by adding tests to my own test demo.

**Comment by MuhKuh7** [comment] 2015-12-01 23:53
I cannot test right now, but when I used "Run selected tests" on the group header of all 107 tests, all 107 were executed. Just when using "Run all" it did not work. I can try commenting out tomorrow.

**Comment by CharliePoole** [comment] 2015-12-02 00:42
I took our NUnit3TestDemo program and copied the file SimpleTests.cs three times, renaming the files and class. This gave me 115 tests in the suite, most of which do nothing.

I ran tests using both CTP-7b (the last release) and the about-to-be-released CTP-8, which incorporates NUnit 3.0.1. All tests ran whether I used Run All or Run selected tests.

My conclusion is that the issue is either in your install or in one or more of your tests rather than in the adapter. I suggest waiting for NUnit 3.0.1 to be released along with CTP-8. This should be tonight. Then make sure you have removed any old NUnit code and are only using the new bits. If that doesn't solve your problem, we can discuss on the mail list or repoen this issue, which I am closing for now.

**Closed by CharliePoole** 2015-12-02 00:42 UTC
Labels: status:confirm

**Comment by MuhKuh7** [comment] 2015-12-02 09:39
- I tried commenting out one half of the tests, but either way, all tests run as long as the total count is less than 100
- Updating to NUnit 3.0.1 does not help
- I reinstalled the test adapter from Visual Studio Gallery, but it did not help as well

What do you mean with "make sure you have removed any old NUnit code"?
- I only use Assert.AreEqual, Assert.IsNull, Assert.IsEmpty and Assert.Throws
- My tests either use [Test] or [TestCase(...)], most actually TestCase

**Comment by rprouse** [comment] 2015-12-02 11:51
How are you running the tests in Visual Studio? You said Run All, but I wanted to confirm. Can you also try the other ways?

1. Click the Run All link in Test Explorer? 
2. Group by project and run the project? 
3. The menu Test | Run | All Tests?
4. Ctrl R + A?
5. One of the many other ways you can run tests in VS? :smile: 

We need to figure out a way to reproduce this in order to verify and fix this.

What version of Visual Studio are you using? There might be a version specific bug.

Did you install the adapter from NuGet or from the Extension Gallery?

Is there anything special about your tests? For example, are there lots of TestCases or do you use TestCaseSource?

**Comment by CharliePoole** [comment] 2015-12-02 11:56
You are not using the 3.0.1 engine yet. We will release ctp-8 of the
adapter, which uses it today.

**Comment by MuhKuh7** [comment] 2015-12-02 12:46
@CharliePoole: Then I misunderstood, sorry. Will try the ctp-8.

**Comment by OsirisTerje** [comment] 2015-12-02 21:32
I tried this with the 3.0.7 adapter, and the test program at https://github.com/OsirisTerje/NUnit.TestPrograms  which contains a solution with 14000 NUnit tests and it runs as it should.  You should see both success tests and failed tests, but no ignored tests, and all should run. 
Can you try the same solution (It is in the TestNUnitMultipleTest folder) and see if that works on your machine ?

**Comment by MuhKuh7** [comment] 2015-12-02 22:35
@OsirisTerje, all tests are running with 3.0.7

@CharliePoole, I updated to 3.0.8, but unfortunately I still have the same issue.

I am still trying to figure out what is special about those tests. Running any group of tests always works. So if I group by project and run the group, all 115 tests in my project run. Using "Run All" (in any way I found in VS) only 15 tests are executed.

**Comment by CharliePoole** [comment] 2015-12-02 22:43
@MuhKuh7 OK... now you have me confused. You are saying that the problem only exists with 3.0.8, not with 3.0.7. Right?

However, I only issued the 3.0.8 update a few hours ago and your original post from yesterday shows that you are having the failure with 3.0.7. Can you verify what is the exact situation?

The fact that running a group of tests works makes some sense because VS calls an entirely different interface method in the adapter for Run All. I'll look to see if there is anything obvious in that method, which might cause such a problem and which is not in the other method!

Have you been able to create this problem using any tests other than your own?

**Comment by MuhKuh7** [comment] 2015-12-02 22:47
Sorry for the confusion. The statement about the working 3.0.7 was regarding the test solution from @OsirisTerje 

My solution shows the bug in 3.0.7 and 3.0.8

So it seems it is something about my tests.

**Comment by CharliePoole** [comment] 2015-12-02 22:53
But possibly something about your tests that NUnit should deal with more correctly! If we can find what that is, we can re-open this issue.

**Comment by MuhKuh7** [comment] 2015-12-02 22:54
Is there any way for me to actually debug the adapter?

**Comment by CharliePoole** [comment] 2015-12-02 23:07
You would have to build it. Also, if you have not previously debugged VS extensions, you will find it somewhat of a different experience from normal debugging. :-)

**Comment by MuhKuh7** [comment] 2015-12-03 13:45
I just realized that MS released Update 1 to Visual Studio 2015 3 days ago. With Update 1 installed, the Test Adapter now works.

**Comment by CharliePoole** [comment] 2015-12-03 14:01
@MuhKuh7 That's great. We all learned something!
