### ISSUE TITLE
Test Explorer is finding tests, but not running them after upgrading to NUnit3TestAdapter v4.3.0

### ISSUE THREAD

**Issue by Guitrum** [nunit/nunit3-vs-adapter#1027] opened 2022-11-02 05:23 UTC
NUnit: v3.13.3
NUnit3TestAdapter: v4.3.0
Visual Studio Professional 2019: v16.11.20
Target Framework Version: v4.5

I'm running Visual Studio Professional 2019 and have many NUnit tests in my project. With v4.2.1 of the NUnit3TesetAdapter installed, the Test Explorer is able to find and run all my tests [as expected](https://i.imgur.com/yhn9vIK.jpg).

However, a few days ago I updated my NUnit3TestAdapter nuget package from 4.2.1 to 4.3.0 and now my Test Explorer does not run any of the tests. It throws no errors and has [no problem finding/displaying the tests](https://i.imgur.com/CmH6H7j.jpg), but whenever I try to run them, it says:

`Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 172.1 ms`

I can confirm that rolling back to 4.2.1, cleaning, and rebuilding the project fixes the problem so maybe the issue is a bug in the 4.3.0 package, however I wanted to check if there is any configuration I need to do in Visual Studio to fix this.

**Comment by OsirisTerje** [comment] 2022-11-02 07:43
Hi @Guitrum !

It sounds interesting.  
You should not need to change any settings, but I see you state you run net4.5.   Can you please create a very small repro of this, with the same configuration and please include whatever (if any) runsettings file you use.

**Comment by smkanadl** [comment] 2022-11-02 10:18
I have a similar issue with some interesting Test log output:

> Test project *** does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
NUnit Adapter 4.3.0.0: Test discovery starting
**Exception System.UnauthorizedAccessException, Exception thrown discovering tests in** ******.dll
Access to the path 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\InternalTrace.30660.log' is denied.**
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NUnit.Engine.Internal.InternalTraceWriter..ctor(String logPath)
   at NUnit.Engine.Internal.InternalTrace.Initialize(String logName, InternalTraceLevel level)
   at NUnit.Engine.TestEngine.Initialize()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestDiscoverer.cs:line 82
NUnit Adapter 4.3.0.0: Test discovery complete
No test is available in ***.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

The test project is a multi-targeted C# project with net48, netcoreapp3.1 and net6.0.
Executing the test for netcoreapp3.1 and net6.0 works fine.

**Comment by OsirisTerje** [comment] 2022-11-02 10:22
@smkanadl Yes, it seems like the same issue.  Can you create a simple repro project, I think all that is needed is a net48 project ?

**Comment by smkanadl** [comment] 2022-11-02 10:36
@OsirisTerje It seems to be surprisingly hard to reproduce in a simple repo. What I managed to create is an example of the test adapter creating `InternalTrace.29640.log` like files in the `src` of the repository. In the more complex case they are somehow created in the write-protected installation directory. But, at least in my case, the issue is that those (empty) files are created at all. And they are only created for full framework target.s

https://github.com/smkanadl/nunit-test-adapter-issue

**Comment by OsirisTerje** [comment] 2022-11-02 10:41
@smkanadl Your experience equals mine.  I can't reproduce the write-protected directory.  That's why I am asking everyone for a repro :-)  

The other issue with the empty logfiles is known (https://github.com/nunit/nunit-console/issues/1178) and will be included in NUnit.Engine 3.16, ETA sometime this November.

**Comment by smkanadl** [comment] 2022-11-02 10:52
I'll try harder, but cannot promise anything ;-). I'll update the repo and let you know if it was successful. It's a very strange issue because the only difference between the actually affected project and the minimal repo is the amount of projects and code included. No runsettings or other test execution specific setup.

**Comment by OsirisTerje** [comment] 2022-11-02 11:11
I added the following code to your test to see what it is:
```cs
       var d = Environment.CurrentDirectory;
       TestContext.WriteLine($"Current directory : {d}");
```

It is also strange that the logfiles go to the solution root folder, and not the binary work folder.  The latter is what happens in my repro, and is the expected result using the defaults.

**Comment by OsirisTerje** [comment] 2022-11-02 11:15
@CharliePoole The logfiles go to the solution root folder **ONLY** for the net48 target, for the net6 and netcore31 they go to the expected binary folder.

**Comment by OsirisTerje** [comment] 2022-11-02 11:19
@smkanadl I don't think your rerouting causes any issue here, it doesn't separate between targets afaic see.   

(PS: Not sure why you do that, since they are not included with git, nor show up in VS, but if you like it that way :-) )

**Comment by smkanadl** [comment] 2022-11-02 11:35
@OsirisTerje simply reason for that. There are days, where things simply go wrong and you have to delete the build artifacts. In a project with > 50 projects I find it very convenient so delete the `build` directory in a single place without having to fear to loose any changes to the code :-)

Can you pull from my example repo and check the test output, please. At least locally I managed to reproduce the write-protected directory error. To my VERY surprise, it is an `InternalsVisibleToAttribute` that seems to cause the trouble.

**Comment by OsirisTerje** [comment] 2022-11-02 11:53
Pulled now, but latest commit is #455072f  time 11:33

**Comment by smkanadl** [comment] 2022-11-02 11:55
@OsirisTerje Sorry, stupid me. Forgot to push... Now it is pushed!

**Comment by OsirisTerje** [comment] 2022-11-02 13:19
I don't get any such error.
Where is the InternalsVisibleAttribute ?

Sure you committed and pushed everything ?

**Comment by smkanadl** [comment] 2022-11-02 15:10
The attribute is embedded by convention from the `Directory.Build.props`. But you are right. I tested it on a different machine and it all ran the net48 test case. And also after a fresh checkout on my machine it ran fine again. This is giving me a severe headache!

**Comment by OsirisTerje** [comment] 2022-11-02 15:50
@smkanadl  That was an interesting find!   @Guitrum and @janid1967 Can you check this on your systems?

**Comment by Guitrum** [comment] 2022-11-02 16:00
> @smkanadl That was an interesting find! @Guitrum and @janid1967 Can you check this on your systems?

@OsirisTerje as much as I wished the fix was something as simple as that, it does not look like it worked for me. I tried twice to delete the .vs folder, also with deleting all bin/obj folders before rebuilding. Still not getting any of the tests to run

**Comment by OsirisTerje** [comment] 2022-11-02 16:07
@Guitrum Are you able to provide a repro?

**Comment by Guitrum** [comment] 2022-11-02 16:14
> @Guitrum Are you able to provide a repro?

How best would I go about that?

**Comment by smkanadl** [comment] 2022-11-02 16:20
> > @smkanadl That was an interesting find! @Guitrum and @janid1967 Can you check this on your systems?
> 
> @OsirisTerje as much as I wished the fix was something as simple as that, it does not look like it worked for me. I tried twice to delete the .vs folder, also with deleting all bin/obj folders before rebuilding. Still not getting any of the tests to run

Maybe it helped in my case as I was affected by #987.

**Comment by Guitrum** [comment] 2022-11-02 17:24
@OsirisTerje I did fire up my other computer which also has Visual Studio Professional 2019 v16.11.20 on it. I pulled latest from my repo and was able to reproduce the same problem exists there too

**Comment by OsirisTerje** [comment] 2022-11-02 20:20
@Guitrum Can you just create a single test project with a single test, using the same configuration as for your main project. If that works, then add small pieces of stuff similar to your main project that you suspect.  Take a look at https://github.com/smkanadl/nunit-test-adapter-issue where @smkanadl have made a small repro for the same.

**Comment by smkanadl** [comment] 2022-11-02 20:29
I still haven't managed to make it reproducible. Whenever I think I have found something, a clean checkout will just work :-/

**Comment by OsirisTerje** [comment] 2022-11-02 20:42
@smkanadl It might be something that is left over from something, so when it fails, perhaps could just zip together the whole workspace, including the binaries and everything and upload that.  Even if this is then not exactly the adapter that is at fault, if we found stuff that should not be there, we could do a check for that and raise a more specific warning or error.

**Comment by Guitrum** [comment] 2022-11-02 21:34
@OsirisTerje I was working on stripping my solution down to as basic as I could get it to try to repro the issue and somehow got the tests to run with 4.3.0! I went back to my original solution, cleaned, and rebuilt and now it's working there as well!

I wish I knew what was changed but at this point I have no idea. I'll keep poking around to see if the problem resurfaces, but it's looking like it has fixed itself for me

**Comment by Guitrum** [comment] 2022-11-03 02:37
@OsirisTerje are you aware if InternalTrace.###.log files are used by the test adapter in any way? I'm noticing that each time I initiate a test run, one of these .log files gets placed in my root project folder which definitely shouldn't be happening

**Comment by OsirisTerje** [comment] 2022-11-03 08:05
@Guitrum Yes, we're aware of those.  They appears only for netframework, not net core. All of those that are zero size will go away on next release of the engine.  Otherwise we need to find why they go there and not in the bin folder. But it is an engine issue.

**Comment by CharliePoole** [comment] 2022-11-03 08:38
The fact that the log files only appear for net framework is new to me. Because the net core build of the engine doesn't support running out of process, much of the initialization code is different, using conditional compilation. I'll take a look at the places where the code differs to see what I can find.

**Comment by CharliePoole** [comment] 2022-11-03 08:40
@OsirisTerje Have you tried building using one of the dev builds from myget? The most recent 3.16.0-devxxxxx would be the one to try.

**Comment by OsirisTerje** [comment] 2022-11-03 09:48
@CharliePoole I'll do that

**Comment by Quogu** [comment] 2022-11-08 16:33
I'm having the same issue as @Guitrum describes, with a fairly similar setup.

NUnit: v3.13.3
NUnit3TestAdapter: v4.3.0
Visual Studio Professional 2022: v17.3.6
Target Framework Version: v4.7.2

I managed to trigger this on a very simple repro solution - [NUnitVSAdapterRepro.zip](https://github.com/nunit/nunit3-vs-adapter/files/9962951/NUnitVSAdapterRepro.zip) - but after closing and opening Visual Studio it then started working again as normal.

Given the log that @smkanadl and I both got from the Tests Output window that they posted in https://github.com/nunit/nunit3-vs-adapter/issues/1027#issuecomment-1299991747 , I figured that it was to do with the current working directory of VS itself, so I made sure to launch it the same way (the default start menu shortcut for VS2022 opens the IDE in the `C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\` directory which is consistent with the logs referenced above). However, despite closing and reopening it maybe 20-30 times, I managed to get it to fail once more only, with every other try working successfully.

Recreating the same repro did not reproduce the issue either, nor can I now reproduce the issue on the work project that I hit the issue on originally, so I can only determine that the issue is nondeterministic, and that the majority of the time VS decides to change its working directory to the solution directory (evidenced by the output of the snippet of code provided by @OsirisTerje in https://github.com/nunit/nunit3-vs-adapter/issues/1027#issuecomment-1300084065 ), but _sometimes_ it leaves it unset and then test discovery fails.

All that being said, I'm still unsure why test discovery fails even when the CWD is not changed to the solution directory - the code in https://github.com/nunit/nunit3-vs-adapter/blob/V4.3.0/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs#L137 suggests that this should be being picked up - the `ProgramW6432` environment variable is set to `C:\Program Files`, so the check at https://github.com/nunit/nunit3-vs-adapter/blob/V4.3.0/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs#L176 should catch this and set the CWD to a temporary directory inside the NUnit adapter code. I didn't see any way of debugging the test discovery from within Visual Studio either. I'd be tempted to add more logging there to try and catch this issue myself.

I hope this helps, though I doubt it'll bring you any joy that the issue seems nondeterministic. :(

**Comment by OsirisTerje** [comment] 2022-11-08 17:38
@Quogu Thanks!    First, all access to Program files folders should be caught, as you found.  Interesting (and scary) that doesn't happen fully, but I believe it might be because this happens before the WorkDirectory is being set.  The logging happens first when the engine is created and we request the filterservice, and at that time the directory has not been set.  Then the workdirectory is set when the test package is created, and that one should go fine.  So, from what you write, I would assume it is the first one that hits the fan.  That is also what is consistent with my own debugging.

About debugging, it is rather trivial to do so, the adapter has a runsettings for just that, but best is to read this post, where everything should be explained, I hope:  https://github.com/OsirisTerje/osiristerje.github.io/blob/master/Debugging-the-NUnit3TestAdapter-Take2.md

**Comment by OsirisTerje** [comment] 2022-11-08 17:47
The plan going forward is to set the CWD just before the call to get the filterservice to the temp directory, with a NUnit.Engine.Log folder beneath that.  If the workdirectory is not explicitly set, then setting it to the same as the binary directory for the test run.  The first setting happens before any assemblies have been selected, so we can't set it any other place than some temp folder.  The second setting - then we know which assembly we're working on, so we can set it to that executable folder.

**Comment by CharliePoole** [comment] 2022-11-08 18:46
In addition, I suggest setting the engine `WorkDirectory` property to some safe value immediately upon creating the instance. Otherwise, you would be relying on the engine never trying to write any trace entries until you create a runner, which is not actually the case. In fact, there are other calls you could make to the engine (which you don't now use) that could result in a log entry being written. I'd also turn off the tracing at that point as well as a sort of "belt and suspenders" approach.

**Comment by OsirisTerje** [comment] 2022-11-08 19:44
@CharliePoole 
1. I see there are a valid InternalTraceLevel of Default.  What is that the equivalent of?
2. On engine init, you write "turn tracelevel off".  You mean it should not be controlled by any options, just hardcoded off?  There is nothing of interest between that point and when the packages run?

**Comment by CharliePoole** [comment] 2022-11-08 19:54
`Default` is used to indicate that you haven't set the level. There's no need to set it to Default as that is what you get when you don't set it. Some runners may use it to mean `Error`. The engine interprets it as `Off`.

The setting you make using the properties is used for the trace _of the engine itself_. The settings you apply to the `TestPackage` are passed to the framework for its own use.

The engine writes trace entries independent of the running of tests. Since it could be changed at any time to write additional  entries, for example, as part of its own initialization, it is best to have everything set up even if your code doesn't do anything between the two points.

**Comment by OsirisTerje** [comment] 2022-11-08 20:28
Ok, I have currently one InternalTraceLevel property.  I could add another one for the testpackage,  or simply use the same for both and then set them accordingly to that.

> I'd also turn off the tracing at that point as well as a sort of "belt and suspenders" approach.
I just wondered because you said this above, but I'll then just use the value set, and use the default as Off in the adapter settings too.

**Comment by OsirisTerje** [comment] 2022-11-08 21:34
@Guitrum @smkanadl @Quogu This is work in progress, but would appreciate a test.  It should no longer crash, with the existing engine, so empty log files are still produced, but they are in either the temp folder or in the binary.  
If this is working as it should now, then I will add a later dev version of the engine tomorrow.

[NUnit3TestAdapter.4.3.1-alpha.111.zip](https://github.com/nunit/nunit3-vs-adapter/files/9965427/NUnit3TestAdapter.4.3.1-alpha.111.zip)

**Comment by smkanadl** [comment] 2022-11-09 10:48
@OsirisTerje Thank you very much! I managed to set my test repo in the bad state, upgraded the nuget package, rebuild and was able to run the tests - even without deleting any .vs or build folders. Awesome!

**Comment by evheniyrz** [comment] 2022-11-10 11:19
@OsirisTerje Greate.Thanks Its working - [NUnit3TestAdapter.4.3.1-alpha.111.zip](https://github.com/nunit/nunit3-vs-adapter/files/9965427/NUnit3TestAdapter.4.3.1-alpha.111.zip)

**Comment by ojintoad** [comment] 2022-11-11 21:20
I am here because I was experiencing a similar issue. tl;dr the alpha helps me also.

I started with TestAdapter 4.2.1. This ran well on VS2019 but failed on VS2022.
I then upgraded to TestAdapter 4.3.0. This ran well on VS2022 but failed on VS2019.
I then upgraded to the alpha attached here. Ran well on both.

The symptom was either inability to find tests or inability to run them if they were found.

**Comment by OsirisTerje** [comment] 2022-11-12 23:06
@ojintoad  Thanks, really appreciate the feedback!

**Comment by OsirisTerje** [comment] 2022-11-19 21:31
Released here https://www.nuget.org/packages/NUnit3TestAdapter/4.3.1

**Closed by OsirisTerje** 2022-11-19 21:31 UTC
Labels: is:bug, closed:done

**Comment by jzs11** [comment] 2023-06-13 04:06
Hi, the same problem is happening on VisualStudio 2022 17.6.2 and TestApapter v4.5.0 and when our code base targets to .net4.8.

If switch to .net7 everything is fine.

Thanks!

**Comment by HenrikMjaaland93** [comment] 2025-01-27 13:29
SOLUTION: install NUnit Test Adapter (NUnit3TestAdapter) NuGet package.
