### ISSUE TITLE
Visual Studio 2017 RC lightweight mode test explorer searches for tests indefinitely

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#269] opened 2016-11-16 20:28 UTC
If the NUnit test adapter extension is installed and not disabled, the Test Explorer window seems to search for tests indefinitely which prevents me from running or debugging any tests. Sometimes it discovers tests, sometimes not, but it never finishes. I made sure every project was fully loaded and built.

This issue only happens with lightweight loading on.

NUnit 3 Test Adapter version 3.6.0.0

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.25914.0 D15REL
Microsoft .NET Framework Version 4.6.01586

**Comment by rprouse** [comment] 2016-11-16 20:35
Are you using any `TestCaseSource` or similar data driven tests that might be long running during the discovery phase? Did these tests work in prior versions of Visual Studio or the NUnit adapter?

**Comment by jnm2** [comment] 2016-11-16 20:36
@rprouse Yes and yes.
I'm wrong, this issue only happens with lightweight loading on. It's just really slow to discover tests with lightweight loading off.

**Comment by rprouse** [comment] 2016-11-16 20:40
Thanks, we will need to look at that. The adapter code didn't change for VS 2017 though, only the VSIX package, so it might be a VS 2017 issue although I am not seeing issues locally.

**Comment by jnm2** [comment] 2016-11-16 20:45
If you can't repro I can try to share a POC.

**Comment by CharliePoole** [comment] 2016-11-16 20:51
I only just received some info about lightweight loading, which I'm forwarding to @rprouse

**Comment by rprouse** [comment] 2016-11-16 23:31
I have confirmed that this is the case, as far as I can tell, it is not a bug in our adapter, but in Visual Studio. I found the same behavior with an MSTest project.

To reproduce,

1. Turn on **Lightweight Solution Load** in **Tools | Options | General**
2. Collapse your test project in Solution Explorer
3. Close your solution, then reopen
4. Build, Rebuild, Run All Tests, whatever you select, no tests are discovered
5. Click on the project to expand it. it loads and tests are discovered

I was able to reproduce this with a solution with a single test project in it and with both NUnit and MSTest I will report to Microsoft.

**Comment by rprouse** [comment] 2016-11-16 23:42
Update, I have also confirmed with xUnit installed as a NuGet package, not a VSIX

**Comment by jnm2** [comment] 2016-11-17 03:23
You may be correct that it's a bug in VS2017, but I want to emphasize that the specific behavior I was seeing was that test discovery never completed. That's different than discovering or not discovering tests and completing the discovery.

**Comment by pvlakshm** [comment] 2016-11-17 10:40
The title says "searches for tests indefinitely" - that should not be the case.
When Lightweight Solution load is ON, Visual Studio test tools no longer discover tests in the loaded solution for any projects that are not loaded yet. Once the project is loaded, tests will be discovered as usual.

**Comment by jnm2** [comment] 2016-11-17 11:03
It's the searching indefinitely that's the problem because while searching, I can't run or debug tests.

**Comment by pvlakshm** [comment] 2016-11-17 12:37
Thanks. I have logged this as a bug. We will get this looked into.

**Comment by pvlakshm** [comment] 2016-11-23 04:33
In the latest builds we are unable to repro the case where it is searching indefinitely; however we do observe that it discovers 0 tests. That will be fixed in the next upcoming release.

**Comment by jnm2** [comment] 2016-11-23 12:51
@pvlakshm I updated to 15.0.25920.0 and see the same results you just mentioned. With lightweight solution load on, the searching indefinitely is no longer happening and 0 NUnit tests are discovered when I build the test project. A separate project that doesn't use NUnit does have its tests discovered.

**Comment by pvlakshm** [comment] 2016-11-30 11:12
We have a fix and it should be there in the next upcoming release.

**Comment by CharliePoole** [comment] 2016-12-25 16:21
Closing as not our bug.

**Closed by CharliePoole** 2016-12-25 16:21 UTC
Labels: blocked, is:bug, pri:normal

**Comment by MHanafy** [comment] 2017-12-05 03:45
Hi Guys,
Any news about this bug? It seems to not be fix in 15.4.5.

Thanks,
Mahmoud,

**Comment by WDurk1313** [comment] 2018-05-16 15:29
I have Visual Studio 2017 after 15.5 (i.e. 15.7.1) and I still experienced the endless search for tests (like a bad Beach Boys album).  I agree with the previous comment, about the lightweight system being deprecated, since I tried searching tools options for the key phrase "lightweight", and also "liteweight" and a few other things, but couldn't find any options.
So after trying a "switch to Release mode, clean, switch back to Debug mode, clean", which also DID NOT work, I did the following steps which seemed to do the trick:
1. close Visual Studio
2. start Task Manager, goto Process tab and sort by name
3. kill all the residual devenv.exe processes
   (feels good doesn't it?  but be careful not zealous)
4. kill all the residual msbuild.exe processes
5. kill all the residual Roslyn processes
 (I don't remember exactly but I think it was this name: ServiceHub.RoslynCodeAnalysisService32.exe)

Restart Visual Studio, load the solution and you should be fine.

NOTE: I tried it again just to make sure it was the correct Roslyn process, but this time after step 3, there were no processes to kill for steps 4 and 5.  Go figure!

**Comment by OsirisTerje** [comment] 2018-05-21 14:33
There should be significantly less of these now, but there can ofc still be some more.  They are not in the adapter though, but in vstest itself.  
What you need to kill is the test related process, I do the following:
TASKKILL /T /F /FI "IMAGENAME eq vstest.*"
TASKKILL /T /F /FI "IMAGENAME eq testhost.*"
