### ISSUE TITLE
Console.WriteLine() inside OneTimeSetUp does not write to console when running dotnet test

### ISSUE THREAD

**Issue by xuxiankun** [nunit/nunit3-vs-adapter#904] opened 2021-10-27 22:36 UTC
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions   
  NUnit Adapter 3.17.0.0
* Visual Studio edition and full version number (see Help About)  
  Microsoft Visual Studio Professional 2019 Version 16.11.5
* A short repro, preferably attached or pointing to a git repo or gist using System;
```
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;

namespace CollectionsAccountSummaryWorker.Tests.Integration
{
	[TestFixture]
	public class PrimeService_IsPrimeShould
	{

		[OneTimeSetUp]
		public void SetUp()
		{
			var t = Task.Run(() => ShowThreadInfo("Task"));
			t.ConfigureAwait(false).GetAwaiter().GetResult();
			Console.WriteLine("one time setup");


		}

		private void ShowThreadInfo(string s)
		{
			Console.WriteLine("{0} thread ID: {1}",
							  s, Thread.CurrentThread.ManagedThreadId);
		}
		[Test]
		public void IsPrime_InputIs1_ReturnFalse()
		{
			Console.WriteLine("IsPrime_InputIs1_ReturnFalse");
		}
	}
}
```

* What .net platform and version is being targeted
  .NET 3.1.414

**Comment by rprouse** [comment] 2021-10-30 02:14
Duplicate of the other issue you commented on?

**Comment by OsirisTerje** [comment] 2021-10-30 02:53
https://github.com/nunit/nunit3-vs-adapter/issues/266  Duplicate

**Closed by OsirisTerje** 2021-10-30 02:53 UTC
