### ISSUE TITLE
Inheriting test methods from abstract base test fixutures emits "No source data found for..." warning.

### ISSUE THREAD

**Issue by MSK61** [nunit/nunit3-vs-adapter#163] opened 2016-04-30 20:50 UTC
A couple of weeks ago I ran into a scenario that can be stripped down to something like this

    abstract class BaseFixture
    {
        [NUnit.Framework.Test]
        public void RunTest()
        {
        }
    }

    class DerivedTester : BaseFixture
    {
    }
So in essence, I'm deriving a class from an abstract test fixture that has a test method. The test adapter successfully recognizes a test method in the derived classed `DerivedTester`, but I get a message in the output window, Tests channel reading

    No source data found for InheritedTests.DerivedTester.RunTest
The above code was inside a namespace called `InheritedTests`, hence the namespace prefix. This symptom has been touched upon in nunit/nunit-vs-adapter#6 and nunit/nunit#1080, albeit while using generics somehow. My code here doesn't use generics; the message appeared all the same.

**Comment by rprouse** [comment] 2016-05-01 18:56
Does this work if you run the tests from NUnit console? I want to make sure this is an adapter issue and not a general framework issue.

**Comment by rprouse** [comment] 2016-05-01 19:02
This could be a duplicate or related to #1366

**Comment by MSK61** [comment] 2016-05-23 00:33
This isn't the first time to notice that some of my comments on a certain issue disappears on GitHub after I write it. I long ago(about 20 days ago) added a comment describing my findings with trying to run under visual studio adapter and the console runner. I'm repeating my results here as I don't know where the original comment went.

The test runs under both visual studio adapter and the console runner flawlessly. The message doesn't appear under the console runner but does appear in the output window when the test is run under visual studio; this reinforces the conjecture that it's indeed an adapter issue.

**Comment by CharliePoole** [comment] 2016-05-23 02:22
I hadn't looked at this issue before. 

It can only show up in the adapter, since only the adapter attempts to figure out where the test is defined. Source data means the file name and line number of the definition.

However, the adapter uses the class and method name supplied by NUnit in doing this. We will have to check what NUnit is providing. Just going by my memory, I believe that NUnit was providing the wrong class name in this case until we recently applied a fix. The version containing the fix, however, is not the one being used by the adapter. I'll try to confirm this.

**Comment by CharliePoole** [comment] 2016-05-31 20:03
I've confirmed the fix but also that the fix is not yet in a released version of NUnit. It will be in 3.4.

I simulated the fix in the debugger. Once it's actually in, the problem will be resolved without any changes to the adapter code.

However, since the fix is in the NUnit framework, the problem will continue to exist for any tests that use a framework version earlier than 3.4.

Next decision is whether to put in a conditional fix to apply when running against those versions.

**Closed** 2016-06-02 21:34 UTC
Labels: is:bug, pri:normal, status:started
