### ISSUE TITLE
[OneTimeSetUp] function output is missing(?)

### ISSUE THREAD

**Issue by anprabhu** [nunit/nunit3-vs-adapter#503] opened 2018-05-03 17:48 UTC
While running NUnit tests in VS2017, we have some console output in the OneTimeSetUp functions. I do not see this output in the test output, which makes sense. How can I get this output within VS?

**Comment by OsirisTerje** [comment] 2018-05-04 19:31
This is a duplicate of the currently open issue https://github.com/nunit/nunit3-vs-adapter/issues/266

**Closed by OsirisTerje** 2018-05-04 19:31 UTC
