### ISSUE TITLE
TestCaseSource tests get wrongly displayed

### ISSUE THREAD

**Issue by StarWars999123** [nunit/nunit3-vs-adapter#613] opened 2019-02-26 18:37 UTC
Hello, 
I am using NUnit 3.10.1 via Nuget and the TestAdapter 3.13.0.0 in VS 2017 Pro 15.9.3. I have the following test structure, that gets displayed wrongly in TestAdapter.

```
private static readonly object[] MyTestData={
     new object[]{"TestId1",  new [] {Tuple<int,byte[]>(0,new byte[]{0xFF,0x00})}},
     new object[]{"TestId2",  new [] {Tuple<int,byte[]>(5,new byte[]{0xAB,0xAB})}},
     new object[]{"TestId3",  new [] {Tuple<int,byte[]>(0,new byte[]{0xFF,0x00}), Tuple<int,byte[]>(5,new byte[]{0xAB,0xAB})}},

[Test]
[TestCaseSource(nameof(MyTestData))]
public void MyTest(string testName, Tuple<int, byte[]>[] varsToChange){
 // something that sets all programs variables given in varsToChange[i][0] to the value of varsToChange[i][1] 
}
```

The issue is that the tests get displayed wrongly in VS TestExplorer: 
##############
◢MyTest]) (2)
--MyTest("TestId1", [(0,System.Byte[])])
--MyTest("TestId2", [(5,System.Byte[])])
MyTest
MyTest("TestId3", [(0,System.Byte[])], [(5,System.Byte[])])
################
 What I would have expect is the following: 
##############
◢MyTest (3)
-MyTest("TestId1", [(0,System.Byte[])])
-MyTest("TestId2", [(5,System.Byte[])])
-MyTest("TestId3", [(0,System.Byte[])], [(5,System.Byte[])])
################
As you see, what I got differs to my expectation in the following points: 
- the ]) in line 1 should not exist, 
- the single MyTest that can not be executed and allways ends up blue
- TestId3 is not part of the list, but displayed seperate

I hope this supports you with everything you need to reproduce the issue. I am also not sure, whether this is not something, Microsoft needs to fix. In any way I would like to thank you in advance for your support.

**Comment by OsirisTerje** [comment] 2019-02-26 21:57
@StarWars999123  
1.  "the ]) in line 1 should not exist," :   Correct and interesting, haven't seen that before,, but bug is in the Test Explorer.  We don't control this one.  Suggest you raise this in the vstest repo, https://github.com/Microsoft/vstest 
2.  "the single MyTest that can not be executed and allways ends up blue":  IIRC this is a known error, you can raise it again in the vstest repo if you dont find it there. 

The MS guys should at least respond to the issue in vstest repo, althought the Test Explorer itself is not part of that repo, but close enough. 

3. "* TestId3 is not part of the list, but displayed seperate":   This is as expected, as the Test Explorer groups by FQN (Fully Qualified Name), and the 3rd item has a different signature.  This is by design in the Test Explorer.  Since you're using object[] you will get this result, there is no way for the Test Explorer to tell these apart any other way.  

Screenshot of my test:
![image](https://user-images.githubusercontent.com/203432/53449350-e4479280-3a19-11e9-8b1c-bec84c4b79a6.png)

**Comment by OsirisTerje** [comment] 2019-02-26 22:01
Included test project
[Issue613.zip](https://github.com/nunit/nunit3-vs-adapter/files/2907707/Issue613.zip)

**Comment by johnmwright** [comment] 2019-10-28 20:49
I believe this is due to the same underlying issues as #622 and resolved by PR https://github.com/nunit/nunit3-vs-adapter/pull/668

**Comment by OsirisTerje** [comment] 2019-11-01 19:59
Tested with 3.16.0-dev The exception is gone.  It works when using NUnit 3.12, but not when using NUnit 3.11.

**Closed by OsirisTerje** 2019-11-01 19:59 UTC
Labels: External, VS Issue, is:bug
