### ISSUE TITLE
Need to constantly terminate vstest.console.exe

### ISSUE THREAD

**Issue by grokky1** [nunit/nunit3-vs-adapter#352] opened 2017-07-05 18:26 UTC
I'm using the latest of everything (VS2017 15.2, NUnit 3, adapter 3.8.0-alpha1). Targeting .NET Core.

Sometimes the adapter works well. But most of the times, the green bar just carries on forever. It gets stuck in the test discovery phase, which triggers after each build.

So I terminate `vstest.console.exe`, and the `discoveryengine`  and `executionengine`. Then the adapter stops working. Then I build, and it starts again, and works. But the next time I build, it goes into a loop again!

So frustrating. Any recommendations?

(Actually I'm not sure which of the three processes I need to terminate to get it working again, so I terminate all three each time. Maybe the problem is not in `vstest.console.exe` but in one of the other two, I don't know.)

**Comment by OsirisTerje** [comment] 2017-07-05 19:21
Yes, I have seen the same issue, but I believe this is caused by VS and not the adapter.   We have an issue with MS about this.

**Comment by grokky1** [comment] 2017-07-05 19:31
So it's not just me!

What I've done is made a small bat file which terminates all those three processes. I've stuck it onto my taskbar for quick access.

**Comment by OsirisTerje** [comment] 2017-07-05 19:59
I have notified MS of your confirmation (of the issue I have reported before).  I also terminates the TE.Processhost, and sometimes I have to restart VS. 
Just to check, are you using the latest VS (15.2.26430.14) ?

**Comment by OsirisTerje** [comment] 2017-07-05 20:13
I found the issue already reported, https://developercommunity.visualstudio.com/content/problem/65159/test-explorer-intermittently-never-finishes-findin.html.
Then feel free to upvote it, to show more people have this issue.

**Comment by grokky1** [comment] 2017-07-05 21:19
Yep wildcards is a better idea. Thanks for the post, I'll upvote as you suggest.

**Comment by smadala** [comment] 2017-07-12 14:00
@grokky1 For .Net core test projects killing vstest.console.exe will be sufficient. 
Please share logs requested at https://developercommunity.visualstudio.com/comments/76957/view.html, Those will help in RCA.

**Comment by grokky1** [comment] 2017-07-12 14:20
@smadala The problem is that it is not easily reproducible. I don't know when it'll happen, that's what so strange. If I could setup a obvious failing test case, I could send logs.

**Comment by OsirisTerje** [comment] 2018-02-02 18:56
It now seems to happen less often.  When it happens, I have to run the following kill commands:
```

TASKKILL /T /F /FI "IMAGENAME eq vstest.*"
TASKKILL /T /F /FI "IMAGENAME eq testhost.*"
```

I'll close this now, since this is vstest/host related, and not NUnit.

**Closed by OsirisTerje** 2018-02-02 18:56 UTC
Labels: blocked or VS Issue
