### ISSUE TITLE
Console output doesn't seem to show up in Tests output window on failed tests

### ISSUE THREAD

**Issue by andrewescutia** [nunit/nunit3-vs-adapter#728] opened 2020-03-12 23:10 UTC
* NUnit 3.12.0 NUnit3TestAdapter 3.15.1
* Visual Studio 2019 - 16.4.5

Similar to this older issue: https://github.com/nunit/nunit3-vs-adapter/issues/95

I am seeing the option to "Open additional output for this result" as well as the Test Output window that when clicked displays my console logs.  But I do not get this option on failed tests.  This console output on failures would be beneficial to troubleshooting the failure.

**Comment by OsirisTerje** [comment] 2020-03-16 21:35
Is this a duplicate of #343 ?   Can you please check the latest dev version at myget ?

**Closed** 2020-06-08 13:28 UTC
Labels: confirm
