### ISSUE TITLE
If a test writes to Console.Error, the test passes but the session fails

### ISSUE THREAD

**Issue by simmdan** [nunit/nunit3-vs-adapter#204] opened 2016-07-13 01:11 UTC
I have a change to my project going which includes upgrading from nunit 3.2.0 and vs-adapter 3.2.0 to nunit 3.4.1 and vs-adapter 3.4.0.  When I first made the upgrade I discovered that my test runs were reporting that all the tests had passed but the overall run had failed.  To make matters worse equivalent runs using nunit3-console or resharper's test runner did not fail.

After significant investigation I discovered that some of my tests were writing strings to Console.Error and that if I quit that, then the test sessions would pass.

Next I had a look at some of the code changes to the vs adapter between its 3.2.0 and 3.4.0 releases and came across the commit addressing issue #196.  I'm suspicious that when data is passed from Console.Error to _recorder.SendMessage with TestMessageLevel.Error VS is responding by failing the session.

I have not yet been able to take the time to setup my environment to build a version of the adapter with a simple change to not set the level to error, but I suspect that would fix the issue I encountered and make the vs adapter behave consistently with nunit3-console, etc.

**Comment by CharliePoole** [comment] 2016-07-13 01:31
This would be a serious error for sure and would require some changes to both NUnit and the adapter. Please let us know what you find out.

**Comment by CharliePoole** [comment] 2016-07-13 01:35
@simmdan When you say "the overall run had failed" does that imply that you are running with vstest.console.exe?

**Comment by simmdan** [comment] 2016-07-13 01:38
On my CI build machine I run with vstest.console.exe (I'm using VSTS and sticking with vsts.console.exe is the path of least resistance usually).  I believe I was seeing the same issue when running inside VS as well, though.

**Comment by CharliePoole** [comment] 2016-07-13 01:50
I asked because the IDE doesn't do anything particular on failure of a run, beyond displaying all the results. I just confirmed the bug using vstest.console.exe.

As you can see, I vacillated between critical and high priority. Made it merely high because I believe (hope?) that use of stdError in non-error situations will be limited.

**Comment by simmdan** [comment] 2016-07-13 01:55
Thanks for the follow-up.  I've addressed my immediate issue by changing my project to no longer output to stderr.  I was just hoping to help someone else who might find this the hard way.

**Comment by CharliePoole** [comment] 2016-10-22 06:48
Fixed by PR #245. Console.Error output no longer causes error-level logging.

**Closed by CharliePoole** 2016-10-22 06:48 UTC
Labels: easyfix, is:bug, pri:high
