### ISSUE TITLE
Invalid characters in test name breaks test runner

### ISSUE THREAD

**Issue by laura-campbell** [nunit/nunit3-vs-adapter#549] opened 2018-09-27 15:54 UTC
* versions: NUnit 3.0 and NUnit Adapter 3.10.0.21
* Visual Studio Professional version 15.8.5
* .NET framework is 4.6.1

* When a test with a custom name has invalid characters in that name (in this case, '&'), the nunit adapter throws an error and the tests are removed from the window

* Only appears to happen when you select a group of tests

* Doesn't appear to happen on other machines

* repro:  https://github.com/laura-campbell/nunit3bug

```csharp
public class Class1
{
        [TestCaseSource("testcases")]
        public void foo()
        {
        }
        public static IEnumerable<TestCaseData> testcases { get; } = new[] { new TestCaseData().SetName("&") };
}
```

![image](https://user-images.githubusercontent.com/35786146/46157972-e929cf80-c24a-11e8-95f5-2b41630f1f05.png)
test is visible after building the solution

![image](https://user-images.githubusercontent.com/35786146/46158099-27bf8a00-c24b-11e8-971e-63297cceeead.png)
chose to run selected tests on a group of tests

![image](https://user-images.githubusercontent.com/35786146/46158125-373ed300-c24b-11e8-95ab-ed9a2bb973a0.png)
test is not run and disappears from the window

Error message: 

```
[9/27/2018 11:47:55 AM Error] An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing operand. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
```

**Comment by rprouse** [comment] 2018-09-27 16:10
Thanks, looks like a problem parsing the filters that are sent from the test window to the adapter. Does it happen if the test name is more than just `&`, for exampe `apples&pears`?

**Comment by benjamin-hodgson** [comment] 2018-09-27 16:35
> Does it happen if the test name is more than just `&`, for exampe `apples&pears`?

Yes it does. (We encountered it in a test whose name contained a URL with a query string.)

**Comment by rprouse** [comment] 2018-09-27 17:43
Excellent, thanks. That will increase the priority then, especially since `&` is used in URI query params as you mentioned.

**Comment by aboldock** [comment] 2018-11-11 23:55
we are also seeing this problem with 3.10.0.21 with # in the test name and the tests being source from a paramaterised set eg: [Test, TestCaseSource(typeof(AdtPatientTestDataFactory), "TestCases")]
strange thing is not all our devs are seeing the problemonly some, we have changed all our test names to get around this issue on some machines.

**Comment by LangdalP** [comment] 2019-05-21 09:14
I am having the same type of problems. I am from Norway, and in our project we use Norwegian test names. This means that the names may contain æøå and ÆØÅ, which breaks the adapter. We have over a thousand tests, and I don't want to start renaming all of them because of this, so currently I am using the console test runner instead.

**Comment by Macht59** [comment] 2019-08-01 06:48
I have the same problem - just me and non of my colleges. 
In my case the error caused by character '='

**Comment by johnmwright** [comment] 2019-10-28 20:59
This issue has the same underlying cause as #622 and is resolved by PR https://github.com/nunit/nunit3-vs-adapter/pull/668

**Comment by OsirisTerje** [comment] 2019-11-02 15:17
@laura-campbell @Macht59 @benjamin-hodgson @LangdalP @aboldock 
Checking  3.16.0-dev on this one.  To make it work, NUnit also has to be on Version 3.12. 
https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.0-dev-01202


Before:
![image](https://user-images.githubusercontent.com/203432/68072978-ee314a80-fd8b-11e9-848d-dc8ccacf1919.png)

After only adapter upgrade:
![image](https://user-images.githubusercontent.com/203432/68072991-1d47bc00-fd8c-11e9-8afb-b06a58ffe54d.png)

After adapter AND NUnit upgrade:
![image](https://user-images.githubusercontent.com/203432/68072994-29cc1480-fd8c-11e9-9674-d2184129c0ee.png)

All tested with VS 2019 ,  16.3.4

**Closed by OsirisTerje** 2019-11-02 15:17 UTC
Labels: is:bug, pri:high
