### ISSUE TITLE
Hierarchy of TestCase[(...)] not correct in Test Explorer if containing ').' in string argument

### ISSUE THREAD

**Issue by tripplet** [nunit/nunit3-vs-adapter#376] opened 2017-08-15 14:04 UTC
Versions
* NUnit 3.7.1, NUnit3TestAdapter 3.8.0.0
* Visual Studio 2017 - 15.2 (26430.16)
* What .net platform and version is being targeted: Not relevant

The hierarchy of `TestCase[(...)]` items is not correctly displayed in the Visual Studio Test Explorer if one argument contains a string with `).` inside.

Minimum sample:
```cs
namespace test
{
    using NUnit.Framework;

    [TestFixture]
    public class Class1
    {
        [TestCase("correct some text")]
        [TestCase("correct 2 . some text")]
        [TestCase("correct 3 ) some text")]
        [TestCase("correct 4 ) . some text")]
        [TestCase("correct 4 .) some text")]
        [TestCase("not correct ). some text")]
        public void test1(string arg)
        {

        }
    }
}
```
![issue](https://user-images.githubusercontent.com/628197/29319107-1061279c-81d3-11e7-8488-47c05a8907c6.png)

**Comment by CharliePoole** [comment] 2017-08-15 14:13
This would be a bug if confirmed. 

If the problem appears incorrectly in the output from the console runner or nunitlite, then it's most likely an nunit framework bug. 

OTOH, if it only appears in TestExplorer, then we would have to dig deeper to see what we are passing to VS as the name of the test. If we are passing the correct name, then it's a VS bug. Otherwise, it's an adapter bug.

@tripplet If you are able, please let us know if this shows up when running via the console. You can look at the XML output to ascertain the name that we give the test.

**Comment by tripplet** [comment] 2017-08-15 14:25
```
nunit3-console.exe ..\..\..\nunit-issue\bin\Debug\nunit-issue.dll --explore
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    ..\..\..\nunit-issue\bin\Debug\nunit-issue.dll

test.Class1.test1("correct some text")
test.Class1.test1("correct som(. text")
test.Class1.test1("correct 2 . some text")
test.Class1.test1("correct 3 ) some text")
test.Class1.test1("correct 4 ) . some text")
test.Class1.test1("correct 4 .) some text")
test.Class1.test1("not correct ). some text")
```

Xml looks ok too:

```xml
...
<test-case id="0-1006" name="test1(&quot;correct 4 .) some text&quot;)" fullname="test.Class1.test1(&quot;correct 4 .) some text&quot;)" methodname="test1" classname="test.Class1" ... />
<test-case id="0-1007" name="test1(&quot;not correct ). some text&quot;)" fullname="test.Class1.test1(&quot;not correct ). some text&quot;)" methodname="test1" classname="test.Class1" ... />
```

**Comment by CharliePoole** [comment] 2017-08-15 14:56
@tripplet Thanks for checking. SO it looks like it's an adapter issue, either a bug of ours or of VS itself. I'm suspecting VS because there is a history of their attempting to parse our test names to make sense of them. Unfortunately, NUnit test names are arbitrary strings and any resemblance to a class or method name is purely coincidental. NUnit is able to provide the actual class and method name but there doesn't seem to be any way to tell VS about them other than as reflected in the test name.

@OsirisTerje I'm not set up to do this right now... can you check what we pass as a test name to VS?

**Comment by OsirisTerje** [comment] 2017-08-15 14:58
@CharliePoole Yep, can do tomorrow.

**Comment by JornWildt** [comment] 2017-09-08 08:28
I am seeing the same problem here with these test-cases:

    [TestCase("S()/x", new string[] { "Sx" })]
    [TestCase("S(.x", new string[] { "Sx" })]
    [TestCase("S().x", new string[] { "Sx" })]
    [TestCase("S.x", new string[] { "Sx" })]
    public void MyTest(string s, string[] result)
    {
    }

The third one "S().x" does not show up in VS 2017, the others do. I haven't tried the console runner.

**Comment by OsirisTerje** [comment] 2017-09-30 10:05
This looks like it is a Visual Studio bug. 
Using the code from @tripplet , like:
` [TestCase("not correct ). some text")]
        public void TestIt(string arg)
        {
            
        }`

Displayname is:  
TestIt("not correct ). some text")
The xml from NUnit is: 
    <test-case id='6-1001' name='TestIt(&quot;not correct ). some text&quot;)' fullname='ClassLibrary11.Issue376.TestIt(&quot;not correct ). some text&quot;)' methodname='TestIt' classname='ClassLibrary11.Issue376' runstate='Runnable' seed='2035846165' />
            

I'll inform MS about it, and close the issue here.

**Closed** 2017-09-30 10:06 UTC
Labels: closed:notabug

**Comment by jnm2** [comment] 2018-03-04 20:41
Is this the same issue, in 3.9 and current master?

<img src="https://user-images.githubusercontent.com/8040367/36950231-3483dcfa-1fc1-11e8-803a-a6154f190901.png" width="75%" />

<details>
<summary>List of actual names</summary>

```
Decimal_literals_use_digit_separator_when_at_least_five_digits((short)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((short)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((short)-1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((short)-10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ushort)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ushort)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)-1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)-10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)-100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((int)-1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((uint)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((uint)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((uint)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((uint)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)-1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)-10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)-100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((long)-1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ulong)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ulong)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ulong)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((ulong)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)1000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)10_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)100_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-1000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-10_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((float)-100_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-1000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-10_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-100_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-1_000_000)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)1000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)10_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)100_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)1_000_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-1000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-10_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-100_000.1)
Decimal_literals_use_digit_separator_when_at_least_five_digits((double)-1_000_000.1)
```

**Comment by CharliePoole** [comment] 2018-03-04 21:33
This seems like a direct outcome of some of the decisions Microsoft made, which we objected to. Essentially, they parse the names, including any user-created display names, as non-arbitrary strings. We offered other ways they could do this, but...

Resharper isn't quite relevant because it's an extension to VS, not an adapter. That means they create code which is the functional equivalent of what's in the adapter __plus__ what's in the test explorer. Essentially, this is why I think that actual extensions are the better way to go. That's what I'm doing with Test Centric.

**Comment by jnm2** [comment] 2018-03-04 21:35
ReSharper is relevant to me because it gets it right 😜 and I see no reason why VSTest couldn't follow their example and get it right also.

**Comment by CharliePoole** [comment] 2018-03-05 00:03
VSTest can. My point is that if they don't, we can't.

**Comment by jnm2** [comment] 2018-03-05 03:00
So do I understand right that my particular error report should be taken to the VSTest repo?

**Comment by CharliePoole** [comment] 2018-03-05 04:40
You could, although I think we get better results if @OsirisTerje passes it on.

**Comment by OsirisTerje** [comment] 2018-03-06 17:05
I'll talk with them today, and will bring this up too.
