### ISSUE TITLE
Adapter requires test project pbd's to be generated for tests to be executed

### ISSUE THREAD

**Issue by ppejovic** [nunit/nunit3-vs-adapter#276] opened 2016-12-02 00:11 UTC
See #229 

Disabling pbd generation in the project properties of a test project prevents the tests being discovered in Visual Studio. This was for a very basic test project (class library type) I created to test NUnit 3.0. The test project has no dependencies aside from NUnit and NUnit3TestAdapter. 

I believe the problem code is [here](https://github.com/nunit/nunit3-vs-adapter/blob/8a9b8a38b7f808a4a78598542ddaf557950c6790/src/NUnitTestAdapter/NavigationDataProvider.cs#L79):

**NavigationDataProvider.cs#L79**

`var readerParameters = new ReaderParameters() { ReadSymbols = true };`

The [docs ](https://github.com/jbevain/cecil/wiki/Debug-symbols) from Cecil state:

> From an API standpoint, there are two ways of interacting with debug symbols. The easiest is to simply pass `True` to ReaderParameters.ReadSymbols or WriterParameters.WriteSymbols. Cecil will try to load the debug store support assembly depending on the runtime (pdb on .net, mdb on Mono) and read and write the appropriate symbols.

**Comment by CharliePoole** [comment] 2016-12-02 00:28
@ppejovic In my earlier experiments with this, not having the pdb available simply prevented the ide from displaying line numbers, which seemed like a valid tradeoff. In order to reproduce this, can you let me know exactly what versions of VS and the NUnit VS adapter you are using?

**Comment by ppejovic** [comment] 2016-12-02 17:00
@CharliePoole I've added a repro here: https://github.com/ppejovic/nunit3-pbd-repro

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3

**Comment by OsirisTerje** [comment] 2016-12-04 20:21
I can confirm this.   In NUnit2 it behaves as @CharliePoole  says, without a pdb, you can't click and go to source, but in NUnit3 it doesn't show the test at all.

**Comment by CharliePoole** [comment] 2016-12-04 20:47
I made this high priority rather than critical. As a reminder, critical would cause us to do an immediate hotfix release. This doesn't seem in that category, since there's a workaround.

**Comment by OsirisTerje** [comment] 2016-12-25 20:44
@CharliePoole  Just to be clear on what you want:  Should this be closed now or after the PR are merged?  I would assume it is best to close it after the PR merge, right?

**Closed** 2016-12-25 21:26 UTC
Labels: is:bug, pri:high

**Comment by CharliePoole** [comment] 2016-12-25 21:29
Right. I didn't close it because I hadn't read this and you hadn't used any of the formats that would cause it to be done automatically by GitHub. One problem is that occasionally (rarely) we __don't__ want to close an issue because we will be doing more PRs to complete the work. So most of us use the autoclose __except__ when we don't want it to happen. The reviewer can't know what you want to happen, of course, unless you tell him.

**Comment by CharliePoole** [comment] 2016-12-25 21:31
You may also want to know that closed:done issues in the milestone are what we use to create the release notes.
