### ISSUE TITLE
Test list not refreshing if test project is not rebuilt

### ISSUE THREAD

**Issue by sirgru** [nunit/nunit3-vs-adapter#535] opened 2018-08-07 13:55 UTC
I have a use case where I get test data as names of files in the file system.
```
        [TestCaseSource(nameof(GetAllFileNames))]
        public void TestFile(string sourceFileNameWithExtension) {...}
        public static List<string> GetAllFileNames() {...}
```
The tests are not discovered properly. The test explorer sees the list of tests from the time the project was last rebuilt, but if the file system changes and test code doesn't the list of tests will not be refreshed. The console shows: `Error] Test adapter sent back a result for an unknown test case. Ignoring result for`, which I guess means that test adapter did see the change from TestCaseSource, but VS Test Explorer refused to refresh the tests list. I can get the correct behavior by manually building the project after the file system change, which is inconvenient for me.

* NUnit 3.10.1
* NUnit3TestAdapter  3.10.0
* Visual Studio Community 2017 15.5.0
* Framework: netcoreapp2.0
* Runtime: portable

**Comment by OsirisTerje** [comment] 2018-08-07 14:37
Can you please upload a repro project?  (github or zipped here)
Make it as small as you can, it should compile "as is".

I assume you have turned off source based discovery so you're not being tricked by that?

**Comment by sirgru** [comment] 2018-08-07 15:05
Hmm could be that because I didn't use these types of tests before. Could you quickly tell me how to disable source based discovery? This article https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq has something, but I don't have anything in Tools > Options > Test so I guess it's not available in 15.5?

**Comment by sirgru** [comment] 2018-08-07 15:29
[Repro_535.zip](https://github.com/nunit/nunit3-vs-adapter/files/2267022/Repro_535.zip)

Here is the repro just in case.

**Comment by OsirisTerje** [comment] 2018-08-07 15:57
It should be under Tools->Options-Tests, so might not be there in 15.5.  When you start up VS with that solution, do you see the tests appearing ?  That is before you do any builds.

I'll take a look at the repro.

**Comment by sirgru** [comment] 2018-08-07 16:09
Yes, the tests and everything else works fine except in once case:
If the file is added to the file system and project isn't recompiled after that.

**Comment by OsirisTerje** [comment] 2018-08-07 16:28
Discovery is being triggered by the build, and I see that when I just build (not rebuild) after adding a file, the project is being built, since msbuild detects there is a new file.  However, the output is not changed, and that means that discovery doesn't seem to be triggered, or the results not being acted upon.  
So yes, I can repro the behaviour.  I believe this has to do with VSTest, but I'll check a bit more.  
Steps:
-I have 5 files (or whatever number you have)
- I have one trivial test, so should have 6 in total
-Project is built/rebuilt and I see 6 tests
- I add a  new file
- I just Build the solution
The discovery is being started, but no new tests are discovered
![bilde](https://user-images.githubusercontent.com/203432/43789124-824fbcb4-9a6f-11e8-9fc7-3d5b6ca389d7.png)
And  Test Explorer are still showing 6
![bilde](https://user-images.githubusercontent.com/203432/43788771-8eaeb196-9a6e-11e8-83bd-c399aa11efec.png)

The test project now looks like:
![bilde](https://user-images.githubusercontent.com/203432/43788783-9cb1334a-9a6e-11e8-8079-e885e69ae732.png)

So, it seems that the VSTest discovery is somehow deciding it doesn't need to call the adapter.  I think some MSFT need to have a look at this, I'll point them to it.

**Comment by sirgru** [comment] 2018-08-07 16:43
Thanks, it seems the discovery is only triggered when the full rebuild is actually necessary. I can get the correct behavior when I select Build > Rebuild Solution before running the tests.

**Comment by shyamnamboodiripad** [comment] 2018-08-08 01:02
The root cause appears to stem from a difference between what happens when building a .NET Core project v/s old style Desktop project.

* Tests are not being discovered after build for a .NET Core test project. Looks like when the text files (which serve as input to the data driven tests) are added to the project and the project is built, the test binary does not change on disk. TW doesn’t re-trigger discovery in this case because the test ‘container’ binary has not changed on disk. Doing a rebuild on the other hand causes the binary to change on disk and correctly re-triggers discovery.

* If I try the same scenario in a old style Desktop test project (with identical code), and build the project after adding the text file, the output test binary changes on disk and TW ends up re-triggering discovery correctly.

I have uploaded [Repro_535_2.zip](https://github.com/nunit/nunit3-vs-adapter/files/2268534/Repro_535_2.zip) that contains a .NET Core test project (Tests.csproj) as well as a Desktop test project (Tests2.csproj) that you can experiment with to repro the problem.

**Comment by OsirisTerje** [comment] 2018-08-08 14:41
@shyamnamboodiripad So is this a bug in VSTest that will be addressed?  Or is it a bug in the building of .net core ?  
I am not sure why the output would change in a case like this, since the files that are added are not set to be copied to the output, and there is no codechange.  And if  VSTest require a change in the output to activate the adapters, which seems to be the way it works, then this means this is "by design". 

Next, if real time discovery is activated, the discovery will not be run in any case.  Then, if live unit testing is used, the execution will run - and the tests appear.  But then is the question if LUT will react to these files being added ?

**Comment by OsirisTerje** [comment] 2020-05-04 20:13
@shyamnamboodiripad Just checked with VS 2019, 16.5, and it is still the same.

**Comment by OsirisTerje** [comment] 2020-05-04 21:47
@sirgru    @shyamnamboodiripad  Link to MS issue:  https://developercommunity.visualstudio.com/content/problem/1017186/test-explorer-not-refreshing-with-data-driven-test.html

**Comment by OsirisTerje** [comment] 2021-05-09 16:22
The issue has not been voted up nor commented on at the developer community site, so closing it here.

**Closed by OsirisTerje** 2021-05-09 16:22 UTC
Labels: is:bug, VS Issue, External, closed:SomebodyElsesProblem, ReportedToMS, closed:fixedinnewversion
