### ISSUE TITLE
TestExplorer in Visual Studio 15.5.x navigates to Feature.cs code behind 

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#441] opened 2018-01-27 15:58 UTC
_From @QAGal2 on January 26, 2018 13:6_

Given NUnit.Console* 3.7, NUnit 3.9.0,  Visual Studio 15.5.4 (or 15.5.2), SpecFlow & SpecFlow.NUnit 2.2.1
Then double click on a test in Test Explorer,  brings us to the feature.cs code behind file instead of the feature file. This issue began after I upgraded from Visual Studio 15.4.4 (no other changes).

**See Specflow Thread**: https://github.com/techtalk/SpecFlow/issues/990 
      community is pointing cause to NUnit

[DemoFeatureIssue.zip](https://github.com/nunit/nunit-console/files/1667773/DemoFeatureIssue.zip)
Video of behavior: https://www.screencast.com/t/LG6GTFbWGIny

_Copied from original issue: nunit/nunit-console#362_

**Comment by rprouse** [comment] 2018-01-27 15:58
Visual Studio 15.5 handles source locations now whereas NUnit handled it previously. On my phone right now, but will report to the VS team. This issue also belongs in the adapter repo, I will move it there.

**Comment by rprouse** [comment] 2018-01-27 15:58
_From @OsirisTerje on January 26, 2018 14:4_

@rprouse VS doesnt quite handle it yet, it is still behind a feature flag, so this sounds like our stuff.  But, agree, belong so far in adapter repo.

**Comment by rprouse** [comment] 2018-01-27 15:58
Thanks @OsirisTerje, moving to the adapter repo. @QAGal2 please follow the issue there.

**Comment by JoeBarber27** [comment] 2018-01-30 12:17
I had the same issue and a peer found a fix online which has solved the issue for me.
I disabled the extension "Dotnet Extensions for Test Explorer" 

Original Post:
https://developercommunity.visualstudio.com/content/problem/158160/unable-to-fetch-source-information-for-test-method.html

**Comment by QAGal2** [comment] 2018-01-30 12:33
Yes. Tools -> Extensions and updates , "Disable Extensions for Test Explorer" v 15.3..0.4 appears to work for me to fix VS 15.5.x

**Comment by Phil-87** [comment] 2018-02-01 10:16
Where exactly is the "Disable Extensions for Test Explorer" option? I don't see it in the Extensions and Updates window.

**Comment by OsirisTerje** [comment] 2018-02-01 10:35
It should be installed by default,  but if you don't see it, you don't have it, and then its good.
On my machine it looks like:
![image](https://user-images.githubusercontent.com/203432/35674134-fa3f5f14-0743-11e8-8698-391f32ccb9b3.png)

**Comment by Phil-87** [comment] 2018-02-01 10:53
Thanks @OsirisTerje that fixed the problem for me (VS 15.5.4).

**Comment by OsirisTerje** [comment] 2018-02-02 18:31
I'm closing this, as this is a non-finished new feature in VS.

**Comment by QAGal2** [comment] 2018-02-02 18:44
Can you explain what that 'non-finished' new feature means to end users?
It used to work in VS 2017 15.4.x, but broke in 15.45.x, so why do we call it a 'new feature'?
Are we waiting for  VS people to fix this?  
 I am still pretty much broken with Specflow  with 15.5.x. I can go from TestExplorer to feature file, but unable to set breakpoints there   or navigate from feature to Steps.

**Comment by OsirisTerje** [comment] 2018-02-02 19:02
The Real Time discovery is the new "non-finished" feature.  It should hide behind the feature flag, but somehow didn't.  Removing the dotnet test explorer extensions seems to fix it for the cases I have heard of.  

There are no changes to the adapter that should cause something to behave different in 1.5.4 versus 15.5. 

Do you mean that removing that extension, does *not* fix it for you?

With that extension removed, it should behave as it always have done.

**Comment by QAGal2** [comment] 2018-03-06 16:56
VS2017 15.6 fixed this issue. But for my team, it required a fresh reinstall of vs2017 and then reapply of Specflow for VS2017 extension.

**Comment by joelransom** [comment] 2018-03-16 17:34
I had forgotten about this issue. I installed VS 15.6.2 yesterday and it happened again. Now, disabling Dotnet extensions for test explorer doesn't help. 

At first, my tests wouldn't even run, I got "System.InvalidOperationException Message=unknown error: call function result missing 'value'" from ChromeDriver. But updating chromedriver.exe to latest version fixed that problem. (Unrelated?)

Any suggestions about steps to fix test explorer would be appreciated. I don't want to start tearing VS  apart unnecessarily.

**Comment by ManishJayaswal** [comment] 2018-03-20 05:20
I am from the VS unit testing team. Can someone familiar with specflow answer the following for us so that we can investigate this issue from VS side?
•	Is this features file generated by SpecFlow or hand authored by users? 
•	Are they part of the project?

@rprouse @OsirisTerje  - do any of you know how NUnit was previously finding the source location that corresponds to features file? Is that what you get if you crack open the pdb?

**Comment by joelransom** [comment] 2018-03-20 06:17
The feature file (.feature) is authored bt the user. Tbe cs file (.feature.cs) is generated by Specflow. Yes they are part of the oroject.

________________________________

**Comment by ManishJayaswal** [comment] 2018-03-20 06:28
@shyamnamboodiripad  - FYI
Thanks @joelransom ! 
When is the .feature.cs file generated? On save, on build? Additionally, does it get regenerated with every save/build of the project?
Roslyn workspace ( which we now use to determine the source location of a test) probably does not know the relationship between the .features and .features.cs file. It only knows about the .cs files hence that's what is getting set as source location. I am curious as to how it was working before as I don't think that .feature source location would be put in the pdb file either. Perhaps @rprouse can shed some light on this?

**Comment by ManishJayaswal** [comment] 2018-03-20 06:38
@shyamnamboodiripad-  on this comment above "EDIT: Once I run a test from test explorer, dbl-clicking on it takes me to the feature file. The other tests still take me to feature.cs file." - I wonder if source based discovered tests are pointing to the .features.cs file but after the test is run and we get the right source location?
@joelransom - can you try cleaning the solution and rebuilding it and then try to double click on any test to see where it takes you?

**Comment by rprouse** [comment] 2018-03-20 12:49
I am not aware of any special code in the adapter that would translate the source location from the CS file to the feature file. @OsirisTerje that is correct isn't it? Is it possible that SpecFlow rewrites the source location information in the PDB file as a post build step?

Unfortunately, we get many SpecFlow issues reported against NUnit, but despite reaching out have never had any input from the SpecFlow team. Since they are a commercial product and do not work with us, taking the time to learn SpecFlow and reverse engineer how they interact with NUnit is low on our list of priorities.

**Comment by OsirisTerje** [comment] 2018-03-20 12:52
Correct, there is no code for specflow in the adapter.  We need to let the specflow team handle this, they are surely using our adapter, but as long as they dont reach out, there is nothing we can do here.

**Comment by joelransom** [comment] 2018-03-20 15:30
Cleaning/rebuilding etc has no effect.

________________________________

**Comment by ManishJayaswal** [comment] 2018-03-20 16:06
tagging @SabotageAndi from SpecFlow to answer these. I synced up with him offline and he mentioned he will type up a response soon.

**Comment by SabotageAndi** [comment] 2018-03-20 16:29
Hi, I am from the SpecFlow team. @ManishJayaswal pointed me to this issue.

First some information about the commerical status of SpecFlow. It is an Open Source project under the BSD license created by my company. TechTalk (my company) has some commercial products around the Open Source core (like a specialized test runner).

But aside from that, the cooperation between our teams could be better. We are a small team and have simply the workforce to monitor the issues for every unit test framework we are supporting. Please tag me or @gasparnagy on issues you get because of SpecFlow or point them to our repo to open there issues for their problem. We will then have a look at them.

Here are some informations about SpecFlow:
The code-behind files are generated when you save the feature- file or at compile time when you use our MSBuild integration. The MSBuild integration is optional, so for most of the users the code-behind file is generated by saving the file. FYI: for that you need the VS Extension of SpecFlow installed.
In the code-behind file we generate a test class for the configured unit test provider (we support also MSTest and XUnit) and use the attributes of them. I know we are not yet using the latest attributes of NUnit.

Here some example of the files:
Feature file: https://github.com/techtalk/SpecFlow-Examples/tree/master/BowlingKata/BowlingKata-Nunit/Bowling.Specflow/Features
Code- Behind file: https://github.com/techtalk/SpecFlow-Examples/blob/master/BowlingKata/BowlingKata-Nunit/Bowling.Specflow/Features/ScoreCalculation.feature.cs

The only thing where we provide information about the original feature file and line numbers for all unit test frameworks is via the #line pragma (see https://github.com/techtalk/SpecFlow-Examples/blob/master/BowlingKata/BowlingKata-Nunit/Bowling.Specflow/Features/ScoreCalculation.feature.cs#L27).

We don't rewrite some pdbs or doing other crazy stuff. So it's only this pragma commands.

This issue is also not only limited to NUnit. We got also feedback from users with XUnit (https://github.com/techtalk/SpecFlow/issues/990#issuecomment-352620259) and MSTest (https://github.com/techtalk/SpecFlow/issues/990#issuecomment-354980276).

To be honest, I am not sure since when this doesn't work anymore, as most of the time I am using our own test runner. But my quick tests in January (https://github.com/techtalk/SpecFlow/issues/990#issuecomment-356262853) showed that it worked with NUnit 2 and MSTest v1.

In our own test adapter we save the origin location in one of our own attributes (https://github.com/techtalk/SpecFlow-Examples/blob/master/BowlingKata/BowlingKata-German/Bowling.Specflow/Features/Punkteberechnung.feature.cs#L21)

@rprouse @OsirisTerje  Is there any other way we can provide the file and linenumber to NUnit?

**Comment by rprouse** [comment] 2018-03-21 00:17
@SabotageAndi thanks for joining the discussion. I'm sorry if I sounded down on SpecFlow. We are also a small team of volunteers and receive too many issues that should be reported to your repo. Now that we know who to contact, I will pull you in where necessary.

Based on the fact that this worked prior to 15.5.x and seems to have broken for all test frameworks, it sounds like it might be a Visual Studio problem. We can debug the NUnit extension and ensure that the `#line` pragmas are still being respected by us.

**Comment by rprouse** [comment] 2018-03-21 00:17
I am going to reopen this and put the confirm label on it.

**Comment by shyamnamboodiripad** [comment] 2018-03-21 01:17
I am not 100% certain, but this may have stopped working when we did the work to stop fetching 
source information from pdbs by default in the adapter (and to look up source information by fully qualified name after discovery in VS) to optimize performance. (cc @Shyam-Gupta FYI)

I believe the C# compiler stores the line number information present in #line directives in the pdbs it generates. So if we were fetching this information from the pdbs before the above fix then it is clear why this would have stopped working when we stopped looking in pdbs and started relying on the test's fully qualified name to deduce its source location.

This is controlled by the following setting in the adapter. It would be interesting to check whether the source navigation is fixed if we set this to true in the adapter and then trigger a build to ensure that the test is discovered via the adapter (instead of source based discovery).

https://github.com/nunit/nunit3-vs-adapter/blob/d8943d87ecccc097224494f905df287d79f097b3/src/NUnitTestAdapter/AdapterSettings.cs#L98

If the above analysis is correct, then this means we would need to fix the new source information fetch mechanisms in VS to respect #line directives.

**Comment by ManishJayaswal** [comment] 2018-03-21 05:34
@shyamnamboodiripad - I think your analysis is right. Let's open a VS bug to address this and then report back on this issue when it is fixed.
@SabotageAndi - thanks for joining in the discussion and providing clarification on specflow implementation.

**Comment by QAGal2** [comment] 2018-03-21 13:35
My last issue, Git-related, that started this additional issue chain, I resolved today.
(thank you rprouse for spinning it off on my behalf).
The Git-solution needed the NUnit3UnitAdapter to find the source as it ran a test.
All last year, VS2017 + Test Explorer had successfully worked without it.
My VSTS source code solutions, all had that adpater nuget pkg, because they run tests as part of MSBuild process. The Git solution(s), meanwhile, have not been integrated into the build process, and thus was without testadapter pkg, but still working ok.

with this checked on - Tools,Options, Test, Discover tests in real time from source files
with this enabled - Tools, Extensions and Updates, DotnetExtensions for Test Explorer
With this combo:
     VS 2017 15.6.0, NUnit 3.10.1,NUnit3TestAdapter 3.10.0, NUnit.ConsoleRunner 3.8.0
     SpecFlow & SpecFlow.NUnit 2.3.1

I can navigate from Test Explorer to SpecFlow .feature and from .feature to Steps
I can successfully run tests from test explorer for both vsts & Git sourcecode solutions.

Thank you to all you software supporters who have managed to locate each other and communicate.
As an nunit users for 15 years, I know Nunit has always provided excellent support, even back when charlie P. answered directly. I had thought there was more communication between VS and SpecFlow then there was...and I am not use to such frequent releases for VS or from getting test improvements.

Because of all the chatter on 15.6.2+, I will stay on 15.6.0, and try to get my QA team members 
back onto vs2017 again. It had worked for them...then stopped again for still unknown reasons. They admit they had stopped telling me when they revert back to vs2015.

**Comment by SabotageAndi** [comment] 2018-05-11 15:08
@ManishJayaswal any update on this?

**Comment by ManishJayaswal** [comment] 2018-05-11 21:13
@SabotageAndi - we have not been able to get much traction on this. We need to understand why the source information provider is not honoring the #line directive which pdb generator handles correctly. We have an open issue internally tracking this so hopefully we would get to it soon.

**Comment by LirazShay** [comment] 2018-05-15 13:26
@SabotageAndi
This bug also happens to me,
But I see that in the generated files there are no #line pragmas at all. maybe the bug is in the generation of the code behind?
I'm using the latest VS2017 - 15.7.1
NUnit 3 Test Adapter V.3.10.0.0 (latest)
SpecFlow extension for Visual Studio 2017.1.14 (latest)
NUnit 3.10.1 (latest)
SpecFlow 2.3.2 (latest)

Do you know about any workarounds?
I've tried to disable the Test Discovery options in the Options screen and also disabled the Dotnet extensions for Test Explorer those operations didn't solve the problem.
Since there are no #line pragmas nothing will help?

**Comment by SabotageAndi** [comment] 2018-05-15 13:55
@LirazShay if you have no pragmas, this has nothing to do with this issue. Please create a new issue in the SpecFlow repo: https://github.com/techtalk/SpecFlow/

**Comment by SabotageAndi** [comment] 2018-05-15 14:25
@LirazShay  This issue is about, that the info from the pragmas are not used for discovery. You don't have any pragmas in your code-behind file, which is something in SpecFlow which generates the code-behind files. So nothing todo with NUnit and the TestAdapter, but with the SpecFlow code behind file generation. The pragmas are generated normally (see https://github.com/techtalk/SpecFlow-Examples/blob/master/BowlingKata/BowlingKata-Nunit/Bowling.Specflow/Features/ScoreCalculation.feature.cs#L27).

**Comment by LirazShay** [comment] 2018-05-15 14:44
@SabotageAndi 
My mistake.
Sorry, while trying to find a solution to this issue I've changed the allowDebugGeneratedFiles="true". that causes to disappearing of the line pragmas?
I guess so because when I changed it to false the line pragmas were added but the Test Explorer still did not navigate to the feature files

**Comment by LirazShay** [comment] 2018-06-04 16:29
@ManishJayaswal 
Hi, can you help us with it?
There were so many updates to visual studio 2017, but no one solved this issue,
Is there any open issue not private in  Visual Studio Developer Community or something?
Please note that this issue is very important for the BDD community of C#, we're suffering from this a lot. 
Every update of Visual Studio I disappointed again

**Comment by ManishJayaswal** [comment] 2018-06-04 16:36
We have an internal open issue on this but we have not been able to investigate and resolve it yet. We will try to prioritize it. Sorry about the delay here.
@Shyam-Gupta - FYI

**Comment by LirazShay** [comment] 2018-06-05 12:38
@ManishJayaswal 
@shyamnamboodiripad 
@SabotageAndi 
@rprouse 

I've opened a bug about this issue in VisualStudio developer community.
https://developercommunity.visualstudio.com/content/problem/267390/text-explorer-specflow-tests-goes-to-the-feature-c.html

Could you please vote or add your own thoughts there? so that someone will not wrongly close it (might think not a bug or bug in SpecFlow)

**Comment by ManishJayaswal** [comment] 2018-06-05 16:14
@LirazShay - thanks! I have linked it to the right internal bug so you can use that feedback item to track the progress on that issue.

**Comment by rommel-baltazar** [comment] 2018-06-19 05:51
Currently works for me on the following set up:

Visual Studio 2017 Version 15.6.4

Extensions:
1. Disabled Dot Net Extensions for Test Explorer
2. Nunit 3 Test Adapter 3.10
3. SpecFlow for Visual Studio 2017 2017.1.14

Nuget:
1. Specflow 2.3.1
2. NUnit 3.10.1

**Comment by LirazShay** [comment] 2018-06-20 14:55
@rommel-baltazar 
For me it still doesn't work:
Visual Studio 2017 Pro Version **15.7.3**

Extensions:

Disabled Dot Net Extensions for Test Explorer
Nunit 3 Test Adapter 3.10
SpecFlow for Visual Studio 2017 2017.1.14
Nuget:

Specflow 2.3.1
NUnit 3.10.1

What is your Test Discovery settings?
![image](https://user-images.githubusercontent.com/16083652/41666384-169e6fc4-74b3-11e8-9b80-2539374bb795.png)

**Comment by LirazShay** [comment] 2018-06-24 13:31
@rommel-baltazar 
Sorry, your Visual Studio 2017 Version 15.6.4 is not updated,
the latest version is 15.7.3
Could you please update the visual studio and see if this still happens?

**Comment by rommel-baltazar** [comment] 2018-06-25 00:31
Hi @LirazShay ,

Sorry, can't do that as I risk breaking my config. Was just sharing my setup as it might be helpful for someone to use the setup while waiting for the permanent fix.

Was reading the comments in https://developercommunity.visualstudio.com/content/problem/158160/unable-to-fetch-source-information-for-test-method.html and noted that Microsoft fixed the issue in VS 15.6.2 and someone raised that he was encountering the issue again in 15.6.6. So it seems the fix was somewhat lost on either VS 15.6.5 or 15.6.6 and is still not fixed up to your version (15.7.3).

**Comment by LirazShay** [comment] 2018-07-04 08:23
###  Good news!!!
We've been told [here](https://developercommunity.visualstudio.com/comments/285673/view.html) that VS team have fixed the problem in an upcoming 15.8 preview 4 release. 
Thanks for everyone who helped with it!!! 
Thanks you for helping us build a better Visual Studio!

**Comment by kendrahavens** [comment] 2018-10-25 20:18
I believe this issue can be closed as it was fixed in 15.8 Preview 4. If anyone is still experiencing it, please let us know on [developer community](https://developercommunity.visualstudio.com/).

**Comment by joelransom** [comment] 2018-10-25 20:21
Agreed.

________________________________

**Closed** 2018-10-25 20:30 UTC
Labels: External, VS Issue, confirm

**Comment by OsirisTerje** [comment] 2018-10-25 20:31
Thanks for pointing it out, Kendra.  
Have you looked through the other open VS issues we have here too?  Might be more that is fixed.

**Comment by kendrahavens** [comment] 2018-10-25 20:55
I have, I'm still following up on some. A few were pushed to VS2019 timeframe. I'll share what updates I can.

**Comment by comecme** [comment] 2023-03-08 14:56
The problem seems to have reappeared in VS2022 v17.5.

I have created a [new issue in Microsoft Developer Community](https://developercommunity.visualstudio.com/t/Test-Explorer-SpecFlow-tests:-goes-to/10303967?), but as I am only a user of SpecFlow and not a collaborator, I wasn't able to provide much information. Maybe someone can add more info to my issue?

**Comment by OsirisTerje** [comment] 2023-03-08 15:02
@comecme This is not good.  Does the repro solution that is in the old devcom issue still works, and can that be used as a repro for the new one?

**Comment by comecme** [comment] 2023-03-08 15:11
I don't know. What do you mean by "devcom"? This thread doesn't mention "devcom" anywhere. I did download the DemoFeatureIssue.zip file mentioned in the original post and it does have the issue in VS2022 v17.5.1.

In VS2019 v16.11.24 the problem doesn't occur.

But that zip-file contains an already generated SpecFlowFeature1.feature.cs file. In my real world situation we use generate on build. We don't use the SpecFlowSingleFileGenerator.

**Comment by OsirisTerje** [comment] 2023-03-08 17:33
1. Can you upload the zip file ?
2. Can you provide a new small repro that doesn't use the SpecFlowSingleFileGenerator ?

**Comment by gasparnagy** [comment] 2023-03-09 09:01
There is a better issue on Microsoft Developer Community about this: https://developercommunity.visualstudio.com/t/Test-Explorer-SpecFlow-tests:-goes-to/10291227

It seems, that the issue is in VS and being fixed (but not released yet). The issue was not NUnit specific, it was aslo reproducible with MsTest and xUnit, so I suggest the issue here should be closed.

**Comment by OsirisTerje** [comment] 2023-03-09 10:33
Thanks @gasparnagy .
