### ISSUE TITLE
NUnit test cases not run from inherited class.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#226] opened 2016-08-27 01:29 UTC
@corliss commented on [Sun Feb 02 2014](https://github.com/nunit/nunit-vs-adapter/issues/22)

I found a stackoverflow [question](http://stackoverflow.com/questions/14505548/nunit-test-cases-not-run-from-inherited-class) that discusses this very issue.
That question has to do with the ReSharper test runner, but the same buggy behavior exists in the NUnit VS adapter.

The NUnit standalone runner works correctly, so this bug is probably not in NUnit Core.

I'm a bit surprised that this has not been reported before, or fixed yet, as abstract test fixtures are getting increasingly popular.

Any workarounds (or even better, a quick fix) are greatly appreciated, this technique is a core part of our current test plan.

EDIT: It turns out that running tests explicitly from the test class node in Test Explorer does run all the tests and test cases in the base class.

However:

1) Running tests using CtrlR+CtrlT (TestExplorer.DebugAllTestsInContext) runs only the [Test]'s in the base class, not the [TestCase]'s. 

2) Double clicking on a such a TestCase in Test Explorer does not navigate to the correct file and line in the abstract text fixture.

This reduces the severity to a major inconvenience, but at least there is a workaround. A fix is still very appreciated.

---

@CharliePoole commented on [Tue Dec 01 2015](https://github.com/nunit/nunit-vs-adapter/issues/22#issuecomment-161108441)

Both the priority and the assignment to the fix-in-both milestone are dependent on confirming the bug.

---

@CharliePoole commented on [Tue Dec 08 2015](https://github.com/nunit/nunit-vs-adapter/issues/22#issuecomment-162871073)

@OsirisTerje I moved this from 3.0-Only because it seemed like it should either be fixed in both or closed if not confirmed. Is there some reason not to fix in 2.0 if confirmed? Note that I'm the one who gave it a priority:normal - you may not agree.

**Comment by rprouse** [comment] 2016-10-14 21:36
I am unable to confirm this in the latest version of the 3.0 adapter.

I tried with generic base classes, abstract base classes and generic abstract base classes.

1. Clicking in the base classes and using Ctrl+R Ctrl+T runs the base tests as expected.
2. Double clicking on the TestCase in TestExplorer takes me to the source, and I can see the source link in the output window,

![image](https://cloud.githubusercontent.com/assets/493828/19403348/a6f45d62-9234-11e6-8f3f-ce65561db50c.png)

![image](https://cloud.githubusercontent.com/assets/493828/19403353/aff77f0c-9234-11e6-8ff8-81b6a7cc34d1.png)

I am using Visual Studio 2015 Update 3 with the latest version of the VS adapter installed.

I am closing this as no-repro. If you can attach a repro, we can reopen.

**Closed by rprouse** 2016-10-14 21:36 UTC
Labels: confirm, is:bug, pri:normal

**Comment by rprouse** [comment] 2016-10-14 21:38
@corliss I have closed this issue because I cannot reproduce what you are seeing. Please see my previous comment. Sorry I forgot to mention you in it.
