### ISSUE TITLE
Print to console not shown with v3 of adapter

### ISSUE THREAD

**Issue by sbhanderi** [nunit/nunit3-vs-adapter#132] opened 2016-03-15 12:03 UTC
When running tests via VS, console out used to be shown in console with v2 of adapter.
V3 adapter does not show any output. ie if there are calls to Console.WriteLine("xxxxx")

**Comment by CharliePoole** [comment] 2016-03-15 16:51
This is really just a side effect of nunit/nunit#1139 and should be fixed when it is fixed in NUnit and we update the adapter to use the new version.

**Comment by sbhanderi** [comment] 2016-03-16 16:09
I don't know if this is known.
When running tests via V3 adapter, there are no console outputs. Even at the end of the test.
nunit/nunit#1139 implies that the output is show when the test is completed.
Whilst correctly the console output is shown at the end of each test when using nunit3-console.exe to the tests.

**Comment by CharliePoole** [comment] 2016-03-16 20:48
@sbhanderi That's correct. NUnit console displays text output from tests at the end of __each__ test. A summary report is produced at the end of the test run. This has been the case since NUnit 3.0. Before that, output was sent to the console immediately as it was produced. That's what nunit/nunit#1139 addresses, asking that we provide some way to send immediate output to the console.

I didn't meant to imply that the current issue will not be fixed __automatically__ by resolving the NUnit issue, only that we can't effectively fix it until that issue is fixed.

While we wait, tell me where you would like to see that output.

**Comment by sbhanderi** [comment] 2016-03-17 14:36
![capture](https://cloud.githubusercontent.com/assets/6664067/13849162/de302f92-ec4c-11e5-9123-74e5cdb5e7dd.PNG)
I have attached a screen shot of where I expect the output to be written.
So I have  NUnit3 Test Adapter loaded into VS Premium 2013.
![capture](https://cloud.githubusercontent.com/assets/6664067/13849287/62046e3c-ec4d-11e5-9b0a-2cfd98d4f616.PNG)
I run a test, and expected the text output to be written in the Output "Tests" window, at some stage of the test, be it start, end real-time, but I never saw it written out.

**Comment by rprouse** [comment] 2016-03-17 14:54
The NUnit 3 adapter currently works like MSTest and the output is available in Test Explorer. For example, when I run this test,

```C#
[Test]
public void PassingMethod()
{
    Console.WriteLine("Write to the console");
    TestContext.WriteLine("Write to the TestContext");
    Assert.Pass("Your first passing test");
}
```

And then click on the test in Test Explorer, the results at the bottom of the window has an output link,

![image](https://cloud.githubusercontent.com/assets/493828/13849751/e044dd42-ec2d-11e5-8c11-0e2bb326f081.png)

Clicking on that link opens a new window with the output,

![image](https://cloud.githubusercontent.com/assets/493828/13849789/0592794c-ec2e-11e5-910c-5965223859cc.png)

If you have CodeLens, you can also get to the output by clicking on the green/red circle above your test;

![image](https://cloud.githubusercontent.com/assets/493828/13849870/3e3fdfbe-ec2e-11e5-8522-d4644b1e8998.png)

**Comment by sbhanderi** [comment] 2016-03-17 15:51
Thanks for that info.
I am sure the output used to go the Output "Test" area.
I suppose that was the case when the output was written immediately as the test was run.(My prefered mode).

**Comment by CharliePoole** [comment] 2016-03-17 16:29
We'll have to decide what to do with any immediate output once NUnit is producing it. The output window is probably the best location in that case.

**Comment by MeirionHughes** [comment] 2016-04-12 08:16
Had to downgrade to 2 in order to debug a really obscure async issue that only reliably reproduced when running multiple tests. Unfortunately, when concurrently running multiple-tests with resharper + nunit 3, you lose the console output entirely. If you run only one test, its fine.

**Comment by CharliePoole** [comment] 2016-04-12 09:57
Any problems you have with running under red-carpet are unconnected to this issue about the nunit adapter.

**Closed** 2016-07-02 20:11 UTC
Labels: bug, pri:normal

**Comment by lealb** [comment] 2018-01-16 08:49
up to now, in Nunit 3.9.0.0, It still looks like this

**Comment by dariusdamalakas** [comment] 2018-01-16 19:49
@lealb same here.   It looks like `Console.WriteLine` is not visible in console.

This is the test:
````
[Test]
public void Test1()
{
      Console.WriteLine("XXXXXXXXXXX");
}
````

And i do not see this output when running tests from console.  Full output below:

````
 dotnet test
Build started, please wait...
Build completed.

Test run for C:\Users\dariu\projects\rankup\hackerrank\warmup\plus-minus\plusminus.tests\bin\Debug\netcoreapp2.0\plusminus.tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.9.0.0: Test execution started
Running all tests in C:\Users\dariu\projects\rankup\hackerrank\warmup\plus-minus\plusminus.tests\bin\Debug\netcoreapp2.0\plusminus.tests.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.9.0.0: Test execution complete

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.7091 Seconds
````

**Comment by rprouse** [comment] 2018-01-23 02:14
@dariusdamalakas your issue is a separate one with `dotnet test`. Your issue is a duplicate of #343 if you would like to track it or add more info.

**Comment by dariusdamalakas** [comment] 2018-01-23 07:20
@rprouse much appreciated! thanks.
