### ISSUE TITLE
Tests using other attributes than TestAttribute does not get marked as tests

### ISSUE THREAD

**Issue by appel1** [nunit/nunit3-vs-adapter#55] opened 2015-10-13 07:07 UTC
In the Visual Studio text editor tests are marked as tests with a small icon that shows the last test result. That only seem to work for tests using TestAttribute. Is this because of some limitation with the Visual Studio test runner? 

Using Visual Studio 2015.

**Comment by rprouse** [comment] 2015-10-14 14:33
I can confirm this, but expect that it is because MSTest does not have an equivalent for TestCase or something like a row test. @OsirisTerje, can you confirm that.

**Comment by CharliePoole** [comment] 2015-10-14 15:34
In theory, they should be able to mark any test for which we provide a file
name and line number. Can you confirm that that we do provide such info for
these tests?

**Comment by OsirisTerje** [comment] 2015-10-15 20:34
The small icon you refer to is a Codelens Test Indicator, and that doesn't recognize the TestCases.  If you look in the Test Explorer you see that all test cases are shown there, so the adapter does what it should do.  
So, there is a bug in the Codelens indicator.  I'll ask the PG if they are aware of this.

**Comment by OsirisTerje** [comment] 2015-10-15 20:46
@CharliePoole   We provide name and linenumbers, as the navigation from Test Explorer to code works for these too, and I can't see anything in our codebase that differs for these.

**Comment by CharliePoole** [comment] 2015-11-15 04:53
I'm closing this as not a bug - or not our bug anyway!

**Closed by CharliePoole** 2015-11-15 04:53 UTC

**Comment by tparikka** [comment] 2017-03-23 14:36
If anyone still watching this issue wants to raise this to Microsoft, I've added a Uservoice request for it at the request of Microsoft's social media team as they told me they had no previous requests for this enhancement.

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18701998-codelens-doesn-t-detect-parameterized-nunit-tests
